'use strict';

class January2022NewsApp extends React.Component {
 render() {
      return e("div", null,
e(NewsList, {newsType: "Non Media News", newsTitle: "Maternal Outcomes After Severe Acute Respiratory Syndrome Coronavirus 2 (SARS-CoV-2) Infection in Vaccinated Compared With Unvaccinated Pregnant Patients", newsSource: "Obstetrics and Gynecology", newsDate: "January 2022", newsLink: "https://journals.lww.com/greenjournal/fulltext/2022/01000/maternal_outcomes_after_severe_acute_respiratory.14.aspx"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Nation wide assessment of energy costs and policies to limit airborne infection risks in U.S. schools", newsSource: "Science Direct", newsDate: "January 2022", newsLink: "https://www.sciencedirect.com/science/article/pii/S2352710221013917"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "Predictors of smell recovery in a nationwide prospective cohort of patients with COVID-19", newsSource: "Science Direct", newsDate: "January - February 2022", newsLink: "https://www.sciencedirect.com/science/article/pii/S0196070921003409"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Characterisation of COVID-19 deaths by vaccination types and status in Malaysia between February and September 2021", newsSource: "Lancet", newsDate: "January 1, 2022", newsLink: "https://doi.org/10.1016/j.lanwpc.2021.100354"}),               
e(NewsList, {newsType: "Media News", newsTitle: "Bans on hospital visitors necessary ‘last resort’ in coming weeks, NHS chief says", newsSource: "Guardian", newsDate: "January 1, 2022", newsLink: "https://www.theguardian.com/world/2022/jan/01/hospitals-may-have-to-reintroduce-visitor-bans-health-chief-says"}),
e(NewsList, {newsType: "Media News", newsTitle: "How much longer can China keep up its zero-Covid strategy?", newsSource: "Guardian", newsDate: "January 1, 2022", newsLink: "https://www.theguardian.com/world/2022/jan/01/china-zero-covid-strategy-beijing-policy-protecting-public-health-coronavirus"}),
e(NewsList, {newsType: "Media News", newsTitle: "Schools in England told to wear masks in class as fears mount of Omicron surge", newsSource: "Guardian", newsDate: "January 1, 2022", newsLink: "https://www.theguardian.com/world/2022/jan/01/schools-in-england-told-wear-masks-in-class-as-fears-mount-of-omicron-surge"}),
e(NewsList, {newsType: "Media News", newsTitle: "‘There is no money left’: Covid crisis leaves Sri Lanka on brink of bankruptcy", newsSource: "Guardian", newsDate: "January 2, 2022", newsLink: "https://www.theguardian.com/world/2022/jan/02/covid-crisis-sri-lanka-bankruptcy-poverty-pandemic-food-prices"}),
e(NewsList, {newsType: "Media News", newsTitle: "U.S. is considering recommending that individuals exposed to Covid end isolation if they’ve tested negative for the virus after five days, Dr. Fauci says", newsSource: "CNBC", newsDate: "January 2, 2022", newsLink: "https://www.cnbc.com/2022/01/02/us-is-considering-recommending-that-individuals-exposed-to-covid-end-isolation-if-theyve-tested-negative-for-the-virus-after-five-days-dr-fauci-says.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "Covid clinics: hope and high prices on the long road to recovery", newsSource: "Guardian", newsDate: "January 2, 2022", newsLink: "https://www.theguardian.com/global/2022/jan/02/covid-clinics-hope-and-high-prices-on-the-long-road-to-recovery"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Identification of TCR repertoires in functionally competent cytotoxic T cells cross-reactive to SARS-CoV-2", newsSource: "Nature", newsDate: "January 2, 2022", newsLink: "https://doi.org/10.1038/s42003-021-02885-6"}),
e(NewsList, {newsType: "Media News", newsTitle: "U.S. considers recommending negative Covid test before people end isolation period, Fauci says", newsSource: "CNBC", newsDate: "January 2, 2022", newsLink: "https://www.cnbc.com/2022/01/02/us-is-considering-recommending-that-individuals-exposed-to-covid-end-isolation-if-theyve-tested-negative-for-the-virus-after-five-days-dr-fauci-says.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "Doctors worry about hospital capacity as virus cases surge", newsSource: "AP News", newsDate: "January 2, 2022", newsLink: "https://apnews.com/article/coronavirus-pandemic-health-kansas-wichita-88603449fc0b107d53658b182931224f"}),
e(NewsList, {newsType: "Media News", newsTitle: "Advocates fear suspensions could add to pandemic pain for vulnerable students", newsSource: "NBC News", newsDate: "January 2, 2022", newsLink: "https://www.nbcnews.com/news/education/school-suspension-covid-mental-health-rcna10329"}),
e(NewsList, {newsType: "Media News", newsTitle: "Wastewater samples reveal record levels of coronavirus across U.S.", newsSource: "NBC News", newsDate: "January 2, 2022", newsLink: "https://www.nbcnews.com/news/us-news/wastewater-samples-reveal-record-levels-covid-19-us-rcna10451"}),
e(NewsList, {newsType: "Media News", newsTitle: "A wounded PM and ailing economy force England to ‘go Swedish’ on Covid", newsSource: "Guardian", newsDate: "January 2, 2022", newsLink: "https://www.theguardian.com/business/2022/jan/02/a-wounded-pm-and-ailing-economy-forces-england-to-go-swedish-on-covid"}),
e(NewsList, {newsType: "Media News", newsTitle: "French politicians condemn death threats over vaccine pass", newsSource: "Guardian", newsDate: "January 3, 2022", newsLink: "https://www.theguardian.com/world/2022/jan/03/french-politicians-condemn-death-threats-over-vaccine-pass"}),
e(NewsList, {newsType: "Media News", newsTitle: "A WHO official weighs in on Covid, vaccines, and mistakes that were made", newsSource: "STAT News", newsDate: "January 3, 2022", newsLink: "https://www.statnews.com/2022/01/03/a-who-official-weighs-in-on-covid-vaccines-and-mistakes-that-were-made/"}),
e(NewsList, {newsType: "Media News", newsTitle: "Ontario shuts schools, indoor dining and gyms", newsSource: "AP News", newsDate: "January 3, 2022", newsLink: "https://apnews.com/article/coronavirus-pandemic-health-canada-ontario-958c116479a85cdc0692dae556c582b6"}),
e(NewsList, {newsType: "Media News", newsTitle: "NHS trusts declare critical incidents amid Covid staff crisis", newsSource: "Guardian", newsDate: "January 3, 2022", newsLink: "https://www.theguardian.com/society/2022/jan/03/several-nhs-trusts-declare-critical-incidents-amid-covid-staff-crisis"}),
e(NewsList, {newsType: "Media News", newsTitle: "NHS faces significant pressure in coming weeks, says Boris Johnson", newsSource: "Guardian", newsDate: "January 3, 2022", newsLink: "https://www.theguardian.com/world/2022/jan/03/nhs-faces-significant-pressure-in-coming-weeks-says-boris-johnson"}), 
e(NewsList, {newsType: "Media News", newsTitle: "The world has avoided a ‘twindemic,’ but as flu cases rise alongside covid, experts fear that could change", newsSource: "Washington Post", newsDate: "January 4, 2022", newsLink: "https://www.washingtonpost.com/world/2022/01/04/twindemic-coronavirus-flu-outbreak-2021-israel-brazil-australia/"}),
e(NewsList, {newsType: "Media News", newsTitle: "These are the numbers health officials are watching at this point in the pandemic", newsSource: "NPR", newsDate: "January 4, 2022", newsLink: "https://www.npr.org/2022/01/04/1070008296/covid-omicron-cases-numbers-deaths-hospitalizations"}),
e(NewsList, {newsType: "Media News", newsTitle: "Walmart, Kroger Raise Prices of Covid-19 Test Kits", newsSource: "Wall Street Journal", newsDate: "January 4, 2022", newsLink: "https://www.wsj.com/articles/walmart-kroger-raise-prices-of-covid-19-test-kits-11641320476"}),
e(NewsList, {newsType: "Media News", newsTitle: "The coronavirus may cause fat cells to miscommunicate, leading to diabetes", newsSource: "Science News", newsDate: "January 4, 2022", newsLink: "https://www.sciencenews.org/article/coronavirus-covid-diabetes-fat-cells-blood-sugar"}), 
e(NewsList, {newsType: "Media News", newsTitle: "Scientists call for Covid reinfections in UK to be included in case figures", newsSource: "Guardian", newsDate: "January 4, 2022", newsLink: "https://www.theguardian.com/world/2022/jan/04/scientists-call-covid-reinfections-uk-be-included-case-figures-omicron"}),
e(NewsList, {newsType: "Media News", newsTitle: "Omicron cases are exploding. Scientists still don’t know how bad the wave will be", newsSource: "Science", newsDate: "January 4, 2022", newsLink: "https://www.science.org/content/article/omicron-cases-are-exploding-scientists-still-don-t-know-how-bad-wave-will-be"}),
e(NewsList, {newsType: "Media News", newsTitle: "Hong Kong Bans Flights From U.S., U.K., Six Other Nations", newsSource: "Bloomberg", newsDate: "January 4, 2022", newsLink: "https://www.bloomberg.com/news/articles/2022-01-05/hong-kong-bans-five-more-flight-routes-as-omicron-besieges-city"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Pfizer to Provide U.S. Government with an Additional 10 Million Treatment Courses of its Oral Therapy to Help Combat COVID-19", newsSource: "Pfizer", newsDate: "January 4, 2022", newsLink: "https://www.pfizer.com/news/press-release/press-release-detail/pfizer-provide-us-government-additional-10-million"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Lottery-Based Incentives and COVID-19 Vaccination Rates in the US", newsSource: "Jama Network", newsDate: "January 4, 2022", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamainternmed.2021.7052"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Association of Birth During the COVID-19 Pandemic With Neurodevelopmental Status at 6 Months in Infants With and Without In Utero Exposure to Maternal SARS-CoV-2 Infection", newsSource: "Jama Network", newsDate: "January 4, 2022", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamapediatrics.2021.5563"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Feasibility of SARS-CoV-2 Surveillance Testing Among Children and Childcare Workers at German Day Care Centers", newsSource: "Jama Network", newsDate: "January 4, 2022", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamanetworkopen.2021.42057"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "The Shadow Pandemic: A Qualitative Exploration of the Impacts of COVID-19 on Service Providers and Women Survivors of Intimate Partner Violence and Brain Injury", newsSource: "Journal of Head Trauma Rehabilitation", newsDate: "January - February 2022", newsLink: "https://journals.lww.com/headtraumarehab/Fulltext/2022/01000/The_Shadow_Pandemic__A_Qualitative_Exploration_of.7.aspx"}),               
e(NewsList, {newsType: "Media News", newsTitle: "Cuba’s vaccine success story sails past mark set by rich world’s Covid efforts", newsSource: "Guardian", newsDate: "January 5, 2022", newsLink: "https://www.theguardian.com/world/2022/jan/05/cuba-coronavirus-covid-vaccines-success-story"}),
e(NewsList, {newsType: "Media News", newsTitle: "Desperation as China’s locked down cities pay price of zero-Covid strategy", newsSource: "Guardian", newsDate: "January 5, 2022", newsLink: "https://www.theguardian.com/world/2022/jan/05/desperation-as-chinas-locked-down-cities-pay-price-of-zero-covid-strategy"}), 
e(NewsList, {newsType: "Media News", newsTitle: "COVID case counts may be losing importance amid omicron", newsSource: "AP News", newsDate: "January 5, 2022", newsLink: "https://apnews.com/article/coronavirus-pandemic-science-health-anthony-fauci-9444d63b650b98e235ed2595b0ebe844"}),
e(NewsList, {newsType: "Media News", newsTitle: "Lawmakers begin early talks about another round of coronavirus relief targeting businesses", newsSource: "Washington Post", newsDate: "January 5, 2022", newsLink: "https://www.washingtonpost.com/us-policy/2022/01/05/congress-omicron-coronavirus-aid/"}),
e(NewsList, {newsType: "Media News", newsTitle: "CDC urges ‘up to date’ COVID shots but won’t change definition of ‘fully vaccinated’", newsSource: "PBS", newsDate: "January 5, 2022", newsLink: "https://www.pbs.org/newshour/health/cdc-urges-up-to-date-covid-shots-but-wont-change-definition-of-fully-vaccinated"}),
e(NewsList, {newsType: "Media News", newsTitle: "Inside a Covid-19 School Closing: A Pennsylvania Superintendent Agonizes Over Going Remote", newsSource: "Wall Street Journal", newsDate: "January 5, 2022", newsLink: "https://www.wsj.com/amp/articles/inside-a-covid-19-school-closing-a-pennsylvania-superintendent-agonizes-over-going-remote-11641416872"}),
e(NewsList, {newsType: "Media News", newsTitle: "Ministers must act now on NHS staffing crisis, health chiefs warn", newsSource: "Guardian", newsDate: "January 5, 2022", newsLink: "https://www.theguardian.com/world/2022/jan/05/ministers-must-act-now-on-nhs-staffing-crisis-health-chiefs-warn"}),
e(NewsList, {newsType: "Media News", newsTitle: "Every U.S. cruise with passengers has coronavirus cases on board", newsSource: "Washington Post", newsDate: "January 5, 2022", newsLink: "https://www.washingtonpost.com/travel/2022/01/05/every-cruise-ship-covid-cdc/"}),
e(NewsList, {newsType: "Media News", newsTitle: "Study raises doubts about rapid Covid tests’ reliability in early days after infection", newsSource: "STAT News", newsDate: "January 5, 2022", newsLink: "https://www.statnews.com/2022/01/05/study-raises-doubts-about-rapid-covid-tests-reliability-in-early-days-after-infection/"}),
e(NewsList, {newsType: "Media News", newsTitle: "‘The next variant is just around the corner’: Experts warn the world’s at risk until all are vaccinated", newsSource: "CNBC", newsDate: "January 6, 2022", newsLink: "https://www.cnbc.com/2022/01/06/new-covid-variants-are-a-danger-until-the-whole-world-is-vaccinated.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "Supreme Court is set to review Biden’s vaccine rules for businesses, health-care workers. Here’s what to know.", newsSource: "Washington Post", newsDate: "January 6, 2022", newsLink: "https://www.washingtonpost.com/politics/courts_law/supreme-court-biden-vaccine-mandate/2022/01/05/ad579632-6e44-11ec-aaa8-35d1865a6977_story.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "Japan Criticizes U.S. Response After Omicron Spreads Near American Bases", newsSource: "Wall Street Journal", newsDate: "January 6, 2022", newsLink: "https://www.wsj.com/articles/japan-criticizes-u-s-response-after-omicron-spreads-near-american-bases-11641466830"}),
e(NewsList, {newsType: "Media News", newsTitle: "French MPs pass controversial Covid vaccine bill with large majority", newsSource: "Guardian", newsDate: "January 6, 2022", newsLink: "https://www.theguardian.com/world/2022/jan/06/french-mps-pass-controversial-covid-vaccine-bill-with-large-majority"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Omicron's feeble attack on the lungs could make it less dangerous", newsSource: "Nature", newsDate: "January 6, 2022", newsLink: "https://doi.org/10.1038/d41586-022-00007-8"}),               
         ); 
 }
}

document.addEventListener("DOMContentLoaded", function(event) {
  ReactDOM.render(
  e(January2022NewsApp), 
  //e(Welcome, {name: "Person"}), e(NewsList, {newsType: "Non Media News", newsTitle: "", newsSource: "", newsDate: "January , 2022", newsLink: ""}),
  document.querySelector('#article-main-jan2022')
  );
});
