'use strict';

class November2021NewsApp extends React.Component {
 render() {
      return e("div", null,
e(NewsList, {newsType: "Non Media News", newsTitle: "COVID-19 mortality and the overweight: Cross-Country Evidence", newsSource: "Science Direct", newsDate: "November 2021", newsLink: "https://www.sciencedirect.com/science/article/pii/S266653522100104X"}),
e(NewsList, {newsType: "Media News", newsTitle: "Federal contractors get broad flexibility to enforce Covid vaccine rules for millions of workers", newsSource: "CNBC", newsDate: "November 1, 2021", newsLink: "https://www.cnbc.com/2021/11/01/federal-contractors-will-have-broad-flexibility-to-enforce-covid-vaccine-rules.html"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Safety and efficacy of fluvoxamine in COVID-19 ICU patients: an open label, prospective cohort trial with matched controls", newsSource: "British Journal of Clinical Pharmacology", newsDate: "November 1, 2021", newsLink: "https://doi.org/10.1111/bcp.15126"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "How conspiracists exploited COVID-19 science", newsSource: "Nature", newsDate: "November 1, 2021", newsLink: "https://doi.org/10.1038/s41562-021-01217-2"}), 
e(NewsList, {newsType: "Media News", newsTitle: "Facebook failing to protect users from Covid misinformation, says monitor", newsSource: "Guardian", newsDate: "November 1, 2021", newsLink: "https://www.theguardian.com/technology/2021/nov/02/facebook-failing-to-protect-users-from-covid-misinformation-says-monitor"}),
e(NewsList, {newsType: "Media News", newsTitle: "More than 2,000 New York City firefighters out sick as vaccine mandate takes effect", newsSource: "CBS News", newsDate: "November 1, 2021", newsLink: "https://www.cbsnews.com/news/covid-vaccine-mandate-firefighters-fdny-call-sick-new-york/"}), 
e(NewsList, {newsType: "Non Media News", newsTitle: "Durability of Antibody Levels After Vaccination With mRNA SARS-CoV-2 Vaccine in Individuals With or Without Prior Infection", newsSource: "Jama Network", newsDate: "November 1, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jama.2021.19996"}),
e(NewsList, {newsType: "Media News", newsTitle: "US prisons face staff shortages as officers quit amid COVID", newsSource: "AP News", newsDate: "November 1, 2021", newsLink: "https://apnews.com/article/coronavirus-united-states-prisons-staff-shortages-health-dba13f1c6368392be2bc5e7375170a78"}),
e(NewsList, {newsType: "Media News", newsTitle: "Loneliness vs. solitude: Study finds early COVID isolation was positive for many", newsSource: "Miami Herald", newsDate: "November 2, 2021", newsLink: "https://www.miamiherald.com/news/nation-world/national/article255455446.html"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "Analysis of the Effectiveness of the Ad26.COV2.S Adenoviral Vector Vaccine for Preventing COVID-19", newsSource: "Jama Network", newsDate: "November 2, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamanetworkopen.2021.32540"}), 
e(NewsList, {newsType: "Media News", newsTitle: "Half of Beijing’s flights are canceled as China’s capital city tightens Covid restrictions", newsSource: "CNBC", newsDate: "November 2, 2021", newsLink: "https://www.cnbc.com/2021/11/02/beijing-flights-cancelled-as-city-tightens-covid-travel-restrictions.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "China’s Latest Delta Outbreak its Most Widespread Since Wuhan", newsSource: "Bloomberg", newsDate: "November 2, 2021", newsLink: "https://www.bloomberg.com/news/articles/2021-11-03/china-s-fast-spreading-delta-outbreak-now-its-widest-since-wuhan"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "CDC Recommends Pediatric COVID-19 Vaccine for Children 5 to 11 Years", newsSource: "CDC", newsDate: "November 2, 2021", newsLink: "https://www.cdc.gov/media/releases/2021/s1102-PediatricCOVID-19Vaccine.html"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "A broadly cross-reactive antibody neutralizes and protects against sarbecovirus challenge in mice", newsSource: "Science", newsDate: "November 2, 2021", newsLink: "https://doi.org/10.1126/scitranslmed.abj7125"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "An oral SARS-CoV-2 Mpro inhibitor clinical candidate for the treatment of COVID-19", newsSource: "Science", newsDate: "November 2, 2021", newsLink: "https://doi.org/10.1126/science.abl4784"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Visualizing in deceased COVID-19 patients how SARS-CoV-2 attacks the respiratory and olfactory mucosae but spares the olfactory bulb", newsSource: "Cell", newsDate: "November 2, 2021", newsLink: "https://doi.org/10.1016/j.cell.2021.10.027"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Postmortem Antigen-Detecting Rapid Diagnostic Tests to Predict Infectivity of SARS-CoV-2–Associated Deaths", newsSource: "CDC", newsDate: "November 2, 2021", newsLink: "https://doi.org/10.3201/eid2801.211749"}),               
e(NewsList, {newsType: "Media News", newsTitle: "NYC police unions warned vaccine mandates would pull 10,000 officers off streets. So far, the number is 34.", newsSource: "Washington Post", newsDate: "November 2, 2021", newsLink: "https://www.washingtonpost.com/nation/2021/11/02/nypd-unpaid-leave-vaccine-mandate/"}),               
e(NewsList, {newsType: "Media News", newsTitle: "Chinese stock up on food as temperatures fall and Covid spreads", newsSource: "NBC News", newsDate: "November 3, 2021", newsLink: "https://www.nbcnews.com/news/world/chinese-stock-food-temperatures-fall-covid-spreads-rcna4415"}),
e(NewsList, {newsType: "Media News", newsTitle: "Flu deaths drop dramatically in Australia due to Covid measures with one type possibly eliminated", newsSource: "Guardian", newsDate: "November 3, 2021", newsLink: "https://www.theguardian.com/society/2021/nov/04/flu-deaths-drop-dramatically-in-australia-due-to-covid-measures-with-one-type-possibly-eliminated"}),
e(NewsList, {newsType: "Media News", newsTitle: "Covid: Germany enveloped in ‘massive’ pandemic of the unvaccinated", newsSource: "Guardian", newsDate: "November 3, 2021", newsLink: "https://www.theguardian.com/world/2021/nov/03/germany-enveloped-in-massive-pandemic-of-the-unvaccinated"}),
e(NewsList, {newsType: "Media News", newsTitle: "Fears for Australia’s pregnant women as vaccination rates lag far behind general population", newsSource: "Guardian", newsDate: "November 3, 2021", newsLink: "https://www.theguardian.com/australia-news/2021/nov/04/fears-for-pregnant-women-as-vaccination-rates-lag-far-behind-general-population"}),
e(NewsList, {newsType: "Media News", newsTitle: "Vaccine mandates are surging in job listings", newsSource: "CNBC", newsDate: "November 3, 2021", newsLink: "https://www.cnbc.com/2021/11/03/vaccine-mandates-are-surging-in-job-listings.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "CDC director says kids with a prior Covid infection should ‘absolutely’ still get vaccinated", newsSource: "CNBC", newsDate: "November 3, 2021", newsLink: "https://www.cnbc.com/2021/11/03/cdc-director-urges-kids-whove-had-a-prior-covid-infection-to-still-get-vaccinated.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "Eager parents rush to get kids pediatric COVID-19 vaccines", newsSource: "AP News", newsDate: "November 3, 2021", newsLink: "https://apnews.com/article/coronavirus-pandemic-lifestyle-business-social-media-coronavirus-vaccine-d3b00691e9fcd62ccb9f7f00f66749bd"}), 
e(NewsList, {newsType: "Media News", newsTitle: "Covid has caused 28m years of life to be lost, study finds", newsSource: "Guardian", newsDate: "November 3, 2021", newsLink: "https://www.theguardian.com/world/2021/nov/03/covid-has-caused-28m-years-of-life-to-be-lost-study-finds"}),
e(NewsList, {newsType: "Media News", newsTitle: "Covaxin, India's homegrown Covid vaccine, is authorized by World Health Organization", newsSource: "NBC News", newsDate: "November 3, 2021", newsLink: "https://www.nbcnews.com/news/world/covaxin-india-s-homegrown-covid-vaccine-authorized-world-health-organization-n1283169"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Neutralization of the SARS-CoV-2 Mu Variant by Convalescent and Vaccine Serum", newsSource: "New England Journal of Medicine", newsDate: "November 3, 2021", newsLink: "https://www.nejm.org/doi/full/10.1056/NEJMc2114706"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Phase 3 Trial of mRNA-1273 during the Delta-Variant Surge", newsSource: "New England Journal of Medicine", newsDate: "November 3, 2021", newsLink: "https://www.nejm.org/doi/full/10.1056/NEJMc2115597"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Estimated cost-based generic prices for molnupiravir for the treatment of COVID-19 infection", newsSource: "Harvard University Department of Global Health and Population", newsDate: "November 3, 2021", newsLink: "https://scholar.harvard.edu/files/melissabarber/files/estimated_cost-based_generic_prices_for_molnupiravir_for_the_treatment_of_covid-19_infection.pdf"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Urban particulate matter impairs airway-surface-liquid-mediated coronavirus inactivation", newsSource: "Oxford Academics", newsDate: "November 3, 2021", newsLink: "https://doi.org/10.1093/infdis/jiab545"}),
e(NewsList, {newsType: "Media News", newsTitle: "Puerto Rico to make COVID-19 vaccine mandatory for school", newsSource: "Washington Post", newsDate: "November 3, 2021", newsLink: "https://www.washingtonpost.com/world/puerto-rico-to-make-covid-19-vaccine-mandatory-for-school/2021/11/03/c1ea8274-3cf0-11ec-bd6f-da376f47304e_story.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "Life expectancy fell sharply in the U.S. last year among high-income countries", newsSource: "NBC News", newsDate: "November 3, 2021", newsLink: "https://www.nbcnews.com/science/science-news/life-expectancy-fell-sharply-us-last-year-high-income-countries-rcna4450"}),
e(NewsList, {newsType: "Media News", newsTitle: "Covid vaccines for children are coming. So is misinformation.", newsSource: "NBC News", newsDate: "November 3, 2021", newsLink: "https://www.nbcnews.com/tech/tech-news/vaccine-misinformation-poised-spike-covid-shots-kids-roll-rcna4360"}),
e(NewsList, {newsType: "Media News", newsTitle: "WHO says Europe is back at the epicenter of Covid pandemic, despite vaccines", newsSource: "NBC News", newsDate: "November 4, 2021", newsLink: "https://www.nbcnews.com/health/health-news/who-says-europe-back-epicenter-covid-pandemic-despite-vaccines-n1283263"}),
e(NewsList, {newsType: "Media News", newsTitle: "Ventilate your home to stop Covid spread, UK government says", newsSource: "Guardian", newsDate: "November 4, 2021", newsLink: "https://www.theguardian.com/world/2021/nov/05/ventilate-home-stop-covid-spread-government-uk"}),
e(NewsList, {newsType: "Media News", newsTitle: "Federal Government Cuts Ties With Troubled Vaccine Maker", newsSource: "NY Times", newsDate: "November 4, 2021", newsLink: "https://www.nytimes.com/2021/11/04/us/emergent-biosolutions-covid-vaccine.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "What young Americans think about vaccines and mandates", newsSource: "PBS", newsDate: "November 4, 2021", newsLink: "https://www.pbs.org/newshour/health/young-americans-are-less-likely-than-others-to-be-vaccinated-most-still-say-they-see-it-as-a-social-responsibility"}),
e(NewsList, {newsType: "Media News", newsTitle: "Gene common in south Asian people doubles risk of Covid death, study finds", newsSource: "Guardian", newsDate: "November 4, 2021", newsLink: "https://www.theguardian.com/science/2021/nov/04/gene-common-in-south-asian-people-doubles-risk-of-covid-death-study-finds"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Association Between mRNA Vaccination and COVID-19 Hospitalization and Disease Severity", newsSource: "Jama Network", newsDate: "November 4, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jama.2021.19499"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Imaging intact human organs with local resolution of cellular structures using hierarchical phase-contrast tomography", newsSource: "Nature", newsDate: "November 4, 2021", newsLink: "https://doi.org/10.1038/s41592-021-01317-x"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Identification of LZTFL1 as a candidate effector gene at a COVID-19 risk locus", newsSource: "Nature", newsDate: "November 4, 2021", newsLink: "https://doi.org/10.1038/s41588-021-00955-3"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Infection with SARS-CoV-2 variant B.1.1.7 detected in a group of dogs and cats with suspected myocarditis", newsSource: "BVA Journals", newsDate: "November 4, 2021", newsLink: "https://doi.org/10.1002/vetr.944"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "SARS-CoV-2 vaccine protection and deaths among US veterans during 2021", newsSource: "Science", newsDate: "November 4, 2021", newsLink: "https://doi.org/10.1126/science.abm0620"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Rapid assessment of SARS-CoV-2 evolved variants using virus-like particles", newsSource: "Science", newsDate: "November 4, 2021", newsLink: "https://doi.org/10.1126/science.abl6184"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "First oral antiviral for COVID-19, Lagevrio (molnupiravir), approved by MHRA", newsSource: "Government UK", newsDate: "November 4, 2021", newsLink: "https://www.gov.uk/government/news/first-oral-antiviral-for-covid-19-lagevrio-molnupiravir-approved-by-mhra"}),               
e(NewsList, {newsType: "Media News", newsTitle: "US mandates vaccines or tests for big companies by Jan. 4", newsSource: "AP News", newsDate: "November 4, 2021", newsLink: "https://apnews.com/article/covid-employer-mandates-us-29c2262c336bcfc38da2d14b251daf51"}),                
e(NewsList, {newsType: "Media News", newsTitle: "Businesses have until after the holidays to implement Biden Covid vaccine mandate", newsSource: "CNBC", newsDate: "November 4, 2021", newsLink: "https://www.cnbc.com/2021/11/04/biden-vaccine-mandate-businesses-have-until-after-christmas-to-comply.html"}),               
              ); 
 }
}

document.addEventListener("DOMContentLoaded", function(event) {
  ReactDOM.render(
  e(November2021NewsApp), 
  //e(Welcome, {name: "Person"}), e(NewsList, {newsType: "Non Media News", newsTitle: "", newsSource: "", newsDate: "November , 2021", newsLink: ""}),
  document.querySelector('#article-main-november2021')
  );
});
