'use strict';

const e = React.createElement;

class NewsList extends React.Component {
  render() {
    return e("div", {class: "article-container"},
    e("div", {class: "news-box news-box-a"},
    e("i", {class: "fas fa-exclamation-circle fa-2x"}, this.props.newsType),
    e("h3", null, this.props.newsTitle), 
    e("p", {class: "price"}, "Source: ", this.props.newsSource, ", Published on ", this.props.newsDate), 
    e("a", {target: "_blank", href: `${this.props.newsLink}`, class: "btn"}, "Link to Article")),  
    e("div", {class: "news-box news-box-b"}, 
    e("img", {src: "img/coronavirus-19-mobile.jpg",alt: "COVID-19 News Image"
    }))
    );
  }
}

class October2021NewsApp extends React.Component {
 render() {
      return e("div", null,
e(NewsList, {newsType: "Non Media News", newsTitle: "The BNT162b2 vaccine effectiveness against new COVID-19 cases and complications of breakthrough cases: A nation-wide retrospective longitudinal multiple cohort analysis using individualised data", newsSource: "Science Direct", newsDate: "October 2021", newsLink: "https://www.sciencedirect.com/science/article/pii/S2352396421003674"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "The combined treatment of Molnupiravir and Favipiravir results in a potentiation of antiviral efficacy in a SARS-CoV-2 hamster infection model", newsSource: "Science Direct", newsDate: "October 2021", newsLink: "https://www.sciencedirect.com/science/article/pii/S2352396421003881"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "Anxiety, depression, insomnia, and trauma-related symptoms following COVID-19 infection at long-term follow-up", newsSource: "Science Direct", newsDate: "October 2021", newsLink: "https://www.sciencedirect.com/science/article/pii/S2666354621001186"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Human exposure to respiratory aerosols in a ventilated room: Effects of ventilation condition, emission mode, and social distancing", newsSource: "Science Direct", newsDate: "October 2021", newsLink: "https://www.sciencedirect.com/science/article/abs/pii/S2210670721003735"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "The durability of immunity against reinfection by SARS-CoV-2: a comparative evolutionary study", newsSource: "Lancet", newsDate: "October 1, 2021", newsLink: "https://doi.org/10.1016/S2666-5247(21)00219-6"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "COVID-19 and global equity for health: The good, the bad, and the wicked", newsSource: "PLOS", newsDate: "October 1, 2021", newsLink: "https://doi.org/10.1371/journal.pmed.1003797"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Merck and Ridgeback’s Investigational Oral Antiviral Molnupiravir Reduced the Risk of Hospitalization or Death by Approximately 50 Percent Compared to Placebo for Patients with Mild or Moderate COVID-19 in Positive Interim Analysis of Phase 3 Study", newsSource: "Merck and Ridgebacks", newsDate: "October 1, 2021", newsLink: "https://www.merck.com/news/merck-and-ridgebacks-investigational-oral-antiviral-molnupiravir-reduced-the-risk-of-hospitalization-or-death-by-approximately-50-percent-compared-to-placebo-for-patients-with-mild-or-moderat/"}),               
e(NewsList, {newsType: "Media News", newsTitle: "Why it’s not possible for the Covid vaccines to contain a magnetic tracking chip that connects to 5G", newsSource: "CNBC", newsDate: "October 1, 2021", newsLink: "https://www.cnbc.com/2021/10/01/why-the-covid-vaccines-dont-contain-a-magnetic-5g-tracking-chip.html"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "FDA to Hold Advisory Committee Meetings to Discuss Emergency Use Authorization for Booster Doses and COVID-19 Vaccines for Younger Children", newsSource: "U.S. Food and Drug Administration", newsDate: "October 1, 2021", newsLink: "https://www.fda.gov/news-events/press-announcements/fda-hold-advisory-committee-meetings-discuss-emergency-use-authorization-booster-doses-and-covid-19"}),
e(NewsList, {newsType: "Media News", newsTitle: "Justice Department argues Texas ban on school mask mandates violates disabled students’ rights", newsSource: "Texas Tribune", newsDate: "October 1, 2021", newsLink: "https://www.texastribune.org/2021/10/01/texas-schools-mask-mandates-justice-department/"}),
e(NewsList, {newsType: "Media News", newsTitle: "Vaccinated people are less likely to spread Covid, new research finds", newsSource: "NBC News", newsDate: "October 1, 2021", newsLink: "https://www.nbcnews.com/health/health-news/vaccinated-people-are-less-likely-spread-covid-new-research-finds-n1280583/"}),
e(NewsList, {newsType: "Media News", newsTitle: "Many are searching for vaccine mandate loopholes. These are the people trying to stop them.", newsSource: "Washington Post", newsDate: "October 2, 2021", newsLink: "https://www.washingtonpost.com/lifestyle/2021/10/02/vaccine-mandate-office-loophole/"}),
e(NewsList, {newsType: "Media News", newsTitle: "Unvaccinated care workers should get another job, says Javid", newsSource: "Guardian", newsDate: "October 2, 2021", newsLink: "https://www.theguardian.com/politics/2021/oct/02/covid-unvaccinated-care-workers-should-get-another-job-says-javid"}),               
e(NewsList, {newsType: "Media News", newsTitle: "Alabama to use Covid rescue funds to build prisons", newsSource: "NBC News", newsDate: "October 2, 2021", newsLink: "https://www.nbcnews.com/news/us-news/alabama-use-covid-rescue-funds-build-prisons-n1280624"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Characterization of SARS-CoV-2 and common cold coronavirus-specific T cell responses in MIS-C and Kawasaki disease children", newsSource: "Wiley Online Library", newsDate: "October 2, 2021", newsLink: "https://doi.org/10.1002/eji.202149556"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "Effect of Convalescent Plasma on Organ Support–Free Days in Critically Ill Patients With COVID-19", newsSource: "Jama Network", newsDate: "October 4, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jama.2021.18178"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Effectiveness of mRNA BNT162b2 COVID-19 vaccine up to 6 months in a large integrated health system in the USA: a retrospective cohort study", newsSource: "Lancet", newsDate: "October 4, 2021", newsLink: "https://doi.org/10.1016/S0140-6736(21)02183-8"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Acute Myocarditis Following COVID-19 mRNA Vaccination in Adults Aged 18 Years or Older", newsSource: "Jama Network", newsDate: "October 4, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamainternmed.2021.5511"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Comirnaty and Spikevax: EMA recommendations on extra doses and boosters", newsSource: "European Medicines Agency", newsDate: "October 4, 2021", newsLink: "https://www.ema.europa.eu/en/news/comirnaty-spikevax-ema-recommendations-extra-doses-boosters"}),
e(NewsList, {newsType: "Media News", newsTitle: "Pandemic, Worker Shortage Pose Major Challenges to Long-Term Care Industry", newsSource: "Morning Consult", newsDate: "October 4, 2021", newsLink: "https://morningconsult.com/2021/10/04/health-care-workers-series-part-2-long-term-care/"}),
e(NewsList, {newsType: "Media News", newsTitle: "Anti-vaxxers trying to disrupt Australian rollout by making fake vaccine bookings", newsSource: "Guardian", newsDate: "October 4, 2021", newsLink: "https://www.theguardian.com/australia-news/2021/oct/05/anti-vaxxers-trying-to-disrupt-australian-rollout-by-making-fake-vaccine-bookings"}),
e(NewsList, {newsType: "Media News", newsTitle: "Fauci: Remarks on Christmas gatherings were 'misinterpreted'", newsSource: "Hill", newsDate: "October 4, 2021", newsLink: "https://thehill.com/policy/healthcare/575174-fauci-remarks-on-christmas-gatherings-were-misinterpreted"}),
e(NewsList, {newsType: "Media News", newsTitle: "Get a fan and get vaccinated, the CDC says in its safety tips for the holidays", newsSource: "NPR", newsDate: "October 4, 2021", newsLink: "https://www.npr.org/sections/coronavirus-live-updates/2021/10/04/1043020857/cdc-tips-for-celebrating-the-holidays-safely-covid"}),
e(NewsList, {newsType: "Media News", newsTitle: "Dr. Scott Gottlieb says ‘nothing is going to stop’ families from gathering for holidays", newsSource: "CNBC", newsDate: "October 4, 2021", newsLink: "https://www.cnbc.com/2021/10/04/covid-dr-scott-gottlieb-expects-families-will-gather-for-holidays.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "WHO says unvaccinated people are ‘dying unnecessarily’ from Covid as hospitals fill", newsSource: "CNBC", newsDate: "October 5, 2021", newsLink: "https://www.cnbc.com/2021/10/05/who-says-unvaccinated-people-are-dying-unnecessarily-from-covid-.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "Frustration, anger and deaths won’t convince the unvaccinated", newsSource: "Washington Post", newsDate: "October 5, 2021", newsLink: "https://www.washingtonpost.com/outlook/2021/10/05/frustration-anger-deaths-wont-convince-unvaccinated/"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Increased risk for COVID-19 breakthrough infection in fully vaccinated patients with substance use disorders in the United States between December 2020 and August 2021", newsSource: "Wiley Online Library", newsDate: "October 5, 2021", newsLink: "https://doi.org/10.1002/wps.20921"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Johnson & Johnson Announces Submission of Emergency Use Authorization Amendment to the U.S. FDA to Support Booster of its Single-Shot COVID-19 Vaccine", newsSource: "Johnson and Johnson", newsDate: "October 5, 2021", newsLink: "https://www.jnj.com/johnson-johnson-announces-submission-of-emergency-use-authorization-amendment-to-the-u-s-fda-to-support-booster-of-its-single-shot-covid-19-vaccine"}),
e(NewsList, {newsType: "Media News", newsTitle: "Australia won’t welcome foreign tourists until at least 2022", newsSource: "AP News", newsDate: "October 5, 2021", newsLink: "https://apnews.com/article/coronavirus-pandemic-lifestyle-business-scott-morrison-travel-0e0dea481cefe0952e19f6315b6955ee"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Moderna COVID-19 vaccine generates long-lasting immune memory", newsSource: "National Institutes of Health", newsDate: "October 5, 2021", newsLink: "https://www.nih.gov/news-events/nih-research-matters/moderna-covid-19-vaccine-generates-long-lasting-immune-memory"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "An affinity-enhanced, broadly neutralizing heavy chain-only antibody protects against SARS-CoV-2 infection in animal models", newsSource: "Science", newsDate: "October 5, 2021", newsLink: "https://doi.org/10.1126/scitranslmed.abi7826"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "COVID vaccines cut the risk of transmitting Delta — but not for long", newsSource: "Nature", newsDate: "October 5, 2021", newsLink: "https://doi.org/10.1038/d41586-021-02689-y"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Low anti-SARS-CoV-2 S antibody levels predict increased mortality and dissemination of viral components in the blood of critical COVID-19 patients", newsSource: "Wiley Online Library", newsDate: "October 5, 2021", newsLink: "https://doi.org/10.1111/joim.13386"}),               
e(NewsList, {newsType: "Media News", newsTitle: "I took the Covid vaccine while pregnant – let’s not pretend it’s an easy decision", newsSource: "Guardian", newsDate: "October 5, 2021", newsLink: "https://www.theguardian.com/lifeandstyle/2021/oct/05/pregnant-women-not-taking-vaccine"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "High-dimensional profiling reveals phenotypic heterogeneity and disease-specific alterations of granulocytes in COVID-19", newsSource: "PNAS", newsDate: "October 5, 2021", newsLink: "https://doi.org/10.1073/pnas.2109123118"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Coverage and Estimated Effectiveness of mRNA COVID-19 Vaccines Among US Veterans", newsSource: "Jama Network", newsDate: "October 6, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamanetworkopen.2021.28391"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Real-world data show that filters clean COVID-causing virus from air", newsSource: "Nature", newsDate: "October 6, 2021", newsLink: "https://doi.org/10.1038/d41586-021-02669-2"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Myocarditis after Covid-19 Vaccination in a Large Health Care Organization", newsSource: "New England Journal of Medicine", newsDate: "October 6, 2021", newsLink: "https://www.nejm.org/doi/full/10.1056/NEJMoa2110737"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "No one is safe until we are all safe", newsSource: "Science", newsDate: "October 6, 2021", newsLink: "https://doi.org/10.1126/scitranslmed.abl9900"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Waning Immune Humoral Response to BNT162b2 Covid-19 Vaccine over 6 Months", newsSource: "New England Journal of Medicine", newsDate: "October 6, 2021", newsLink: "https://www.nejm.org/doi/full/10.1056/NEJMoa2114583"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Myocarditis after BNT162b2 mRNA Vaccine against Covid-19 in Israel", newsSource: "New England Journal of Medicine", newsDate: "October 6, 2021", newsLink: "https://www.nejm.org/doi/full/10.1056/NEJMoa2109730"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Waning of BNT162b2 Vaccine Protection against SARS-CoV-2 Infection in Qatar", newsSource: "New England Journal of Medicine", newsDate: "October 6, 2021", newsLink: "https://www.nejm.org/doi/full/10.1056/NEJMoa2114114"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "The legacy of maternal SARS-CoV-2 infection on the immunology of the neonate", newsSource: "Nature", newsDate: "October 6, 2021", newsLink: "https://doi.org/10.1038/s41590-021-01049-2"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Anti-SARS-CoV-2 receptor binding domain antibody evolution after mRNA vaccination", newsSource: "Nature", newsDate: "October 7, 2021", newsLink: "https://doi.org/10.1038/s41586-021-04060-7"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Why easing COVID restrictions could prompt a fierce flu rebound", newsSource: "Nature", newsDate: "October 7, 2021", newsLink: "https://doi.org/10.1038/d41586-021-02558-8"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "A genetic link between risk for Alzheimer's disease and severe COVID-19 outcomes via the OAS1 gene", newsSource: "Oxford Academics", newsDate: "October 7, 2021", newsLink: "https://doi.org/10.1093/brain/awab337"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Association of Receipt of the Ad26.COV2.S COVID-19 Vaccine With Presumptive Guillain-Barré Syndrome, February-July 2021", newsSource: "Jama Network", newsDate: "October 7, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jama.2021.16496"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Monetary incentives increase COVID-19 vaccinations", newsSource: "Science", newsDate: "October 7, 2021", newsLink: "https://doi.org/10.1126/science.abm0475"}),
e(NewsList, {newsType: "Media News", newsTitle: "UN Secretary calls unequal distribution of Covid vaccines across globe immoral and stupid", newsSource: "CNBC", newsDate: "October 7, 2021", newsLink: "https://www.cnbc.com/2021/10/07/un-secretary-calls-unequal-distribution-of-covid-vaccines-across-globe-immoral-and-stupid.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "People who want organ transplants must get the COVID-19 vaccine, a hospital says", newsSource: "NPR", newsDate: "October 7, 2021", newsLink: "https://www.npr.org/sections/coronavirus-live-updates/2021/10/07/1044034382/colorado-hospital-organ-transplant-covid-vaccine"}),
e(NewsList, {newsType: "Media News", newsTitle: "Fired for refusing a Covid vaccine? You likely can’t get unemployment benefits", newsSource: "CNBC", newsDate: "October 7, 2021", newsLink: "https://www.cnbc.com/2021/10/07/fired-for-refusing-a-covid-vaccine-you-likely-cant-get-unemployment-benefits.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "More than 140,000 US children lost a parent or caregiver to Covid, study finds", newsSource: "Guardian", newsDate: "October 7, 2021", newsLink: "https://www.theguardian.com/world/2021/oct/07/covid-hidden-pandemic-children-parents-caregiver"}),
e(NewsList, {newsType: "Media News", newsTitle: "Biden calls for businesses to instate vaccine mandates ahead of federal requirement", newsSource: "NBC News", newsDate: "October 7, 2021", newsLink: "https://www.nbcnews.com/politics/white-house/biden-calls-businesses-instate-vaccine-mandates-ahead-federal-requirement-n1281069"}),
e(NewsList, {newsType: "Media News", newsTitle: "Ghost towns: Nursing home staffing falls amid pandemic", newsSource: "AP News", newsDate: "October 7, 2021", newsLink: "https://apnews.com/article/coronavirus-pandemic-nursing-homes-d1befe76a3a0680b57defb6d9f1cfb66"}),
e(NewsList, {newsType: "Media News", newsTitle: "Faced with losing their jobs, even the most hesitant are getting vaccinated", newsSource: "NPR", newsDate: "October 7, 2021", newsLink: "https://www.npr.org/2021/10/07/1043332198/employer-vaccine-mandates-success-workers-get-shots-to-keep-jobs"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "SARS-CoV-2 infection generates tissue-localized immunological memory in humans", newsSource: "Science", newsDate: "October 7, 2021", newsLink: "https://doi.org/10.1126/sciimmunol.abl9105"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Physical, cognitive, and mental health impacts of COVID-19 after hospitalisation (PHOSP-COVID): a UK multicentre, prospective cohort study", newsSource: "Lancet", newsDate: "October 7, 2021", newsLink: "https://doi.org/10.1016/S2213-2600(21)00383-0"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "SARS-CoV-2 RNA in the Cerebrospinal Fluid of a Patient with Long COVID", newsSource: "Sage Journals", newsDate: "October 7, 2021", newsLink: "https://doi.org/10.1177%2F20499361211048572"}),
e(NewsList, {newsType: "Media News", newsTitle: "Iceland Joins Nordic Peers in Halting Moderna Covid Vaccinations", newsSource: "Bloomberg", newsDate: "October 8, 2021", newsLink: "https://www.bloomberg.com/news/articles/2021-10-08/iceland-joins-nordic-peers-in-halting-moderna-covid-vaccinations"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "Myocardial microthrombi after COVID-19 mRNA vaccination", newsSource: "Oxford Academics", newsDate: "October 8, 2021", newsLink: "https://doi.org/10.1093/eurheartj/ehab727"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Heart-inflammation risk from Pfizer COVID vaccine is very low", newsSource: "Nature", newsDate: "October 8, 2021", newsLink: "https://doi.org/10.1038/d41586-021-02740-y"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "Global prevalence and burden of depressive and anxiety disorders in 204 countries and territories in 2020 due to the COVID-19 pandemic", newsSource: "Lancet", newsDate: "October 8, 2021", newsLink: "https://doi.org/10.1016/S0140-6736(21)02143-7"}),
e(NewsList, {newsType: "Media News", newsTitle: "Could the global Covid death toll be millions higher than thought?", newsSource: "Guardian", newsDate: "October 8, 2021", newsLink: "https://www.theguardian.com/world/2021/oct/08/global-covid-death-toll-higher-pandemic"}),
e(NewsList, {newsType: "Media News", newsTitle: "Anti-vaccine chiropractors rising force of misinformation", newsSource: "AP News", newsDate: "October 8, 2021", newsLink: "https://apnews.com/article/anti-virus-chiropractors-rising-force-misinformation-02b347767b45cab1d6d532be03c57529"}),
e(NewsList, {newsType: "Media News", newsTitle: "Hospitals brace for an onslaught this winter, from flu as well as COVID", newsSource: "NPR", newsDate: "October 8, 2021", newsLink: "https://www.npr.org/sections/health-shots/2021/10/08/1044342789/hospitals-brace-for-an-onslaught-this-winter-from-flu-as-well-as-covid"}),
e(NewsList, {newsType: "Media News", newsTitle: "Revealed: anti-vaccine TikTok videos being viewed by children as young as nine", newsSource: "Guardian", newsDate: "October 8, 2021", newsLink: "https://www.theguardian.com/technology/2021/oct/08/revealed-anti-vaccine-tiktok-videos-viewed-children-as-young-as-nine-covid"}),
e(NewsList, {newsType: "Media News", newsTitle: "States have mandated vaccinations since long before COVID-19", newsSource: "Pew Research", newsDate: "October 8, 2021", newsLink: "https://www.pewresearch.org/fact-tank/2021/10/08/states-have-mandated-vaccinations-since-long-before-covid-19/"}),
e(NewsList, {newsType: "Media News", newsTitle: "Delays set to push Covid jabs for teens in England into Christmas period", newsSource: "Guardian", newsDate: "October 9, 2021", newsLink: "https://www.theguardian.com/world/2021/oct/09/delays-covid-jabs-teens-christmas-period-headteachers-vaccinations"}),               
e(NewsList, {newsType: "Media News", newsTitle: "New Zealand makes COVID-19 vaccinations mandatory for health workers", newsSource: "Reuters", newsDate: "October 10, 2021", newsLink: "https://www.reuters.com/world/asia-pacific/new-zealand-reports-fall-local-covid-19-cases-all-auckland-2021-10-11/"}),
e(NewsList, {newsType: "Media News", newsTitle: "Canada's overworked healthcare sector braces for staff shortages as vaccine mandates loom", newsSource: "Reuters", newsDate: "October 10, 2021", newsLink: "https://www.reuters.com/business/healthcare-pharmaceuticals/canadas-overworked-healthcare-sector-brace-staff-shortages-vaccine-mandates-loom-2021-10-10/"}),               
e(NewsList, {newsType: "Media News", newsTitle: "Getting flu with Covid doubles risk of death, says UK health chief", newsSource: "Guardian", newsDate: "October 10, 2021", newsLink: "https://www.theguardian.com/world/2021/oct/10/getting-flu-with-covid-makes-you-twice-as-likely-to-die-says-uk-health-chief"}),               
e(NewsList, {newsType: "Media News", newsTitle: "Fauci: US must not ‘prematurely declare victory’ over Covid", newsSource: "Guardian", newsDate: "October 10, 2021", newsLink: "https://www.theguardian.com/us-news/2021/oct/10/fauci-covid-halloween-prematurely-declare-victory"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Does the presence of symptoms affect pregnancy outcomes in third trimester in women with SARS-CoV-2", newsSource: "Taylor and Francis", newsDate: "October 10, 2021", newsLink: "https://doi.org/10.1080/14767058.2021.1956895"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Association Between Risk of COVID-19 Infection in Nonimmune Individuals and COVID-19 Immunity in Their Family Members", newsSource: "Jama Network", newsDate: "October 11, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamainternmed.2021.5814"}),               
e(NewsList, {newsType: "Media News", newsTitle: "In search for covid origins, Hubei caves and wildlife farms draw new scrutiny", newsSource: "Washington Post", newsDate: "October 11, 2021", newsLink: "https://www.washingtonpost.com/world/asia_pacific/china-covid-bats-caves-hubei/2021/10/10/082eb8b6-1c32-11ec-bea8-308ea134594f_story.html"}),               
e(NewsList, {newsType: "Media News", newsTitle: "Experts warn of possible twindemic of COVID-19 and flu this winter", newsSource: "CBS News", newsDate: "October 11, 2021", newsLink: "https://www.cbsnews.com/news/covid-19-flu-season-winter-twindemic/"}),
e(NewsList, {newsType: "Media News", newsTitle: "U.S. moves closer to clearing Moderna and J&J Covid booster shots this week", newsSource: "CNBC", newsDate: "October 11, 2021", newsLink: "https://www.cnbc.com/2021/10/11/us-moves-closer-to-clearing-moderna-and-jj-covid-booster-shots-this-week.html"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "Merck and Ridgeback Announce Submission of Emergency Use Authorization Application to the U.S. FDA for Molnupiravir, an Investigational Oral Antiviral Medicine, for the Treatment of Mild-to-Moderate COVID-19 in At Risk Adults", newsSource: "Merck and Ridgeback", newsDate: "October 11, 2021", newsLink: "https://www.merck.com/news/merck-and-ridgeback-announce-submission-of-emergency-use-authorization-application-to-the-u-s-fda-for-molnupiravir-an-investigational-oral-antiviral-medicine-for-the-treatment-of-mild-to-moderate-c/"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "AZD7442 reduced risk of developing severe COVID-19 or death in TACKLE Phase III outpatient treatment trial", newsSource: "AstraZeneca", newsDate: "October 11, 2021", newsLink: "https://www.astrazeneca.com/media-centre/press-releases/2021/azd7442-phiii-trial-positive-in-covid-outpatients.html"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "Impact of circulating SARS-CoV-2 variants on mRNA vaccine-induced immunity", newsSource: "Nature", newsDate: "October 11, 2021", newsLink: "https://doi.org/10.1038/s41586-021-04085-y"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "A novel class of TMPRSS2 inhibitors potently block SARS-CoV-2 and MERS-CoV viral entry and protect human epithelial lung cells", newsSource: "PNAS", newsDate: "October 11, 2021", newsLink: "https://doi.org/10.1073/pnas.2108728118"}),               
e(NewsList, {newsType: "Media News", newsTitle: "Covid pandemic has pushed poor countries to record debt levels – World Bank", newsSource: "Guardian", newsDate: "October 11, 2021", newsLink: "https://www.theguardian.com/business/2021/oct/11/covid-pandemic-has-pushed-poor-countries-to-record-debt-levels-world-bank"}),
e(NewsList, {newsType: "Media News", newsTitle: "FDA staff doesn’t take stance on Moderna Covid booster shots, says two doses are enough to protect against severe disease", newsSource: "CNBC", newsDate: "October 12, 2021", newsLink: "https://www.cnbc.com/2021/10/12/moderna-covid-booster-fda-staff-doesnt-take-stance-says-two-doses-protect-against-severe-disease.html"}),
e(NewsList, {newsType: "Media News", newsTitle: "Italy's toughest-in-the-world COVID-19 vaccine mandate sparks violent protests", newsSource: "CBS News", newsDate: "October 12, 2021", newsLink: "https://www.cbsnews.com/news/covid-19-vaccine-mandate-italy-violent-protests/"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "EMA ends rolling review of CVnCoV COVID-19 vaccine following withdrawal by CureVac AG", newsSource: "European Medicines Agency", newsDate: "October 12, 2021", newsLink: "https://www.ema.europa.eu/en/news/ema-ends-rolling-review-cvncov-covid-19-vaccine-following-withdrawal-curevac-ag"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "Analysis of SARS-CoV-2 infection dynamic in vivo using reporter-expressing viruses", newsSource: "PNAS", newsDate: "October 12, 2021", newsLink: "https://doi.org/10.1073/pnas.2111593118"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Effect of co-flow on fluid dynamics of a cough jet with implications in spread of COVID-19", newsSource: "Physics of Fluid", newsDate: "October 12, 2021", newsLink: "https://doi.org/10.1063/5.0064104"}),
e(NewsList, {newsType: "Non Media News", newsTitle: "Mask effectiveness for preventing secondary cases of COVID-19, Johnson County, Iowa, USA", newsSource: "CDC", newsDate: "October 12, 2021", newsLink: "https://doi.org/10.3201/eid2801.211591"}),               
e(NewsList, {newsType: "Non Media News", newsTitle: "Computational prediction of the effect of amino acid changes on the binding affinity between SARS-CoV-2 spike RBD and human ACE2", newsSource: "PNAS", newsDate: "October 19, 2021", newsLink: "https://doi.org/10.1073/pnas.2106480118"}),  
         ); 
 }
}

document.addEventListener("DOMContentLoaded", function(event) {
  ReactDOM.render(
  e(October2021NewsApp), 
  //e(Welcome, {name: "Person"}), e(NewsList, {newsType: "Non Media News", newsTitle: "", newsSource: "", newsDate: "October , 2021", newsLink: ""}),
  document.querySelector('#article-main-october2021')
  );
});

const pfizerUpdate = document.querySelector('.pfizer-update')
    pfizerUpdate.innerHTML = "Last Updated: 10/11/2021";
const modernaUpdate = document.querySelector('.moderna-update')
    modernaUpdate.innerHTML = "Last Updated: 10/11/2021";
const jessenUpdate = document.querySelector('.jessen-update')
    jessenUpdate.innerHTML = "Last Updated: 10/11/2021";
