//DOM Elements
const usCaseDeathJh = document.querySelector(".us-testing-two");
const usCaseConfirmJh = document.querySelector(".us-testing");

//Define API (https://about-corona.net/documentation, https://covid19api.com/)
const globalapi1 = 'https://corona-api.com/countries';
const globalapi2 = 'https://api.covid19api.com/summary';

//Global Count from covid19-api.org   
   fetch('https://covid19-api.org/api/status')
  .then(response => {
   return response.json();
  })
  .then(data => {
   console.log(data);
   //usCaseDeathJh.textContent = data.Global.TotalDeaths + ' as of ' + data.Date.toString().substring(0, 10);
   //usCaseConfirmJh.textContent = data.Global.TotalConfirmed + ' as of ' + data.Date.toString().substring(0, 10);
   });
   
//Global Count from corona-api      
   fetch(globalapi1)
  .then(response => {
   return response.json();
  })
  .then(data => {
   console.log(data);
   });

//Global Count from covid19api
  fetch(globalapi2, {
  method: 'GET',
  mode: 'cors', // no-cors, *cors, same-origin
  cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
  credentials: 'same-origin', // include, *same-origin, omit
  headers: {
      'Content-Type': 'application/json'
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },   
})
  .then(response => {
   return response.json();
  })
  .then(data => {
   console.log(data);
   options = {
      year: 'numeric', month: 'numeric', day: 'numeric',
      hour: 'numeric', minute: 'numeric', second: 'numeric', 
      dayPeriod: 'short',
      timeZone: 'America/Los_Angeles'
   };
   const date = new Date();
   const datea = new Intl.DateTimeFormat('default', options).format(date);    
   usCaseConfirmJh.textContent = addCommaDecimal(data.Global.TotalConfirmed) + ' as of ' + datea;
   usCaseDeathJh.textContent = addCommaDecimal(data.Global.TotalDeaths) + ' as of ' + datea;   
   /*
   const birthday = new Date();
   const date1 = birthday.getDate();
   const date2 = birthday.getFullYear();
   const date3 = birthday.getMonth() + 1;
   const date4 = date3 + "/" + date1 + "/" + date2;
   usCaseConfirmJh.textContent = data[0].total_cases + ' as of ' + data[0].last_update.toString().substring(6,7) + '/' + data[0].last_update.toString().substring(8,10) + '/' + data[0].last_update.toString().substring(0,4); 
   usCaseDeathJh.textContent = data[0].total_deaths + ' as of ' + data[0].last_update.toString().substring(6,7) + '/' + data[0].last_update.toString().substring(8,10) + '/' + data[0].last_update.toString().substring(0,4);*/   
   });

async function getCountryCountFromCovidApi() {
 await fetch(globalapi2, {
  method: 'GET',
  mode: 'cors', // no-cors, *cors, same-origin
  cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
  credentials: 'same-origin', // include, *same-origin, omit
  headers: {
      'Content-Type': 'application/json'
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },   
}).then(response => response.json())
  .then(data => {
   const country1 = document.querySelector('.country1');
   const caseConfirm1 = document.querySelector('.CaseConfirm1');
   const caseDeath1 = document.querySelector('.CaseDeath1');
   const date1 = document.querySelector('.Date1');
   country1.textContent = data.Countries[1].Country
   caseConfirm1.textContent = addCommaDecimal(data.Countries[1].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[1].NewConfirmed) +')'
   caseDeath1.textContent = addCommaDecimal(data.Countries[1].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[1].NewDeaths) +')'
   date1.textContent = new Date(data.Countries[1].Date).toString().substring(0,15) 
      const country2 = document.querySelector('.country2');
   const caseConfirm2 = document.querySelector('.CaseConfirm2');
   const caseDeath2 = document.querySelector('.CaseDeath2');
   const date2 = document.querySelector('.Date2');
   country2.textContent = data.Countries[2].Country
   caseConfirm2.textContent = addCommaDecimal(data.Countries[2].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[2].NewConfirmed) +')'
   caseDeath2.textContent = addCommaDecimal(data.Countries[2].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[2].NewDeaths) +')'
   date2.textContent = new Date(data.Countries[2].Date).toString().substring(0,15)
      const country3 = document.querySelector('.country3');
   const caseConfirm3 = document.querySelector('.CaseConfirm3');
   const caseDeath3 = document.querySelector('.CaseDeath3');
   const date3 = document.querySelector('.Date3');
   country3.textContent = data.Countries[3].Country
   caseConfirm3.textContent = addCommaDecimal(data.Countries[3].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[3].NewConfirmed) +')'
   caseDeath3.textContent = addCommaDecimal(data.Countries[3].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[3].NewDeaths) +')'
   date3.textContent = new Date(data.Countries[3].Date).toString().substring(0,15)
      const country4 = document.querySelector('.country4');
   const caseConfirm4 = document.querySelector('.CaseConfirm4');
   const caseDeath4 = document.querySelector('.CaseDeath4');
   const date4 = document.querySelector('.Date4');
   country4.textContent = data.Countries[4].Country
   caseConfirm4.textContent = addCommaDecimal(data.Countries[4].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[4].NewConfirmed) +')'
   caseDeath4.textContent = addCommaDecimal(data.Countries[4].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[4].NewDeaths) +')'
   date4.textContent = new Date(data.Countries[4].Date).toString().substring(0,15)
      const country5 = document.querySelector('.country5');
   const caseConfirm5 = document.querySelector('.CaseConfirm5');
   const caseDeath5 = document.querySelector('.CaseDeath5');
   const date5 = document.querySelector('.Date5');
   country5.textContent = data.Countries[5].Country
   caseConfirm5.textContent = addCommaDecimal(data.Countries[5].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[5].NewConfirmed) +')'
   caseDeath5.textContent = addCommaDecimal(data.Countries[5].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[5].NewDeaths) +')'
   date5.textContent = new Date(data.Countries[5].Date).toString().substring(0,15)
      const country6 = document.querySelector('.country6');
   const caseConfirm6 = document.querySelector('.CaseConfirm6');
   const caseDeath6 = document.querySelector('.CaseDeath6');
   const date6 = document.querySelector('.Date6');
   country6.textContent = data.Countries[6].Country
   caseConfirm6.textContent = addCommaDecimal(data.Countries[6].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[6].NewConfirmed) +')'
   caseDeath6.textContent = addCommaDecimal(data.Countries[6].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[6].NewDeaths) +')'
   date6.textContent = new Date(data.Countries[6].Date).toString().substring(0,15)
      const country7 = document.querySelector('.country7');
   const caseConfirm7 = document.querySelector('.CaseConfirm7');
   const caseDeath7 = document.querySelector('.CaseDeath7');
   const date7 = document.querySelector('.Date7');
   country7.textContent = data.Countries[7].Country
   caseConfirm7.textContent = addCommaDecimal(data.Countries[7].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[7].NewConfirmed) +')'
   caseDeath7.textContent = addCommaDecimal(data.Countries[7].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[7].NewDeaths) +')'
   date7.textContent = new Date(data.Countries[7].Date).toString().substring(0,15)
      const country8 = document.querySelector('.country8');
   const caseConfirm8 = document.querySelector('.CaseConfirm8');
   const caseDeath8 = document.querySelector('.CaseDeath8');
   const date8 = document.querySelector('.Date8');
   country8.textContent = data.Countries[8].Country
   caseConfirm8.textContent = addCommaDecimal(data.Countries[8].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[8].NewConfirmed) +')'
   caseDeath8.textContent = addCommaDecimal(data.Countries[8].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[8].NewDeaths) +')'
   date8.textContent = new Date(data.Countries[8].Date).toString().substring(0,15)
      const country9 = document.querySelector('.country9');
   const caseConfirm9 = document.querySelector('.CaseConfirm9');
   const caseDeath9 = document.querySelector('.CaseDeath9');
   const date9 = document.querySelector('.Date9');
   country9.textContent = data.Countries[9].Country
   caseConfirm9.textContent = addCommaDecimal(data.Countries[9].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[9].NewConfirmed) +')'
   caseDeath9.textContent = addCommaDecimal(data.Countries[9].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[9].NewDeaths) +')'
   date9.textContent = new Date(data.Countries[9].Date).toString().substring(0,15)
      const country10 = document.querySelector('.country10');
   const caseConfirm10 = document.querySelector('.CaseConfirm10');
   const caseDeath10 = document.querySelector('.CaseDeath10');
   const date10 = document.querySelector('.Date10');
   country10.textContent = data.Countries[10].Country
   caseConfirm10.textContent = addCommaDecimal(data.Countries[10].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[10].NewConfirmed) +')'
   caseDeath10.textContent = addCommaDecimal(data.Countries[10].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[10].NewDeaths) +')'
   date10.textContent = new Date(data.Countries[10].Date).toString().substring(0,15)
      const country11 = document.querySelector('.country11');
   const caseConfirm11 = document.querySelector('.CaseConfirm11');
   const caseDeath11 = document.querySelector('.CaseDeath11');
   const date11 = document.querySelector('.Date11');
   country11.textContent = data.Countries[11].Country
   caseConfirm11.textContent = addCommaDecimal(data.Countries[11].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[11].NewConfirmed) +')'
   caseDeath11.textContent = addCommaDecimal(data.Countries[11].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[11].NewDeaths) +')'
   date11.textContent = new Date(data.Countries[11].Date).toString().substring(0,15)
      const country12 = document.querySelector('.country12');
   const caseConfirm12 = document.querySelector('.CaseConfirm12');
   const caseDeath12 = document.querySelector('.CaseDeath12');
   const date12 = document.querySelector('.Date12');
   country12.textContent = data.Countries[12].Country
   caseConfirm12.textContent = addCommaDecimal(data.Countries[12].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[12].NewConfirmed) +')'
   caseDeath12.textContent = addCommaDecimal(data.Countries[12].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[12].NewDeaths) +')'
   date12.textContent = new Date(data.Countries[12].Date).toString().substring(0,15) 
      const country13 = document.querySelector('.country13');
   const caseConfirm13 = document.querySelector('.CaseConfirm13');
   const caseDeath13 = document.querySelector('.CaseDeath13');
   const date13 = document.querySelector('.Date13');
   country13.textContent = data.Countries[13].Country
   caseConfirm13.textContent = addCommaDecimal(data.Countries[13].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[13].NewConfirmed) +')'
   caseDeath13.textContent = addCommaDecimal(data.Countries[13].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[13].NewDeaths) +')'
   date13.textContent = new Date(data.Countries[13].Date).toString().substring(0,15)   
      const country14 = document.querySelector('.country14');
   const caseConfirm14 = document.querySelector('.CaseConfirm14');
   const caseDeath14 = document.querySelector('.CaseDeath14');
   const date14 = document.querySelector('.Date14');
   country14.textContent = data.Countries[14].Country
   caseConfirm14.textContent = addCommaDecimal(data.Countries[14].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[14].NewConfirmed) +')'
   caseDeath14.textContent = addCommaDecimal(data.Countries[14].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[14].NewDeaths) +')'
   date14.textContent = new Date(data.Countries[14].Date).toString().substring(0,15)  
      const country15 = document.querySelector('.country15');
   const caseConfirm15 = document.querySelector('.CaseConfirm15');
   const caseDeath15 = document.querySelector('.CaseDeath15');
   const date15 = document.querySelector('.Date15');
   country15.textContent = data.Countries[15].Country
   caseConfirm15.textContent = addCommaDecimal(data.Countries[15].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[15].NewConfirmed) +')'
   caseDeath15.textContent = addCommaDecimal(data.Countries[15].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[15].NewDeaths) +')'
   date15.textContent = new Date(data.Countries[15].Date).toString().substring(0,15)
      const country16 = document.querySelector('.country16');
   const caseConfirm16 = document.querySelector('.CaseConfirm16');
   const caseDeath16 = document.querySelector('.CaseDeath16');
   const date16 = document.querySelector('.Date16');
   country16.textContent = data.Countries[16].Country
   caseConfirm16.textContent = addCommaDecimal(data.Countries[16].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[16].NewConfirmed) +')'
   caseDeath16.textContent = addCommaDecimal(data.Countries[16].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[16].NewDeaths) +')'
   date16.textContent = new Date(data.Countries[16].Date).toString().substring(0,15)
      const country17 = document.querySelector('.country17');
   const caseConfirm17 = document.querySelector('.CaseConfirm17');
   const caseDeath17 = document.querySelector('.CaseDeath17');
   const date17 = document.querySelector('.Date17');
   country17.textContent = data.Countries[17].Country
   caseConfirm17.textContent = addCommaDecimal(data.Countries[17].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[17].NewConfirmed) +')'
   caseDeath17.textContent = addCommaDecimal(data.Countries[17].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[17].NewDeaths) +')'
   date17.textContent = new Date(data.Countries[17].Date).toString().substring(0,15) 
      const country18 = document.querySelector('.country18');
   const caseConfirm18 = document.querySelector('.CaseConfirm18');
   const caseDeath18 = document.querySelector('.CaseDeath18');
   const date18 = document.querySelector('.Date18');
   country18.textContent = data.Countries[18].Country
   caseConfirm18.textContent = addCommaDecimal(data.Countries[18].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[18].NewConfirmed) +')'
   caseDeath18.textContent = addCommaDecimal(data.Countries[18].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[18].NewDeaths) +')'
   date18.textContent = new Date(data.Countries[18].Date).toString().substring(0,15)
      const country19 = document.querySelector('.country19');
   const caseConfirm19 = document.querySelector('.CaseConfirm19');
   const caseDeath19 = document.querySelector('.CaseDeath19');
   const date19 = document.querySelector('.Date19');
   country19.textContent = data.Countries[19].Country
   caseConfirm19.textContent = addCommaDecimal(data.Countries[19].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[19].NewConfirmed) +')'
   caseDeath19.textContent = addCommaDecimal(data.Countries[19].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[19].NewDeaths) +')'
   date19.textContent = new Date(data.Countries[19].Date).toString().substring(0,15)    
      const country20 = document.querySelector('.country20');
   const caseConfirm20 = document.querySelector('.CaseConfirm20');
   const caseDeath20 = document.querySelector('.CaseDeath20');
   const date20 = document.querySelector('.Date20');
   country20.textContent = data.Countries[20].Country
   caseConfirm20.textContent = addCommaDecimal(data.Countries[20].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[20].NewConfirmed) +')'
   caseDeath20.textContent = addCommaDecimal(data.Countries[20].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[20].NewDeaths) +')'
   date20.textContent = new Date(data.Countries[20].Date).toString().substring(0,15) 
      const country21 = document.querySelector('.country21');
   const caseConfirm21 = document.querySelector('.CaseConfirm21');
   const caseDeath21 = document.querySelector('.CaseDeath21');
   const date21 = document.querySelector('.Date21');
   country21.textContent = data.Countries[21].Country
   caseConfirm21.textContent = addCommaDecimal(data.Countries[21].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[21].NewConfirmed) +')'
   caseDeath21.textContent = addCommaDecimal(data.Countries[21].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[21].NewDeaths) +')'
   date21.textContent = new Date(data.Countries[21].Date).toString().substring(0,15)  
      const country22 = document.querySelector('.country22');
   const caseConfirm22 = document.querySelector('.CaseConfirm22');
   const caseDeath22 = document.querySelector('.CaseDeath22');
   const date22 = document.querySelector('.Date22');
   country22.textContent = data.Countries[22].Country
   caseConfirm22.textContent = addCommaDecimal(data.Countries[22].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[22].NewConfirmed) +')'
   caseDeath22.textContent = addCommaDecimal(data.Countries[22].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[22].NewDeaths) +')'
   date22.textContent = new Date(data.Countries[22].Date).toString().substring(0,15)
      const country23 = document.querySelector('.country23');
   const caseConfirm23 = document.querySelector('.CaseConfirm23');
   const caseDeath23 = document.querySelector('.CaseDeath23');
   const date23 = document.querySelector('.Date23');
   country23.textContent = data.Countries[23].Country
   caseConfirm23.textContent = addCommaDecimal(data.Countries[23].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[23].NewConfirmed) +')'
   caseDeath23.textContent = addCommaDecimal(data.Countries[23].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[23].NewDeaths) +')'
   date23.textContent = new Date(data.Countries[23].Date).toString().substring(0,15) 
      const country24 = document.querySelector('.country24');
   const caseConfirm24 = document.querySelector('.CaseConfirm24');
   const caseDeath24 = document.querySelector('.CaseDeath24');
   const date24 = document.querySelector('.Date24');
   country24.textContent = data.Countries[24].Country
   caseConfirm24.textContent = addCommaDecimal(data.Countries[24].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[24].NewConfirmed) +')'
   caseDeath24.textContent = addCommaDecimal(data.Countries[24].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[24].NewDeaths) +')'
   date24.textContent = new Date(data.Countries[24].Date).toString().substring(0,15)
      const country25 = document.querySelector('.country25');
   const caseConfirm25 = document.querySelector('.CaseConfirm25');
   const caseDeath25 = document.querySelector('.CaseDeath25');
   const date25 = document.querySelector('.Date25');
   country25.textContent = data.Countries[25].Country
   caseConfirm25.textContent = addCommaDecimal(data.Countries[25].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[25].NewConfirmed) +')'
   caseDeath25.textContent = addCommaDecimal(data.Countries[25].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[25].NewDeaths) +')'
   date25.textContent = new Date(data.Countries[25].Date).toString().substring(0,15) 
      const country26 = document.querySelector('.country26');
   const caseConfirm26 = document.querySelector('.CaseConfirm26');
   const caseDeath26 = document.querySelector('.CaseDeath26');
   const date26 = document.querySelector('.Date26');
   country26.textContent = data.Countries[26].Country
   caseConfirm26.textContent = addCommaDecimal(data.Countries[26].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[26].NewConfirmed) +')'
   caseDeath26.textContent = addCommaDecimal(data.Countries[26].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[26].NewDeaths) +')'
   date26.textContent = new Date(data.Countries[26].Date).toString().substring(0,15)
      const country27 = document.querySelector('.country27');
   const caseConfirm27 = document.querySelector('.CaseConfirm27');
   const caseDeath27 = document.querySelector('.CaseDeath27');
   const date27 = document.querySelector('.Date27');
   country27.textContent = data.Countries[27].Country
   caseConfirm27.textContent = addCommaDecimal(data.Countries[27].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[27].NewConfirmed) +')'
   caseDeath27.textContent = addCommaDecimal(data.Countries[27].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[27].NewDeaths) +')'
   date27.textContent = new Date(data.Countries[27].Date).toString().substring(0,15)  
      const country28 = document.querySelector('.country28');
   const caseConfirm28 = document.querySelector('.CaseConfirm28');
   const caseDeath28 = document.querySelector('.CaseDeath28');
   const date28 = document.querySelector('.Date28');
   country28.textContent = data.Countries[28].Country
   caseConfirm28.textContent = addCommaDecimal(data.Countries[28].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[28].NewConfirmed) +')'
   caseDeath28.textContent = addCommaDecimal(data.Countries[28].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[28].NewDeaths) +')'
   date28.textContent = new Date(data.Countries[28].Date).toString().substring(0,15)   
      const country29 = document.querySelector('.country29');
   const caseConfirm29 = document.querySelector('.CaseConfirm29');
   const caseDeath29 = document.querySelector('.CaseDeath29');
   const date29 = document.querySelector('.Date29');
   country29.textContent = data.Countries[29].Country
   caseConfirm29.textContent = addCommaDecimal(data.Countries[29].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[29].NewConfirmed) +')'
   caseDeath29.textContent = addCommaDecimal(data.Countries[29].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[29].NewDeaths) +')'
   date29.textContent = new Date(data.Countries[29].Date).toString().substring(0,15)     
      const country30 = document.querySelector('.country30');
   const caseConfirm30 = document.querySelector('.CaseConfirm30');
   const caseDeath30 = document.querySelector('.CaseDeath30');
   const date30 = document.querySelector('.Date30');
   country30.textContent = data.Countries[30].Country
   caseConfirm30.textContent = addCommaDecimal(data.Countries[30].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[30].NewConfirmed) +')'
   caseDeath30.textContent = addCommaDecimal(data.Countries[30].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[30].NewDeaths) +')'
   date30.textContent = new Date(data.Countries[30].Date).toString().substring(0,15)
      const country31 = document.querySelector('.country31');
   const caseConfirm31 = document.querySelector('.CaseConfirm31');
   const caseDeath31 = document.querySelector('.CaseDeath31');
   const date31 = document.querySelector('.Date31');
   country31.textContent = data.Countries[31].Country
   caseConfirm31.textContent = addCommaDecimal(data.Countries[31].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[31].NewConfirmed) +')'
   caseDeath31.textContent = addCommaDecimal(data.Countries[31].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[31].NewDeaths) +')'
   date31.textContent = new Date(data.Countries[31].Date).toString().substring(0,15)
      const country32 = document.querySelector('.country32');
   const caseConfirm32 = document.querySelector('.CaseConfirm32');
   const caseDeath32 = document.querySelector('.CaseDeath32');
   const date32 = document.querySelector('.Date32');
   country32.textContent = data.Countries[32].Country
   caseConfirm32.textContent = addCommaDecimal(data.Countries[32].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[32].NewConfirmed) +')'
   caseDeath32.textContent = addCommaDecimal(data.Countries[32].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[32].NewDeaths) +')'
   date32.textContent = new Date(data.Countries[32].Date).toString().substring(0,15)
      const country33 = document.querySelector('.country33');
   const caseConfirm33 = document.querySelector('.CaseConfirm33');
   const caseDeath33 = document.querySelector('.CaseDeath33');
   const date33 = document.querySelector('.Date33');
   country33.textContent = data.Countries[33].Country
   caseConfirm33.textContent = addCommaDecimal(data.Countries[33].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[33].NewConfirmed) +')'
   caseDeath33.textContent = addCommaDecimal(data.Countries[33].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[33].NewDeaths) +')'
   date33.textContent = new Date(data.Countries[33].Date).toString().substring(0,15)
      const country34 = document.querySelector('.country34');
   const caseConfirm34 = document.querySelector('.CaseConfirm34');
   const caseDeath34 = document.querySelector('.CaseDeath34');
   const date34 = document.querySelector('.Date34');
   country34.textContent = data.Countries[34].Country
   caseConfirm34.textContent = addCommaDecimal(data.Countries[34].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[34].NewConfirmed) +')'
   caseDeath34.textContent = addCommaDecimal(data.Countries[34].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[34].NewDeaths) +')'
   date34.textContent = new Date(data.Countries[34].Date).toString().substring(0,15)
      const country35 = document.querySelector('.country35');
   const caseConfirm35 = document.querySelector('.CaseConfirm35');
   const caseDeath35 = document.querySelector('.CaseDeath35');
   const date35 = document.querySelector('.Date35');
   country35.textContent = data.Countries[35].Country
   caseConfirm35.textContent = addCommaDecimal(data.Countries[35].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[35].NewConfirmed) +')'
   caseDeath35.textContent = addCommaDecimal(data.Countries[35].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[35].NewDeaths) +')'
   date35.textContent = new Date(data.Countries[35].Date).toString().substring(0,15)  
      const country36 = document.querySelector('.country36');
   const caseConfirm36 = document.querySelector('.CaseConfirm36');
   const caseDeath36 = document.querySelector('.CaseDeath36');
   const date36 = document.querySelector('.Date36');
   country36.textContent = data.Countries[36].Country
   caseConfirm36.textContent = addCommaDecimal(data.Countries[36].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[36].NewConfirmed) +')'
   caseDeath36.textContent = addCommaDecimal(data.Countries[36].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[36].NewDeaths) +')'
   date36.textContent = new Date(data.Countries[36].Date).toString().substring(0,15)
      const country37 = document.querySelector('.country37');
   const caseConfirm37 = document.querySelector('.CaseConfirm37');
   const caseDeath37 = document.querySelector('.CaseDeath37');
   const date37 = document.querySelector('.Date37');
   country37.textContent = data.Countries[37].Country
   caseConfirm37.textContent = addCommaDecimal(data.Countries[37].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[37].NewConfirmed) +')'
   caseDeath37.textContent = addCommaDecimal(data.Countries[37].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[37].NewDeaths) +')'
   date37.textContent = new Date(data.Countries[37].Date).toString().substring(0,15)
      const country38 = document.querySelector('.country38');
   const caseConfirm38 = document.querySelector('.CaseConfirm38');
   const caseDeath38 = document.querySelector('.CaseDeath38');
   const date38 = document.querySelector('.Date38');
   country38.textContent = data.Countries[38].Country
   caseConfirm38.textContent = addCommaDecimal(data.Countries[38].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[38].NewConfirmed) +')'
   caseDeath38.textContent = addCommaDecimal(data.Countries[38].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[38].NewDeaths) +')'
   date38.textContent = new Date(data.Countries[38].Date).toString().substring(0,15)
      const country39 = document.querySelector('.country39');
   const caseConfirm39 = document.querySelector('.CaseConfirm39');
   const caseDeath39 = document.querySelector('.CaseDeath39');
   const date39 = document.querySelector('.Date39');
   country39.textContent = data.Countries[39].Country
   caseConfirm39.textContent = addCommaDecimal(data.Countries[39].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[39].NewConfirmed) +')'
   caseDeath39.textContent = addCommaDecimal(data.Countries[39].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[39].NewDeaths) +')'
   date39.textContent = new Date(data.Countries[39].Date).toString().substring(0,15)        
      const country40 = document.querySelector('.country40');
   const caseConfirm40 = document.querySelector('.CaseConfirm40');
   const caseDeath40 = document.querySelector('.CaseDeath40');
   const date40 = document.querySelector('.Date40');
   country40.textContent = data.Countries[40].Country
   caseConfirm40.textContent = addCommaDecimal(data.Countries[40].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[40].NewConfirmed) +')'
   caseDeath40.textContent = addCommaDecimal(data.Countries[40].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[40].NewDeaths) +')'
   date40.textContent = new Date(data.Countries[40].Date).toString().substring(0,15) 
      const country41 = document.querySelector('.country41');
   const caseConfirm41 = document.querySelector('.CaseConfirm41');
   const caseDeath41 = document.querySelector('.CaseDeath41');
   const date41 = document.querySelector('.Date41');
   country41.textContent = data.Countries[41].Country
   caseConfirm41.textContent = addCommaDecimal(data.Countries[41].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[41].NewConfirmed) +')'
   caseDeath41.textContent = addCommaDecimal(data.Countries[41].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[41].NewDeaths) +')'
   date41.textContent = new Date(data.Countries[41].Date).toString().substring(0,15) 
      const country42 = document.querySelector('.country42');
   const caseConfirm42 = document.querySelector('.CaseConfirm42');
   const caseDeath42 = document.querySelector('.CaseDeath42');
   const date42 = document.querySelector('.Date42');
   country42.textContent = data.Countries[42].Country
   caseConfirm42.textContent = addCommaDecimal(data.Countries[42].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[42].NewConfirmed) +')'
   caseDeath42.textContent = addCommaDecimal(data.Countries[42].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[42].NewDeaths) +')'
   date42.textContent = new Date(data.Countries[42].Date).toString().substring(0,15)
      const country43 = document.querySelector('.country43');
   const caseConfirm43 = document.querySelector('.CaseConfirm43');
   const caseDeath43 = document.querySelector('.CaseDeath43');
   const date43 = document.querySelector('.Date43');
   country43.textContent = data.Countries[43].Country
   caseConfirm43.textContent = addCommaDecimal(data.Countries[43].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[43].NewConfirmed) +')'
   caseDeath43.textContent = addCommaDecimal(data.Countries[43].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[43].NewDeaths) +')'
   date43.textContent = new Date(data.Countries[43].Date).toString().substring(0,15)
      const country44 = document.querySelector('.country44');
   const caseConfirm44 = document.querySelector('.CaseConfirm44');
   const caseDeath44 = document.querySelector('.CaseDeath44');
   const date44 = document.querySelector('.Date44');
   country44.textContent = data.Countries[44].Country
   caseConfirm44.textContent = addCommaDecimal(data.Countries[44].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[44].NewConfirmed) +')'
   caseDeath44.textContent = addCommaDecimal(data.Countries[44].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[44].NewDeaths) +')'
   date44.textContent = new Date(data.Countries[44].Date).toString().substring(0,15)
      const country45 = document.querySelector('.country45');
   const caseConfirm45 = document.querySelector('.CaseConfirm45');
   const caseDeath45 = document.querySelector('.CaseDeath45');
   const date45 = document.querySelector('.Date45');
   country45.textContent = data.Countries[45].Country
   caseConfirm45.textContent = addCommaDecimal(data.Countries[45].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[45].NewConfirmed) +')'
   caseDeath45.textContent = addCommaDecimal(data.Countries[45].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[45].NewDeaths) +')'
   date45.textContent = new Date(data.Countries[45].Date).toString().substring(0,15)
      const country46 = document.querySelector('.country46');
   const caseConfirm46 = document.querySelector('.CaseConfirm46');
   const caseDeath46 = document.querySelector('.CaseDeath46');
   const date46 = document.querySelector('.Date46');
   country46.textContent = data.Countries[46].Country
   caseConfirm46.textContent = addCommaDecimal(data.Countries[46].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[46].NewConfirmed) +')'
   caseDeath46.textContent = addCommaDecimal(data.Countries[46].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[46].NewDeaths) +')'
   date46.textContent = new Date(data.Countries[46].Date).toString().substring(0,15)
      const country47 = document.querySelector('.country47');
   const caseConfirm47 = document.querySelector('.CaseConfirm47');
   const caseDeath47 = document.querySelector('.CaseDeath47');
   const date47 = document.querySelector('.Date47');
   country47.textContent = data.Countries[47].Country
   caseConfirm47.textContent = addCommaDecimal(data.Countries[47].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[47].NewConfirmed) +')'
   caseDeath47.textContent = addCommaDecimal(data.Countries[47].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[47].NewDeaths) +')'
   date47.textContent = new Date(data.Countries[47].Date).toString().substring(0,15) 
      const country48 = document.querySelector('.country48');
   const caseConfirm48 = document.querySelector('.CaseConfirm48');
   const caseDeath48 = document.querySelector('.CaseDeath48');
   const date48 = document.querySelector('.Date48');
   country48.textContent = data.Countries[48].Country
   caseConfirm48.textContent = addCommaDecimal(data.Countries[48].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[48].NewConfirmed) +')'
   caseDeath48.textContent = addCommaDecimal(data.Countries[48].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[48].NewDeaths) +')'
   date48.textContent = new Date(data.Countries[48].Date).toString().substring(0,15)
      const country49 = document.querySelector('.country49');
   const caseConfirm49 = document.querySelector('.CaseConfirm49');
   const caseDeath49 = document.querySelector('.CaseDeath49');
   const date49 = document.querySelector('.Date49');
   country49.textContent = data.Countries[49].Country
   caseConfirm49.textContent = addCommaDecimal(data.Countries[49].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[49].NewConfirmed) +')'
   caseDeath49.textContent = addCommaDecimal(data.Countries[49].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[49].NewDeaths) +')'
   date49.textContent = new Date(data.Countries[49].Date).toString().substring(0,15)    
      const country50 = document.querySelector('.country50');
   const caseConfirm50 = document.querySelector('.CaseConfirm50');
   const caseDeath50 = document.querySelector('.CaseDeath50');
   const date50 = document.querySelector('.Date50');
   country50.textContent = data.Countries[50].Country
   caseConfirm50.textContent = addCommaDecimal(data.Countries[50].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[50].NewConfirmed) +')'
   caseDeath50.textContent = addCommaDecimal(data.Countries[50].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[50].NewDeaths) +')'
   date50.textContent = new Date(data.Countries[50].Date).toString().substring(0,15)
      const country51 = document.querySelector('.country51');
   const caseConfirm51 = document.querySelector('.CaseConfirm51');
   const caseDeath51 = document.querySelector('.CaseDeath51');
   const date51 = document.querySelector('.Date51');
   country51.textContent = data.Countries[51].Country
   caseConfirm51.textContent = addCommaDecimal(data.Countries[51].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[51].NewConfirmed) +')'
   caseDeath51.textContent = addCommaDecimal(data.Countries[51].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[51].NewDeaths) +')'
   date51.textContent = new Date(data.Countries[51].Date).toString().substring(0,15)
      const country52 = document.querySelector('.country52');
   const caseConfirm52 = document.querySelector('.CaseConfirm52');
   const caseDeath52 = document.querySelector('.CaseDeath52');
   const date52 = document.querySelector('.Date52');
   country52.textContent = data.Countries[52].Country
   caseConfirm52.textContent = addCommaDecimal(data.Countries[52].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[52].NewConfirmed) +')'
   caseDeath52.textContent = addCommaDecimal(data.Countries[52].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[52].NewDeaths) +')'
   date52.textContent = new Date(data.Countries[52].Date).toString().substring(0,15)
      const country53 = document.querySelector('.country53');
   const caseConfirm53 = document.querySelector('.CaseConfirm53');
   const caseDeath53 = document.querySelector('.CaseDeath53');
   const date53 = document.querySelector('.Date53');
   country53.textContent = data.Countries[53].Country
   caseConfirm53.textContent = addCommaDecimal(data.Countries[53].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[53].NewConfirmed) +')'
   caseDeath53.textContent = addCommaDecimal(data.Countries[53].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[53].NewDeaths) +')'
   date53.textContent = new Date(data.Countries[53].Date).toString().substring(0,15)
      const country54 = document.querySelector('.country54');
   const caseConfirm54 = document.querySelector('.CaseConfirm54');
   const caseDeath54 = document.querySelector('.CaseDeath54');
   const date54 = document.querySelector('.Date54');
   country54.textContent = data.Countries[54].Country
   caseConfirm54.textContent = addCommaDecimal(data.Countries[54].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[54].NewConfirmed) +')'
   caseDeath54.textContent = addCommaDecimal(data.Countries[54].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[54].NewDeaths) +')'
   date54.textContent = new Date(data.Countries[54].Date).toString().substring(0,15)    
      const country55 = document.querySelector('.country55');
   const caseConfirm55 = document.querySelector('.CaseConfirm55');
   const caseDeath55 = document.querySelector('.CaseDeath55');
   const date55 = document.querySelector('.Date55');
   country55.textContent = data.Countries[55].Country
   caseConfirm55.textContent = addCommaDecimal(data.Countries[55].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[55].NewConfirmed) +')'
   caseDeath55.textContent = addCommaDecimal(data.Countries[55].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[55].NewDeaths) +')'
   date55.textContent = new Date(data.Countries[55].Date).toString().substring(0,15)
      const country56 = document.querySelector('.country56');
   const caseConfirm56 = document.querySelector('.CaseConfirm56');
   const caseDeath56 = document.querySelector('.CaseDeath56');
   const date56 = document.querySelector('.Date56');
   country56.textContent = data.Countries[56].Country
   caseConfirm56.textContent = addCommaDecimal(data.Countries[56].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[56].NewConfirmed) +')'
   caseDeath56.textContent = addCommaDecimal(data.Countries[56].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[56].NewDeaths) +')'
   date56.textContent = new Date(data.Countries[56].Date).toString().substring(0,15)
      const country57 = document.querySelector('.country57');
   const caseConfirm57 = document.querySelector('.CaseConfirm57');
   const caseDeath57 = document.querySelector('.CaseDeath57');
   const date57 = document.querySelector('.Date57');
   country57.textContent = data.Countries[57].Country
   caseConfirm57.textContent = addCommaDecimal(data.Countries[57].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[57].NewConfirmed) +')'
   caseDeath57.textContent = addCommaDecimal(data.Countries[57].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[57].NewDeaths) +')'
   date57.textContent = new Date(data.Countries[57].Date).toString().substring(0,15)
      const country58 = document.querySelector('.country58');
   const caseConfirm58 = document.querySelector('.CaseConfirm58');
   const caseDeath58 = document.querySelector('.CaseDeath58');
   const date58 = document.querySelector('.Date58');
   country58.textContent = data.Countries[58].Country
   caseConfirm58.textContent = addCommaDecimal(data.Countries[58].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[58].NewConfirmed) +')'
   caseDeath58.textContent = addCommaDecimal(data.Countries[58].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[58].NewDeaths) +')'
   date58.textContent = new Date(data.Countries[58].Date).toString().substring(0,15)
      const country59 = document.querySelector('.country59');
   const caseConfirm59 = document.querySelector('.CaseConfirm59');
   const caseDeath59 = document.querySelector('.CaseDeath59');
   const date59 = document.querySelector('.Date59');
   country59.textContent = data.Countries[59].Country
   caseConfirm59.textContent = addCommaDecimal(data.Countries[59].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[59].NewConfirmed) +')'
   caseDeath59.textContent = addCommaDecimal(data.Countries[59].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[59].NewDeaths) +')'
   date59.textContent = new Date(data.Countries[59].Date).toString().substring(0,15)    
      const country60 = document.querySelector('.country60');
   const caseConfirm60 = document.querySelector('.CaseConfirm60');
   const caseDeath60 = document.querySelector('.CaseDeath60');
   const date60 = document.querySelector('.Date60');
   country60.textContent = data.Countries[60].Country
   caseConfirm60.textContent = addCommaDecimal(data.Countries[60].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[60].NewConfirmed) +')'
   caseDeath60.textContent = addCommaDecimal(data.Countries[60].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[60].NewDeaths) +')'
   date60.textContent = new Date(data.Countries[60].Date).toString().substring(0,15)
      const country61 = document.querySelector('.country61');
   const caseConfirm61 = document.querySelector('.CaseConfirm61');
   const caseDeath61 = document.querySelector('.CaseDeath61');
   const date61 = document.querySelector('.Date61');
   country61.textContent = data.Countries[61].Country
   caseConfirm61.textContent = addCommaDecimal(data.Countries[61].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[61].NewConfirmed) +')'
   caseDeath61.textContent = addCommaDecimal(data.Countries[61].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[61].NewDeaths) +')'
   date61.textContent = new Date(data.Countries[61].Date).toString().substring(0,15)   
      const country62 = document.querySelector('.country62');
   const caseConfirm62= document.querySelector('.CaseConfirm62');
   const caseDeath62 = document.querySelector('.CaseDeath62');
   const date62 = document.querySelector('.Date62');
   country62.textContent = data.Countries[62].Country
   caseConfirm62.textContent = addCommaDecimal(data.Countries[62].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[62].NewConfirmed) +')'
   caseDeath62.textContent = addCommaDecimal(data.Countries[62].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[62].NewDeaths) +')'
   date62.textContent = new Date(data.Countries[62].Date).toString().substring(0,15)   
      const country63 = document.querySelector('.country63');
   const caseConfirm63 = document.querySelector('.CaseConfirm63');
   const caseDeath63 = document.querySelector('.CaseDeath63');
   const date63 = document.querySelector('.Date63');
   country63.textContent = data.Countries[63].Country
   caseConfirm63.textContent = addCommaDecimal(data.Countries[63].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[63].NewConfirmed) +')'
   caseDeath63.textContent = addCommaDecimal(data.Countries[63].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[63].NewDeaths) +')'
   date63.textContent = new Date(data.Countries[63].Date).toString().substring(0,15)     
      const country64 = document.querySelector('.country64');
   const caseConfirm64 = document.querySelector('.CaseConfirm64');
   const caseDeath64 = document.querySelector('.CaseDeath64');
   const date64 = document.querySelector('.Date64');
   country64.textContent = data.Countries[64].Country
   caseConfirm64.textContent = addCommaDecimal(data.Countries[64].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[64].NewConfirmed) +')'
   caseDeath64.textContent = addCommaDecimal(data.Countries[64].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[64].NewDeaths) +')'
   date64.textContent = new Date(data.Countries[64].Date).toString().substring(0,15)
      const country65 = document.querySelector('.country65');
   const caseConfirm65 = document.querySelector('.CaseConfirm65');
   const caseDeath65 = document.querySelector('.CaseDeath65');
   const date65 = document.querySelector('.Date65');
   country65.textContent = data.Countries[65].Country
   caseConfirm65.textContent = addCommaDecimal(data.Countries[65].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[65].NewConfirmed) +')'
   caseDeath65.textContent = addCommaDecimal(data.Countries[65].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[65].NewDeaths) +')'
   date65.textContent = new Date(data.Countries[65].Date).toString().substring(0,15)   
      const country66 = document.querySelector('.country66');
   const caseConfirm66 = document.querySelector('.CaseConfirm66');
   const caseDeath66 = document.querySelector('.CaseDeath66');
   const date66 = document.querySelector('.Date66');
   country66.textContent = data.Countries[66].Country
   caseConfirm66.textContent = addCommaDecimal(data.Countries[66].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[66].NewConfirmed) +')'
   caseDeath66.textContent = addCommaDecimal(data.Countries[66].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[66].NewDeaths) +')'
   date66.textContent = new Date(data.Countries[66].Date).toString().substring(0,15)   
      const country67 = document.querySelector('.country67');
   const caseConfirm67 = document.querySelector('.CaseConfirm67');
   const caseDeath67 = document.querySelector('.CaseDeath67');
   const date67 = document.querySelector('.Date67');
   country67.textContent = data.Countries[67].Country
   caseConfirm67.textContent = addCommaDecimal(data.Countries[67].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[67].NewConfirmed) +')'
   caseDeath67.textContent = addCommaDecimal(data.Countries[67].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[67].NewDeaths) +')'
   date67.textContent = new Date(data.Countries[67].Date).toString().substring(0,15)    
      const country68 = document.querySelector('.country68');
   const caseConfirm68 = document.querySelector('.CaseConfirm68');
   const caseDeath68 = document.querySelector('.CaseDeath68');
   const date68 = document.querySelector('.Date68');
   country68.textContent = data.Countries[68].Country
   caseConfirm68.textContent = addCommaDecimal(data.Countries[68].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[68].NewConfirmed) +')'
   caseDeath68.textContent = addCommaDecimal(data.Countries[68].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[68].NewDeaths) +')'
   date68.textContent = new Date(data.Countries[68].Date).toString().substring(0,15)
      const country69 = document.querySelector('.country69');
   const caseConfirm69 = document.querySelector('.CaseConfirm69');
   const caseDeath69 = document.querySelector('.CaseDeath69');
   const date69 = document.querySelector('.Date69');
   country69.textContent = data.Countries[69].Country
   caseConfirm69.textContent = addCommaDecimal(data.Countries[69].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[69].NewConfirmed) +')'
   caseDeath69.textContent = addCommaDecimal(data.Countries[69].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[69].NewDeaths) +')'
   date69.textContent = new Date(data.Countries[69].Date).toString().substring(0,15)        
      const country70 = document.querySelector('.country70');
   const caseConfirm70 = document.querySelector('.CaseConfirm70');
   const caseDeath70 = document.querySelector('.CaseDeath70');
   const date70 = document.querySelector('.Date70');
   country70.textContent = data.Countries[70].Country
   caseConfirm70.textContent = addCommaDecimal(data.Countries[70].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[70].NewConfirmed) +')'
   caseDeath70.textContent = addCommaDecimal(data.Countries[70].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[70].NewDeaths) +')'
   date70.textContent = new Date(data.Countries[70].Date).toString().substring(0,15)
      const country71 = document.querySelector('.country71');
   const caseConfirm71 = document.querySelector('.CaseConfirm71');
   const caseDeath71 = document.querySelector('.CaseDeath71');
   const date71 = document.querySelector('.Date71');
   country71.textContent = data.Countries[71].Country
   caseConfirm71.textContent = addCommaDecimal(data.Countries[71].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[71].NewConfirmed) +')'
   caseDeath71.textContent = addCommaDecimal(data.Countries[71].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[71].NewDeaths) +')'
   date71.textContent = new Date(data.Countries[71].Date).toString().substring(0,15)
      const country72 = document.querySelector('.country72');
   const caseConfirm72 = document.querySelector('.CaseConfirm72');
   const caseDeath72 = document.querySelector('.CaseDeath72');
   const date72 = document.querySelector('.Date72');
   country72.textContent = data.Countries[72].Country
   caseConfirm72.textContent = addCommaDecimal(data.Countries[72].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[72].NewConfirmed) +')'
   caseDeath72.textContent = addCommaDecimal(data.Countries[72].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[72].NewDeaths) +')'
   date72.textContent = new Date(data.Countries[72].Date).toString().substring(0,15) 
      const country73 = document.querySelector('.country73');
   const caseConfirm73 = document.querySelector('.CaseConfirm73');
   const caseDeath73 = document.querySelector('.CaseDeath73');
   const date73 = document.querySelector('.Date73');
   country73.textContent = data.Countries[73].Country
   caseConfirm73.textContent = addCommaDecimal(data.Countries[73].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[73].NewConfirmed) +')'
   caseDeath73.textContent = addCommaDecimal(data.Countries[73].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[73].NewDeaths) +')'
   date73.textContent = new Date(data.Countries[73].Date).toString().substring(0,15)    
      const country74 = document.querySelector('.country74');
   const caseConfirm74 = document.querySelector('.CaseConfirm74');
   const caseDeath74 = document.querySelector('.CaseDeath74');
   const date74 = document.querySelector('.Date74');
   country74.textContent = data.Countries[74].Country
   caseConfirm74.textContent = addCommaDecimal(data.Countries[74].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[74].NewConfirmed) +')'
   caseDeath74.textContent = addCommaDecimal(data.Countries[74].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[74].NewDeaths) +')'
   date74.textContent = new Date(data.Countries[74].Date).toString().substring(0,15)    
      const country75 = document.querySelector('.country75');
   const caseConfirm75 = document.querySelector('.CaseConfirm75');
   const caseDeath75 = document.querySelector('.CaseDeath75');
   const date75 = document.querySelector('.Date75');
   country75.textContent = data.Countries[75].Country
   caseConfirm75.textContent = addCommaDecimal(data.Countries[75].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[75].NewConfirmed) +')'
   caseDeath75.textContent = addCommaDecimal(data.Countries[75].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[75].NewDeaths) +')'
   date75.textContent = new Date(data.Countries[75].Date).toString().substring(0,15)    
      const country76 = document.querySelector('.country76');
   const caseConfirm76 = document.querySelector('.CaseConfirm76');
   const caseDeath76 = document.querySelector('.CaseDeath76');
   const date76 = document.querySelector('.Date76');
   country76.textContent = data.Countries[76].Country
   caseConfirm76.textContent = addCommaDecimal(data.Countries[76].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[76].NewConfirmed) +')'
   caseDeath76.textContent = addCommaDecimal(data.Countries[76].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[76].NewDeaths) +')'
   date76.textContent = new Date(data.Countries[76].Date).toString().substring(0,15)  
      const country77 = document.querySelector('.country77');
   const caseConfirm77 = document.querySelector('.CaseConfirm77');
   const caseDeath77 = document.querySelector('.CaseDeath77');
   const date77 = document.querySelector('.Date77');
   country77.textContent = data.Countries[77].Country
   caseConfirm77.textContent = addCommaDecimal(data.Countries[77].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[77].NewConfirmed) +')'
   caseDeath77.textContent = addCommaDecimal(data.Countries[77].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[77].NewDeaths) +')'
   date77.textContent = new Date(data.Countries[77].Date).toString().substring(0,15)    
      const country78 = document.querySelector('.country78');
   const caseConfirm78 = document.querySelector('.CaseConfirm78');
   const caseDeath78 = document.querySelector('.CaseDeath78');
   const date78 = document.querySelector('.Date78');
   country78.textContent = data.Countries[78].Country
   caseConfirm78.textContent = addCommaDecimal(data.Countries[78].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[78].NewConfirmed) +')'
   caseDeath78.textContent = addCommaDecimal(data.Countries[78].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[78].NewDeaths) +')'
   date78.textContent = new Date(data.Countries[78].Date).toString().substring(0,15)    
      const country79 = document.querySelector('.country79');
   const caseConfirm79 = document.querySelector('.CaseConfirm79');
   const caseDeath79 = document.querySelector('.CaseDeath79');
   const date79 = document.querySelector('.Date79');
   country79.textContent = data.Countries[79].Country
   caseConfirm79.textContent = addCommaDecimal(data.Countries[79].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[79].NewConfirmed) +')'
   caseDeath79.textContent = addCommaDecimal(data.Countries[79].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[79].NewDeaths) +')'
   date79.textContent = new Date(data.Countries[79].Date).toString().substring(0,15)    
      const country80 = document.querySelector('.country80');
   const caseConfirm80 = document.querySelector('.CaseConfirm80');
   const caseDeath80 = document.querySelector('.CaseDeath80');
   const date80 = document.querySelector('.Date80');
   country80.textContent = data.Countries[80].Country
   caseConfirm80.textContent = addCommaDecimal(data.Countries[80].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[80].NewConfirmed) +')'
   caseDeath80.textContent = addCommaDecimal(data.Countries[80].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[80].NewDeaths) +')'
   date80.textContent = new Date(data.Countries[80].Date).toString().substring(0,15)
      const country81 = document.querySelector('.country81');
   const caseConfirm81 = document.querySelector('.CaseConfirm81');
   const caseDeath81 = document.querySelector('.CaseDeath81');
   const date81 = document.querySelector('.Date81');
   country81.textContent = data.Countries[81].Country
   caseConfirm81.textContent = addCommaDecimal(data.Countries[81].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[81].NewConfirmed) +')'
   caseDeath81.textContent = addCommaDecimal(data.Countries[81].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[81].NewDeaths) +')'
   date81.textContent = new Date(data.Countries[81].Date).toString().substring(0,15)
      const country82 = document.querySelector('.country82');
   const caseConfirm82 = document.querySelector('.CaseConfirm82');
   const caseDeath82 = document.querySelector('.CaseDeath82');
   const date82 = document.querySelector('.Date82');
   country82.textContent = data.Countries[82].Country
   caseConfirm82.textContent = addCommaDecimal(data.Countries[82].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[82].NewConfirmed) +')'
   caseDeath82.textContent = addCommaDecimal(data.Countries[82].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[82].NewDeaths) +')'
   date82.textContent = new Date(data.Countries[82].Date).toString().substring(0,15) 
      const country83 = document.querySelector('.country83');
   const caseConfirm83 = document.querySelector('.CaseConfirm83');
   const caseDeath83 = document.querySelector('.CaseDeath83');
   const date83 = document.querySelector('.Date83');
   country83.textContent = data.Countries[83].Country
   caseConfirm83.textContent = addCommaDecimal(data.Countries[83].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[83].NewConfirmed) +')'
   caseDeath83.textContent = addCommaDecimal(data.Countries[83].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[83].NewDeaths) +')'
   date83.textContent = new Date(data.Countries[83].Date).toString().substring(0,15)    
      const country84 = document.querySelector('.country84');
   const caseConfirm84 = document.querySelector('.CaseConfirm84');
   const caseDeath84 = document.querySelector('.CaseDeath84');
   const date84 = document.querySelector('.Date84');
   country84.textContent = data.Countries[84].Country
   caseConfirm84.textContent = addCommaDecimal(data.Countries[84].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[84].NewConfirmed) +')'
   caseDeath84.textContent = addCommaDecimal(data.Countries[84].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[84].NewDeaths) +')'
   date84.textContent = new Date(data.Countries[84].Date).toString().substring(0,15)    
      const country85 = document.querySelector('.country85');
   const caseConfirm85 = document.querySelector('.CaseConfirm85');
   const caseDeath85 = document.querySelector('.CaseDeath85');
   const date85 = document.querySelector('.Date85');
   country85.textContent = data.Countries[85].Country
   caseConfirm85.textContent = addCommaDecimal(data.Countries[85].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[85].NewConfirmed) +')'
   caseDeath85.textContent = addCommaDecimal(data.Countries[85].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[85].NewDeaths) +')'
   date85.textContent = new Date(data.Countries[85].Date).toString().substring(0,15)    
      const country86 = document.querySelector('.country86');
   const caseConfirm86 = document.querySelector('.CaseConfirm86');
   const caseDeath86 = document.querySelector('.CaseDeath86');
   const date86 = document.querySelector('.Date86');
   country86.textContent = data.Countries[86].Country
   caseConfirm86.textContent = addCommaDecimal(data.Countries[86].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[86].NewConfirmed) +')'
   caseDeath86.textContent = addCommaDecimal(data.Countries[86].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[86].NewDeaths) +')'
   date86.textContent = new Date(data.Countries[86].Date).toString().substring(0,15)  
      const country87 = document.querySelector('.country87');
   const caseConfirm87 = document.querySelector('.CaseConfirm87');
   const caseDeath87 = document.querySelector('.CaseDeath87');
   const date87 = document.querySelector('.Date87');
   country87.textContent = data.Countries[87].Country
   caseConfirm87.textContent = addCommaDecimal(data.Countries[87].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[87].NewConfirmed) +')'
   caseDeath87.textContent = addCommaDecimal(data.Countries[87].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[87].NewDeaths) +')'
   date87.textContent = new Date(data.Countries[87].Date).toString().substring(0,15)    
      const country88 = document.querySelector('.country88');
   const caseConfirm88 = document.querySelector('.CaseConfirm88');
   const caseDeath88 = document.querySelector('.CaseDeath88');
   const date88 = document.querySelector('.Date88');
   country88.textContent = data.Countries[88].Country
   caseConfirm88.textContent = addCommaDecimal(data.Countries[88].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[88].NewConfirmed) +')'
   caseDeath88.textContent = addCommaDecimal(data.Countries[88].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[88].NewDeaths) +')'
   date88.textContent = new Date(data.Countries[88].Date).toString().substring(0,15)    
      const country89 = document.querySelector('.country89');
   const caseConfirm89 = document.querySelector('.CaseConfirm89');
   const caseDeath89 = document.querySelector('.CaseDeath89');
   const date89 = document.querySelector('.Date89');
   country89.textContent = data.Countries[89].Country
   caseConfirm89.textContent = addCommaDecimal(data.Countries[89].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[89].NewConfirmed) +')'
   caseDeath89.textContent = addCommaDecimal(data.Countries[89].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[89].NewDeaths) +')'
   date89.textContent = new Date(data.Countries[89].Date).toString().substring(0,15)     
      const country90 = document.querySelector('.country90');
   const caseConfirm90 = document.querySelector('.CaseConfirm90');
   const caseDeath90 = document.querySelector('.CaseDeath90');
   const date90 = document.querySelector('.Date90');
   country90.textContent = data.Countries[90].Country
   caseConfirm90.textContent = addCommaDecimal(data.Countries[90].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[90].NewConfirmed) +')'
   caseDeath90.textContent = addCommaDecimal(data.Countries[90].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[90].NewDeaths) +')'
   date90.textContent = new Date(data.Countries[90].Date).toString().substring(0,15)
      const country91 = document.querySelector('.country91');
   const caseConfirm91 = document.querySelector('.CaseConfirm91');
   const caseDeath91 = document.querySelector('.CaseDeath91');
   const date91 = document.querySelector('.Date91');
   country91.textContent = data.Countries[91].Country
   caseConfirm91.textContent = addCommaDecimal(data.Countries[91].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[91].NewConfirmed) +')'
   caseDeath91.textContent = addCommaDecimal(data.Countries[91].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[91].NewDeaths) +')'
   date91.textContent = new Date(data.Countries[91].Date).toString().substring(0,15)
      const country92 = document.querySelector('.country92');
   const caseConfirm92 = document.querySelector('.CaseConfirm92');
   const caseDeath92 = document.querySelector('.CaseDeath92');
   const date92 = document.querySelector('.Date92');
   country92.textContent = data.Countries[92].Country
   caseConfirm92.textContent = addCommaDecimal(data.Countries[92].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[92].NewConfirmed) +')'
   caseDeath92.textContent = addCommaDecimal(data.Countries[92].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[92].NewDeaths) +')'
   date92.textContent = new Date(data.Countries[92].Date).toString().substring(0,15) 
      const country93 = document.querySelector('.country93');
   const caseConfirm93 = document.querySelector('.CaseConfirm93');
   const caseDeath93 = document.querySelector('.CaseDeath93');
   const date93 = document.querySelector('.Date93');
   country93.textContent = data.Countries[93].Country
   caseConfirm93.textContent = addCommaDecimal(data.Countries[93].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[93].NewConfirmed) +')'
   caseDeath93.textContent = addCommaDecimal(data.Countries[93].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[93].NewDeaths) +')'
   date93.textContent = new Date(data.Countries[93].Date).toString().substring(0,15)    
      const country94 = document.querySelector('.country94');
   const caseConfirm94 = document.querySelector('.CaseConfirm94');
   const caseDeath94 = document.querySelector('.CaseDeath94');
   const date94 = document.querySelector('.Date94');
   country94.textContent = data.Countries[94].Country
   caseConfirm94.textContent = addCommaDecimal(data.Countries[94].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[94].NewConfirmed) +')'
   caseDeath94.textContent = addCommaDecimal(data.Countries[94].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[94].NewDeaths) +')'
   date94.textContent = new Date(data.Countries[94].Date).toString().substring(0,15)    
      const country95 = document.querySelector('.country95');
   const caseConfirm95 = document.querySelector('.CaseConfirm95');
   const caseDeath95 = document.querySelector('.CaseDeath95');
   const date95 = document.querySelector('.Date95');
   country95.textContent = data.Countries[95].Country
   caseConfirm95.textContent = addCommaDecimal(data.Countries[95].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[95].NewConfirmed) +')'
   caseDeath95.textContent = addCommaDecimal(data.Countries[95].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[95].NewDeaths) +')'
   date95.textContent = new Date(data.Countries[95].Date).toString().substring(0,15)    
      const country96 = document.querySelector('.country96');
   const caseConfirm96 = document.querySelector('.CaseConfirm96');
   const caseDeath96 = document.querySelector('.CaseDeath96');
   const date96 = document.querySelector('.Date96');
   country96.textContent = data.Countries[96].Country
   caseConfirm96.textContent = addCommaDecimal(data.Countries[96].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[96].NewConfirmed) +')'
   caseDeath96.textContent = addCommaDecimal(data.Countries[96].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[96].NewDeaths) +')'
   date96.textContent = new Date(data.Countries[96].Date).toString().substring(0,15)  
      const country97 = document.querySelector('.country97');
   const caseConfirm97 = document.querySelector('.CaseConfirm97');
   const caseDeath97 = document.querySelector('.CaseDeath97');
   const date97 = document.querySelector('.Date97');
   country97.textContent = data.Countries[97].Country
   caseConfirm97.textContent = addCommaDecimal(data.Countries[97].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[97].NewConfirmed) +')'
   caseDeath97.textContent = addCommaDecimal(data.Countries[97].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[97].NewDeaths) +')'
   date97.textContent = new Date(data.Countries[97].Date).toString().substring(0,15)    
      const country98 = document.querySelector('.country98');
   const caseConfirm98 = document.querySelector('.CaseConfirm98');
   const caseDeath98 = document.querySelector('.CaseDeath98');
   const date98 = document.querySelector('.Date98');
   country98.textContent = data.Countries[98].Country
   caseConfirm98.textContent = addCommaDecimal(data.Countries[98].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[98].NewConfirmed) +')'
   caseDeath98.textContent = addCommaDecimal(data.Countries[98].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[98].NewDeaths) +')'
   date98.textContent = new Date(data.Countries[98].Date).toString().substring(0,15)    
      const country99 = document.querySelector('.country99');
   const caseConfirm99 = document.querySelector('.CaseConfirm99');
   const caseDeath99 = document.querySelector('.CaseDeath99');
   const date99 = document.querySelector('.Date99');
   country99.textContent = data.Countries[99].Country
   caseConfirm99.textContent = addCommaDecimal(data.Countries[99].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[99].NewConfirmed) +')'
   caseDeath99.textContent = addCommaDecimal(data.Countries[99].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[99].NewDeaths) +')'
   date99.textContent = new Date(data.Countries[99].Date).toString().substring(0,15)      
      const country100 = document.querySelector('.country100');
   const caseConfirm100 = document.querySelector('.CaseConfirm100');
   const caseDeath100 = document.querySelector('.CaseDeath100');
   const date100 = document.querySelector('.Date100');
   country100.textContent = data.Countries[100].Country
   caseConfirm100.textContent = addCommaDecimal(data.Countries[100].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[100].NewConfirmed) +')'
   caseDeath100.textContent = addCommaDecimal(data.Countries[100].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[100].NewDeaths) +')'
   date100.textContent = new Date(data.Countries[100].Date).toString().substring(0,15)
      const country101 = document.querySelector('.country101');
   const caseConfirm101 = document.querySelector('.CaseConfirm101');
   const caseDeath101 = document.querySelector('.CaseDeath101');
   const date101 = document.querySelector('.Date101');
   country101.textContent = data.Countries[101].Country
   caseConfirm101.textContent = addCommaDecimal(data.Countries[101].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[101].NewConfirmed) +')'
   caseDeath101.textContent = addCommaDecimal(data.Countries[101].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[101].NewDeaths) +')'
   date101.textContent = new Date(data.Countries[101].Date).toString().substring(0,15)
      const country102 = document.querySelector('.country102');
   const caseConfirm102 = document.querySelector('.CaseConfirm102');
   const caseDeath102 = document.querySelector('.CaseDeath102');
   const date102 = document.querySelector('.Date102');
   country102.textContent = data.Countries[102].Country
   caseConfirm102.textContent = addCommaDecimal(data.Countries[102].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[102].NewConfirmed) +')'
   caseDeath102.textContent = addCommaDecimal(data.Countries[102].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[102].NewDeaths) +')'
   date102.textContent = new Date(data.Countries[102].Date).toString().substring(0,15) 
      const country103 = document.querySelector('.country103');
   const caseConfirm103 = document.querySelector('.CaseConfirm103');
   const caseDeath103 = document.querySelector('.CaseDeath103');
   const date103 = document.querySelector('.Date103');
   country103.textContent = data.Countries[103].Country
   caseConfirm103.textContent = addCommaDecimal(data.Countries[103].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[103].NewConfirmed) +')'
   caseDeath103.textContent = addCommaDecimal(data.Countries[103].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[103].NewDeaths) +')'
   date103.textContent = new Date(data.Countries[103].Date).toString().substring(0,15)    
      const country104 = document.querySelector('.country104');
   const caseConfirm104 = document.querySelector('.CaseConfirm104');
   const caseDeath104 = document.querySelector('.CaseDeath104');
   const date104 = document.querySelector('.Date104');
   country104.textContent = data.Countries[104].Country
   caseConfirm104.textContent = addCommaDecimal(data.Countries[104].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[104].NewConfirmed) +')'
   caseDeath104.textContent = addCommaDecimal(data.Countries[104].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[104].NewDeaths) +')'
   date104.textContent = new Date(data.Countries[104].Date).toString().substring(0,15)    
      const country105 = document.querySelector('.country105');
   const caseConfirm105 = document.querySelector('.CaseConfirm105');
   const caseDeath105 = document.querySelector('.CaseDeath105');
   const date105 = document.querySelector('.Date105');
   country105.textContent = data.Countries[105].Country
   caseConfirm105.textContent = addCommaDecimal(data.Countries[105].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[105].NewConfirmed) +')'
   caseDeath105.textContent = addCommaDecimal(data.Countries[105].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[105].NewDeaths) +')'
   date105.textContent = new Date(data.Countries[105].Date).toString().substring(0,15)    
      const country106 = document.querySelector('.country106');
   const caseConfirm106 = document.querySelector('.CaseConfirm106');
   const caseDeath106 = document.querySelector('.CaseDeath106');
   const date106 = document.querySelector('.Date106');
   country106.textContent = data.Countries[106].Country
   caseConfirm106.textContent = addCommaDecimal(data.Countries[106].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[106].NewConfirmed) +')'
   caseDeath106.textContent = addCommaDecimal(data.Countries[106].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[106].NewDeaths) +')'
   date106.textContent = new Date(data.Countries[106].Date).toString().substring(0,15)  
      const country107 = document.querySelector('.country107');
   const caseConfirm107 = document.querySelector('.CaseConfirm107');
   const caseDeath107 = document.querySelector('.CaseDeath107');
   const date107 = document.querySelector('.Date107');
   country107.textContent = data.Countries[107].Country
   caseConfirm107.textContent = addCommaDecimal(data.Countries[107].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[107].NewConfirmed) +')'
   caseDeath107.textContent = addCommaDecimal(data.Countries[107].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[107].NewDeaths) +')'
   date107.textContent = new Date(data.Countries[107].Date).toString().substring(0,15)    
      const country108 = document.querySelector('.country108');
   const caseConfirm108 = document.querySelector('.CaseConfirm108');
   const caseDeath108 = document.querySelector('.CaseDeath108');
   const date108 = document.querySelector('.Date108');
   country108.textContent = data.Countries[108].Country
   caseConfirm108.textContent = addCommaDecimal(data.Countries[108].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[108].NewConfirmed) +')'
   caseDeath108.textContent = addCommaDecimal(data.Countries[108].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[108].NewDeaths) +')'
   date108.textContent = new Date(data.Countries[108].Date).toString().substring(0,15)    
      const country109 = document.querySelector('.country109');
   const caseConfirm109 = document.querySelector('.CaseConfirm109');
   const caseDeath109 = document.querySelector('.CaseDeath109');
   const date109 = document.querySelector('.Date109');
   country109.textContent = data.Countries[109].Country
   caseConfirm109.textContent = addCommaDecimal(data.Countries[109].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[109].NewConfirmed) +')'
   caseDeath109.textContent = addCommaDecimal(data.Countries[109].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[109].NewDeaths) +')'
   date109.textContent = new Date(data.Countries[109].Date).toString().substring(0,15)      
      const country110 = document.querySelector('.country110');
   const caseConfirm110 = document.querySelector('.CaseConfirm110');
   const caseDeath110 = document.querySelector('.CaseDeath110');
   const date110 = document.querySelector('.Date110');
   country110.textContent = data.Countries[110].Country
   caseConfirm110.textContent = addCommaDecimal(data.Countries[110].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[110].NewConfirmed) +')'
   caseDeath110.textContent = addCommaDecimal(data.Countries[110].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[110].NewDeaths) +')'
   date110.textContent = new Date(data.Countries[110].Date).toString().substring(0,15)
      const country111 = document.querySelector('.country111');
   const caseConfirm111 = document.querySelector('.CaseConfirm111');
   const caseDeath111 = document.querySelector('.CaseDeath111');
   const date111 = document.querySelector('.Date111');
   country111.textContent = data.Countries[111].Country
   caseConfirm111.textContent = addCommaDecimal(data.Countries[111].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[111].NewConfirmed) +')'
   caseDeath111.textContent = addCommaDecimal(data.Countries[111].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[111].NewDeaths) +')'
   date111.textContent = new Date(data.Countries[111].Date).toString().substring(0,15)
      const country112 = document.querySelector('.country112');
   const caseConfirm112 = document.querySelector('.CaseConfirm112');
   const caseDeath112 = document.querySelector('.CaseDeath112');
   const date112 = document.querySelector('.Date112');
   country112.textContent = data.Countries[112].Country
   caseConfirm112.textContent = addCommaDecimal(data.Countries[112].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[112].NewConfirmed) +')'
   caseDeath112.textContent = addCommaDecimal(data.Countries[112].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[112].NewDeaths) +')'
   date112.textContent = new Date(data.Countries[112].Date).toString().substring(0,15) 
      const country113 = document.querySelector('.country113');
   const caseConfirm113 = document.querySelector('.CaseConfirm113');
   const caseDeath113 = document.querySelector('.CaseDeath113');
   const date113 = document.querySelector('.Date113');
   country113.textContent = data.Countries[113].Country
   caseConfirm113.textContent = addCommaDecimal(data.Countries[113].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[113].NewConfirmed) +')'
   caseDeath113.textContent = addCommaDecimal(data.Countries[113].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[113].NewDeaths) +')'
   date113.textContent = new Date(data.Countries[113].Date).toString().substring(0,15)    
      const country114 = document.querySelector('.country114');
   const caseConfirm114 = document.querySelector('.CaseConfirm114');
   const caseDeath114 = document.querySelector('.CaseDeath114');
   const date114 = document.querySelector('.Date114');
   country114.textContent = data.Countries[114].Country
   caseConfirm114.textContent = addCommaDecimal(data.Countries[114].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[114].NewConfirmed) +')'
   caseDeath114.textContent = addCommaDecimal(data.Countries[114].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[114].NewDeaths) +')'
   date114.textContent = new Date(data.Countries[114].Date).toString().substring(0,15)    
      const country115 = document.querySelector('.country115');
   const caseConfirm115 = document.querySelector('.CaseConfirm115');
   const caseDeath115 = document.querySelector('.CaseDeath115');
   const date115 = document.querySelector('.Date115');
   country115.textContent = data.Countries[115].Country
   caseConfirm115.textContent = addCommaDecimal(data.Countries[115].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[115].NewConfirmed) +')'
   caseDeath115.textContent = addCommaDecimal(data.Countries[115].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[115].NewDeaths) +')'
   date115.textContent = new Date(data.Countries[115].Date).toString().substring(0,15)    
      const country116 = document.querySelector('.country116');
   const caseConfirm116 = document.querySelector('.CaseConfirm116');
   const caseDeath116 = document.querySelector('.CaseDeath116');
   const date116 = document.querySelector('.Date116');
   country116.textContent = data.Countries[116].Country
   caseConfirm116.textContent = addCommaDecimal(data.Countries[116].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[116].NewConfirmed) +')'
   caseDeath116.textContent = addCommaDecimal(data.Countries[116].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[116].NewDeaths) +')'
   date116.textContent = new Date(data.Countries[116].Date).toString().substring(0,15)  
      const country117 = document.querySelector('.country117');
   const caseConfirm117 = document.querySelector('.CaseConfirm117');
   const caseDeath117 = document.querySelector('.CaseDeath117');
   const date117 = document.querySelector('.Date117');
   country117.textContent = data.Countries[117].Country
   caseConfirm117.textContent = addCommaDecimal(data.Countries[117].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[117].NewConfirmed) +')'
   caseDeath117.textContent = addCommaDecimal(data.Countries[117].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[117].NewDeaths) +')'
   date117.textContent = new Date(data.Countries[117].Date).toString().substring(0,15)    
      const country118 = document.querySelector('.country118');
   const caseConfirm118 = document.querySelector('.CaseConfirm118');
   const caseDeath118 = document.querySelector('.CaseDeath118');
   const date118 = document.querySelector('.Date118');
   country118.textContent = data.Countries[118].Country
   caseConfirm118.textContent = addCommaDecimal(data.Countries[118].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[118].NewConfirmed) +')'
   caseDeath118.textContent = addCommaDecimal(data.Countries[118].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[118].NewDeaths) +')'
   date118.textContent = new Date(data.Countries[118].Date).toString().substring(0,15)    
      const country119 = document.querySelector('.country119');
   const caseConfirm119 = document.querySelector('.CaseConfirm119');
   const caseDeath119 = document.querySelector('.CaseDeath119');
   const date119 = document.querySelector('.Date119');
   country119.textContent = data.Countries[119].Country
   caseConfirm109.textContent = addCommaDecimal(data.Countries[119].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[119].NewConfirmed) +')'
   caseDeath109.textContent = addCommaDecimal(data.Countries[119].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[119].NewDeaths) +')'
   date109.textContent = new Date(data.Countries[119].Date).toString().substring(0,15)    
      const country120 = document.querySelector('.country120');
   const caseConfirm120 = document.querySelector('.CaseConfirm120');
   const caseDeath120 = document.querySelector('.CaseDeath120');
   const date120 = document.querySelector('.Date120');
   country120.textContent = data.Countries[120].Country
   caseConfirm120.textContent = addCommaDecimal(data.Countries[120].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[120].NewConfirmed) +')'
   caseDeath120.textContent = addCommaDecimal(data.Countries[120].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[120].NewDeaths) +')'
   date120.textContent = new Date(data.Countries[120].Date).toString().substring(0,15) 
      const country130 = document.querySelector('.country130');
   const caseConfirm130 = document.querySelector('.CaseConfirm130');
   const caseDeath130 = document.querySelector('.CaseDeath130');
   const date130 = document.querySelector('.Date130');
   country130.textContent = data.Countries[130].Country
   caseConfirm130.textContent = addCommaDecimal(data.Countries[130].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[130].NewConfirmed) +')'
   caseDeath130.textContent = addCommaDecimal(data.Countries[130].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[130].NewDeaths) +')'
   date130.textContent = new Date(data.Countries[130].Date).toString().substring(0,15) 
      const country140 = document.querySelector('.country140');
   const caseConfirm140 = document.querySelector('.CaseConfirm140');
   const caseDeath140 = document.querySelector('.CaseDeath140');
   const date140 = document.querySelector('.Date140');
   country140.textContent = data.Countries[140].Country
   caseConfirm140.textContent = addCommaDecimal(data.Countries[140].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[140].NewConfirmed) +')'
   caseDeath140.textContent = addCommaDecimal(data.Countries[140].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[140].NewDeaths) +')'
   date140.textContent = new Date(data.Countries[140].Date).toString().substring(0,15) 
      const country150 = document.querySelector('.country150');
   const caseConfirm150 = document.querySelector('.CaseConfirm150');
   const caseDeath150 = document.querySelector('.CaseDeath150');
   const date150 = document.querySelector('.Date150');
   country150.textContent = data.Countries[150].Country
   caseConfirm150.textContent = addCommaDecimal(data.Countries[150].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[150].NewConfirmed) +')'
   caseDeath150.textContent = addCommaDecimal(data.Countries[150].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[150].NewDeaths) +')'
   date150.textContent = new Date(data.Countries[150].Date).toString().substring(0,15)    
       const country160 = document.querySelector('.country160');
   const caseConfirm160 = document.querySelector('.CaseConfirm160');
   const caseDeath160 = document.querySelector('.CaseDeath160');
   const date160 = document.querySelector('.Date160');
   country160.textContent = data.Countries[160].Country
   caseConfirm160.textContent = addCommaDecimal(data.Countries[160].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[160].NewConfirmed) +')'
   caseDeath160.textContent = addCommaDecimal(data.Countries[160].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[160].NewDeaths) +')'
   date160.textContent = new Date(data.Countries[160].Date).toString().substring(0,15) 
      const country170 = document.querySelector('.country170');
   const caseConfirm170 = document.querySelector('.CaseConfirm170');
   const caseDeath170 = document.querySelector('.CaseDeath170');
   const date170 = document.querySelector('.Date170');
   country170.textContent = data.Countries[170].Country
   caseConfirm170.textContent = addCommaDecimal(data.Countries[170].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[170].NewConfirmed) +')'
   caseDeath170.textContent = addCommaDecimal(data.Countries[170].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[170].NewDeaths) +')'
   date170.textContent = new Date(data.Countries[170].Date).toString().substring(0,15)  
      const country180 = document.querySelector('.country180');
   const caseConfirm180 = document.querySelector('.CaseConfirm180');
   const caseDeath180 = document.querySelector('.CaseDeath180');
   const date180 = document.querySelector('.Date180');
   country180.textContent = data.Countries[180].Country
   caseConfirm180.textContent = addCommaDecimal(data.Countries[180].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[180].NewConfirmed) +')'
   caseDeath180.textContent = addCommaDecimal(data.Countries[180].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[180].NewDeaths) +')'
   date180.textContent = new Date(data.Countries[180].Date).toString().substring(0,15)     
    
    
   const country190 = document.querySelector('.country190');
   const caseConfirm190 = document.querySelector('.CaseConfirm190');
   const caseDeath190 = document.querySelector('.CaseDeath190');
   const date190 = document.querySelector('.Date190');
   country190.textContent = data.Countries[190].Country
   caseConfirm190.textContent = addCommaDecimal(data.Countries[190].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[190].NewConfirmed) +')'
   caseDeath190.textContent = addCommaDecimal(data.Countries[190].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[190].NewDeaths) +')'
   date190.textContent = new Date(data.Countries[190].Date).toString().substring(0,15) 
   const country191 = document.querySelector('.country191');
   const caseConfirm191 = document.querySelector('.CaseConfirm191');
   const caseDeath191 = document.querySelector('.CaseDeath191');
   const date191 = document.querySelector('.Date191');
   country191.textContent = data.Countries[191].Country
   caseConfirm191.textContent = addCommaDecimal(data.Countries[191].TotalConfirmed) + ' (' + addCommaDecimal(data.Countries[191].NewConfirmed) +')'
   caseDeath191.textContent = addCommaDecimal(data.Countries[191].TotalDeaths) + ' (' + addCommaDecimal(data.Countries[191].NewDeaths) +')'
   date191.textContent = new Date(data.Countries[191].Date).toString().substring(0,15)    
  });
}

getCountryCountFromCovidApi();

(async function() {
  let urlList = [
    "https://api.covidtracking.com/v1/us/current.json",
    "https://api.covidtracking.com/v1/states/current.json"
  ];

  const promiseList = urlList.map((url) => {
    return fetch(url)
        .then(response => response.json())
  })

  const jsonBaseList = await Promise.all(promiseList)
  console.log('All done.');
  console.log('jsonBaseList: ', jsonBaseList)
})()

//Global Functions    
   function getArrayFields(input, field) {
      const output = [];
      for (var i=0; i < input.length ; ++i)
        output.push(input[i][field]);
      return output;
   }

   function addDateComma(dateinput) {
      let p = dateinput.toString()
      let d = p.substring(0,4) + ',' + p.substring(4,6) + ',' + p.substring(6,8)
      return d
   }

/* function addComma(input) {
      let result;
      let d = input.toString().length;
      if ((input.toString().length > 3 && input.toString().length < 7)) {
         result = input.toString().slice(0,d-3) + ',' + input.toString().slice(d-3,d);
      } else if ((input.toString().length >= 7 && input.toString().length < 10)) {
         result = input.toString().slice(0,d-6) + ',' + input.toString().slice(d-6,d-3) + ',' + input.toString().slice(d-3,d);
      } else if ((input.toString().length >= 10 && input.toString().length < 13)) {
         result = input.toString().slice(0,d-9) + ',' + input.toString().slice(d-9,d-6) + ',' + input.toString().slice(d-6,d-3) + ',' + input.toString().slice(d-3,d);
      } else {
         result = input;
      }
      return result;
    } */

function addCommaDecimal(x) {
    if (x == undefined || x == null) {
      return x = "Error";
    } else {
      return x.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",");
    }   
}

const determineNull = input => input == undefined ? input = "NA" : input;
