'use strict';

const e = React.createElement;

class Hello extends React.Component {
  render() {
    return e("div", null,
    e("div", {class: "efd"}, "Hello ", this.props.toWhat),
    e("a", {target: "_blank", href: `${this.props.email}`}, "email"), 
    e("a", {href: 'http://google.com'}, "Google"), 
    e("div", null, "Hello ", this.props.toName));
  }
}

class HelloList extends React.Component {
  render() {
    return e("div", null,
    e(Hello, {toWhat: "World", toName: "Ted", email: "http://www.youtube.com"}),
    e(Hello, {toWhat: "The", toName: "Ktle", email: "http://www.github.com"})
    )
  }
}

/*ReactDOM.render( 
  //e(Hello, {toWhat: "World", toName: "Ted", email: "http://www.youtube.com"}),
  e(HelloList),            
  document.querySelector('#article-main-june2021')
);


React.createElement(Link, {
  to: "/Path"
}, " Contact us ");

https://www.frontiersin.org/articles/10.3389/fimmu.2021.700782/abstract

https://reactjs.org/docs/react-without-jsx.html */

function Welcome(props) {
  return e("h1", null, "Hello, ", props.name);
}

class App extends React.Component {
 render() {
    return e("div", null, e(Welcome, {name: "Sara"}),
         e(Welcome, {name: "Cahal"}),
         e(Welcome, {name: "Edite"})); 
 }
}

class NewsList extends React.Component {
  render() {
    return e("div", {class: "article-container"},
    e("div", {class: "news-box news-box-a"},
    e("i", {class: "fas fa-exclamation-circle fa-2x"}, this.props.newsType),
    e("h3", null, this.props.newsTitle), 
    e("p", {class: "price"}, "Source: ", this.props.newsSource, ", Published on ", this.props.newsDate), 
    e("a", {target: "_blank", href: `${this.props.newsLink}`, class: "btn"}, "Link to Article")),  
    e("div", {class: "news-box news-box-b"}, 
    e("img", {src: "img/coronavirus-19-mobile.jpg",alt: "COVID-19 News Image"
    }))
    );
  }
}

class MarchNewsApp extends React.Component {
 render() {
      return e("div", null, 
         e(NewsList, {newsType: "Non Media News", newsTitle: "Factors associated with myocardial SARS-CoV-2 infection, myocarditis, and cardiac inflammation in patients with COVID-19", newsSource: "Nature", newsDate: "March 17, 2021", newsLink: "https://doi.org/10.1038/s41379-021-00790-1"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Essentials in saline pharmacology for nasal or respiratory hygiene in times of COVID-19", newsSource: "Springer", newsDate: "March 27, 2021", newsLink: "https://doi.org/10.1007/s00228-021-03102-3"})      
         ); 
 }
}  

class MayNewsApp extends React.Component {
 render() {
      return e("div", null, 
         e(NewsList, {newsType: "Non Media News", newsTitle: "Discovery of Novel Coronaviruses in Rodents", newsSource: "US National Library of Medicine", newsDate: "May 11, 2020", newsLink: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7980831/"}),      
         e(NewsList, {newsType: "Non Media News", newsTitle: "SARS-CoV-2 simulations go exascale to predict dramatic spike opening and cryptic pockets across the proteome", newsSource: "Nature", newsDate: "May 24, 2021", newsLink: "https://doi.org/10.1038/s41557-021-00707-0"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Boredom proneness, political orientation and adherence to social-distancing in the pandemic", newsSource: "Springer", newsDate: "May 25, 2021", newsLink: "https://doi.org/10.1007/s11031-021-09888-0"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "The Covid-19 Lab Leak Theory Is a Tale of Weaponized Uncertainty", newsSource: "Wired", newsDate: "May 28, 2021", newsLink: "https://www.wired.com/story/covid-19-lab-leak-theory-weaponized-uncertainty/"})      
         ); 
 }
}  

class JulyNewsApp extends React.Component {
 render() {
      return e("div", null, 
         e(NewsList, {newsType: "Media News", newsTitle: "Artificial Proteins Never Seen in the Natural World Are Becoming New COVID Vaccines and Medicines", newsSource: "Scientific American", newsDate: "July 1, 2021", newsLink: "https://www.scientificamerican.com/article/artificial-proteins-never-seen-in-the-natural-world-are-becoming-new-covid-vaccines-and-medicines/"})      
         ); 
 }
}  


class NewsApp extends React.Component {
 render() {
    return e("div", null,
         e(NewsList, {newsType: "Non Media News", newsTitle: "In-hospital use of statins is associated with a reduced risk of mortality in coronavirus-2019 (COVID-19): systematic review and meta-analysis", newsSource: "Springer", newsDate: "February 20, 2021", newsLink: "https://doi.org/10.1007/s43440-021-00233-3"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Children with long covid", newsSource: "US National Library of Medicine", newsDate: "February 27, 2021", newsLink: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7927578/"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Reverse-transcribed SARS-CoV-2 RNA can integrate into the genome of cultured human cells and can be expressed in patient-derived tissues", newsSource: "PNAS", newsDate: "May 25, 2021", newsLink: "https://doi.org/10.1073/pnas.2105968118"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Count the cost of disability caused by COVID-19", newsSource: "Nature", newsDate: "May 26, 2021", newsLink: "https://doi.org/10.1038/d41586-021-01392-2"}),    
         e(NewsList, {newsType: "Non Media News", newsTitle: "CRISPR diagnostics", newsSource: "Science Magazine", newsDate: "May 28, 2021", newsLink: "https://doi.org/10.1126/science.abi9335"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Lipid metabolism changes in patients with severe COVID-19", newsSource: "Science Direct", newsDate: "June, 2021", newsLink: "https://doi.org/10.1016/j.cca.2021.02.011"}),    
         e(NewsList, {newsType: "Non Media News", newsTitle: "HIV-1 and SARS-CoV-2: Patterns in the Evolution of Two Pandemic Pathogens", newsSource: "Cell", newsDate: "June 2, 2021", newsLink: "https://doi.org/10.1016/j.chom.2021.05.012"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Surface Proteins of SARS-CoV-2 Drive Airway Epithelial Cells to Induce IFN-Dependent Inflammation", newsSource: "Journal of Immunology", newsDate: "June 2, 2021", newsLink: "https://doi.org/10.4049/jimmunol.2001407 "}), 
         e(NewsList, {newsType: "Non Media News", newsTitle: "Proteomic Analysis Identifies Prolonged Disturbances in Pathways Related to Cholesterol Metabolism and Myocardium Function in the COVID-19 Recovery Stage", newsSource: "ACS Publications", newsDate: "June 3, 2021", newsLink: "https://doi.org/10.1021/acs.jproteome.1c00054"}),    
         e(NewsList, {newsType: "Non Media News", newsTitle: "SARS-CoV-2 proteins and anti-COVID-19 drugs induce lytic reactivation of an oncogenic virus", newsSource: "Nature", newsDate: "June 3, 2021", newsLink: "https://doi.org/10.1038/s42003-021-02220-z"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Six months of COVID vaccines: what 1.7 billion doses have taught scientists", newsSource: "Nature", newsDate: "June 4, 2021", newsLink: "https://doi.org/10.1038/d41586-021-01505-x"}),    
         e(NewsList, {newsType: "Non Media News", newsTitle: "Therapeutic versus prophylactic anticoagulation for patients admitted to hospital with COVID-19 and elevated D-dimer concentration (ACTION): an open-label, multicentre, randomised, controlled trial", newsSource: "Lancet", newsDate: "June 4, 2021", newsLink: "https://doi.org/10.1016/S0140-6736(21)01203-4"}), 
         e(NewsList, {newsType: "Non Media News", newsTitle: "Open science saves lives: lessons from the COVID-19 pandemic", newsSource: "BioMedCentral", newsDate: "June 5, 2021", newsLink: "https://doi.org/10.1186/s12874-021-01304-y"}), 
         e(NewsList, {newsType: "Media News", newsTitle: "The ‘two societies’: 97% of new COVID cases are among people who haven’t gotten the shots ", newsSource: "Seattle Times", newsDate: "June 5, 2021", newsLink: "https://www.seattletimes.com/seattle-news/health/the-two-societies-97-of-new-covid-cases-are-among-people-who-havent-gotten-the-shots/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "How Virginia Improved Vaccination Rates Among Latinx Residents", newsSource: "NPR", newsDate: "June 6, 2021", newsLink: "https://www.npr.org/2021/06/06/1003713835/how-virginia-improved-vaccination-rates-among-latinx-residents"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Ivermectin and outcomes from Covid-19 pneumonia: A systematic review and meta-analysis of randomized clinical trial studies", newsSource: "Wiley Online Library", newsDate: "June 6, 2021", newsLink: "https://doi.org/10.1002/rmv.2265"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Anti-lockdown march in Montreal draws several thousand protesters", newsSource: "Montreal Gazette", newsDate: "June 6, 2021", newsLink: "https://montrealgazette.com/news/local-news/anti-lockdown-march-in-montreal-draws-several-thousand-protesters"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "Vaccination rates fall off, imperiling Biden’s July Fourth goal", newsSource: "Washington Post", newsDate: "June 6, 2021", newsLink: "https://www.washingtonpost.com/health/2021/06/06/vaccination-rates-decline-us/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Children are ‘vulnerable host’ for Covid as cases recede, US expert warns", newsSource: "Guardian", newsDate: "June 7, 2021", newsLink: "https://www.theguardian.com/world/2021/jun/07/children-covid-vulnerable-host-cases-recede-us"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "India to provide free vaccines to all in major policy shift", newsSource: "AP News", newsDate: "June 7, 2021", newsLink: "https://apnews.com/article/india-lifestyle-coronavirus-pandemic-business-health-914d95c368553f08f0d4d307d797a078"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Major Chinese city battles Delta Covid variant first detected in India with lockdowns, mass testing", newsSource: "CNBC", newsDate: "June 7,201", newsLink: "https://www.cnbc.com/2021/06/07/china-guangzhou-delta-covid-variant.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Spat at, abused, attacked: healthcare staff face rising violence during Covid", newsSource: "Guardian", newsDate: "June 7,201", newsLink: "https://www.theguardian.com/global-development/2021/jun/07/spat-at-abused-attacked-healthcare-staff-face-rising-violence-during-covid"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Dr. Gottlieb: Fully vaccinated people should feel safe this summer but fall booster may be needed", newsSource: "CNBC", newsDate: "June 7,201", newsLink: "https://www.cnbc.com/2021/06/07/dr-scott-gottlieb-says-covid-booster-shot-may-still-be-needed-in-fall.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "A victim of its own success: how Taiwan failed to plan for a major Covid outbreak", newsSource: "Guardian", newsDate: "June 7, 2021", newsLink: "https://www.theguardian.com/world/2021/jun/07/a-victim-of-its-own-success-how-taiwan-failed-to-plan-for-a-major-covid-outbreak"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Most COVID Rules End When 70% of NY Adults Have 1 Dose, Schools Keep Masks Indoors", newsSource: "NBC New York", newsDate: "June 7, 2021", newsLink: "https://www.nbcnewyork.com/news/coronavirus/in-about-face-ny-delays-universal-end-to-school-face-mask-mandate/3093133/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Scientists begin to unravel the mysteries of the coronavirus and brains", newsSource: "Washington Post", newsDate: "June 7, 2021", newsLink: "https://www.washingtonpost.com/health/2021/06/07/covid-are-brains-affected/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Gov. Greg Abbott signs bill to punish businesses that require proof of COVID-19 vaccination", newsSource: "Texas Tribune", newsDate: "June 7, 2021", newsLink: "https://www.texastribune.org/2021/06/07/texas-vaccine-passports-covid-19/"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Spread of Misinformation About Face Masks and COVID-19 by Automated Software on Facebook", newsSource: "Jama Network", newsDate: "June 7,201", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamainternmed.2021.2498"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Nanobodies from camelid mice and llamas neutralize SARS-CoV-2 variants", newsSource: "Nature", newsDate: "June 7,201", newsLink: "https://doi.org/10.1038/s41586-021-03676-z"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "SARS-CoV-2 RNAemia and proteomic trajectories inform prognostication in COVID-19 patients admitted to intensive care", newsSource: "Nature", newsDate: "June 7, 2021", newsLink: "https://doi.org/10.1038/s41467-021-23494-1"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Increased platelet activation in SARS-CoV-2 infected non-hospitalised children and adults, and their household contacts", newsSource: "Wiley Online Library", newsDate: "June 7, 2021", newsLink: "https://doi.org/10.1111/bjh.17629"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Calcifediol treatment and COVID-19-related outcomes", newsSource: "Oxford Academics", newsDate: "June 7, 2021", newsLink: "https://doi.org/10.1210/clinem/dgab405"}),             
         e(NewsList, {newsType: "Media News", newsTitle: "Gangrene, Hearing Loss Show Delta Variant May Be More Severe", newsSource: "Bloomberg", newsDate: "June 7, 2021", newsLink: "https://www.bloomberg.com/news/articles/2021-06-07/gangrene-hearing-loss-point-to-delta-variant-being-more-severe"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "RECOVERY trial finds aspirin does not improve survival for patients hospitalised with COVID-19", newsSource: "Recovery", newsDate: "June 8, 2021", newsLink: "https://www.recoverytrial.net/news/recovery-trial-finds-aspirin-does-not-improve-survival-for-patients-hospitalised-with-covid-19"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "A versatile reverse genetics platform for SARS-CoV-2 and other positive-strand RNA viruses", newsSource: "Nature", newsDate: "June 8, 2021", newsLink: "https://doi.org/10.1038/s41467-021-23779-5"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "EU regulator does not expect approval for CureVac vaccine before August", newsSource: "Reuters", newsDate: "June 8, 2021", newsLink: "https://www.reuters.com/business/healthcare-pharmaceuticals/eu-regulator-does-not-expect-approval-curevac-vaccine-before-august-source-2021-06-08/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "EU regulator to give verdict on Moderna COVID-19 shot for teens in July", newsSource: "Euro News", newsDate: "June 8, 2021", newsLink: "https://www.euronews.com/2021/06/08/us-health-coronavirus-moderna-ema"}),
         e(NewsList, {newsType: "Media News", newsTitle: "'Breakthrough' COVID Infections May Be Common in Vaccinated Transplant Patients", newsSource: "US News", newsDate: "June 8, 2021", newsLink: "https://www.usnews.com/news/health-news/articles/2021-06-08/breakthrough-covid-infections-may-be-common-in-vaccinated-transplant-patients"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "Anti-Vaccine Film Targeted To Black Americans Spreads False Information", newsSource: "NPR", newsDate: "June 8, 2021", newsLink: "https://www.npr.org/sections/health-shots/2021/06/08/1004214189/anti-vaccine-film-targeted-to-black-americans-spreads-false-information"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Fauci says U.S. must vaccinate more people before Delta becomes dominant Covid variant in America", newsSource: "CNBC", newsDate: "June 8, 2021", newsLink: "https://www.cnbc.com/2021/06/08/fauci-says-us-must-vaccinate-more-people-before-delta-becomes-dominant-covid-variant-in-america.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Pfizer to test COVID-19 vaccine in larger group of children below 12", newsSource: "Reuters", newsDate: "June 8, 2021", newsLink: "https://www.reuters.com/business/healthcare-pharmaceuticals/pfizer-start-large-study-test-covid-19-vaccine-children-below-12-2021-06-08/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "US increasingly unlikely to meet Biden’s July 4 vax goal", newsSource: "AP News", newsDate: "June 8, 2021", newsLink: "https://apnews.com/article/us-news-coronavirus-pandemic-health-government-and-politics-e8ca280afabb5040c21e13201cd82dda"}),
         e(NewsList, {newsType: "Media News", newsTitle: "The Highly Contagious Delta Variant Is On The Rise In The U.S.", newsSource: "NPR", newsDate: "June 8, 2021", newsLink: "https://www.npr.org/sections/coronavirus-live-updates/2021/06/08/1004597294/the-highly-contagious-delta-variant-of-covid-is-on-the-rise-in-the-u-s"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Definition and validation of serum biomarkers for optimal differentiation of hyperferritinaemic cytokine storm conditions in children: a retrospective cohort study", newsSource: "Lancet", newsDate: "June 8, 2021", newsLink: "https://doi.org/10.1016/S2665-9913(21)00115-6"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Inflammatory biomarkers in COVID-19-associated multisystem inflammatory syndrome in children, Kawasaki disease, and macrophage activation syndrome: a cohort study", newsSource: "Lancet", newsDate: "June 8, 2021", newsLink: "https://doi.org/10.1016/S2665-9913(21)00139-9"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Antibodies elicited by mRNA-1273 vaccination bind more broadly to the receptor binding domain than do those from SARS-CoV-2 infection", newsSource: "Science Magazine", newsDate: "June 8, 2021", newsLink: "https://doi.org/10.1126/scitranslmed.abi9915"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Molecular evidence of SARS-CoV-2 in New York before the first pandemic wave", newsSource: "Nature", newsDate: "June 8, 2021", newsLink: "https://doi.org/10.1038/s41467-021-23688-7"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "The COVID lab-leak hypothesis: what scientists do and don’t know", newsSource: "Nature", newsDate: "June 8, 2021", newsLink: "https://doi.org/10.1038/d41586-021-01529-3"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "SARS-CoV-2 mRNA vaccination induces functionally diverse antibodies to NTD, RBD and S2", newsSource: "Cell", newsDate: "June 8, 2021", newsLink: "https://doi.org/10.1016/j.cell.2021.06.005"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Expiratory aerosol particle escape from surgical masks due to imperfect sealing", newsSource: "Nature", newsDate: "June 8, 2021", newsLink: "https://doi.org/10.1038/s41598-021-91487-7"}),
         e(NewsList, {newsType: "Media News", newsTitle: "How COVID-19 Can Lead to Diabetes", newsSource: "NIH Director Blog", newsDate: "June 8, 2021", newsLink: "https://directorsblog.nih.gov/2021/06/08/how-covid-19-can-lead-to-diabetes/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "For those who lost loved ones to covid, there is no return to normal", newsSource: "Washington Post", newsDate: "June 8, 2021", newsLink: "https://www.washingtonpost.com/local/social-issues/covid-widows-reopening/2021/06/07/7a55f9e6-c3bc-11eb-8c18-fd53a628b992_story.html"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "China is vaccinating a staggering 20 million people a day", newsSource: "Nature", newsDate: "June 9, 2021", newsLink: "https://doi.org/10.1038/d41586-021-01545-3"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Network medicine links SARS-CoV-2/COVID-19 infection to brain microvascular injury and neuroinflammation in dementia-like cognitive impairment", newsSource: "BioMedCentral", newsDate: "June 9, 2021", newsLink: "https://doi.org/10.1186/s13195-021-00850-3"}),    
         e(NewsList, {newsType: "Non Media News", newsTitle: "The four most urgent questions about long COVID", newsSource: "Nature", newsDate: "June 9, 2021", newsLink: "https://doi.org/10.1038/d41586-021-01511-z"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Associations of Vaccination and of Prior Infection With Positive PCR Test Results for SARS-CoV-2 in Airline Passengers Arriving in Qatar", newsSource: "Jama Network", newsDate: "June 9, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jama.2021.9970"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Deep spatial profiling of human COVID-19 brains reveals neuroinflammation with distinct microanatomical microglia-T cell interactions", newsSource: "Cell", newsDate: "June 9, 2021", newsLink: "https://doi.org/10.1016/j.immuni.2021.06.002"}),  
         e(NewsList, {newsType: "Non Media News", newsTitle: "Identification of novel bat coronaviruses sheds light on the evolutionary origins of SARS-CoV-2 and related viruses", newsSource: "Cell", newsDate: "June 9, 2021", newsLink: "https://doi.org/10.1016/j.cell.2021.06.008"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Immunogenicity of Ad26.COV2.S vaccine against SARS-CoV-2 variants in humans", newsSource: "Nature", newsDate: "June 9, 2021", newsLink: "https://doi.org/10.1038/s41586-021-03681-2"}),
         e(NewsList, {newsType: "Media News", newsTitle: "There's A Stark Red-Blue Divide When It Comes To States' Vaccination Rates", newsSource: "NPR", newsDate: "June 9, 2021", newsLink: "https://www.npr.org/2021/06/09/1004430257/theres-a-stark-red-blue-divide-when-it-comes-to-states-vaccination-rates"}),
         e(NewsList, {newsType: "Media News", newsTitle: "In the U.S., hospitalizations are rising in areas with low vaccination rates.", newsSource: "NY Times", newsDate: "June 9, 2021", newsLink: "https://www.nytimes.com/2021/06/09/us/in-the-us-hospitalizations-are-rising-in-areas-with-low-vaccination-rates.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Washington state offers ‘joints for jabs’ to boost vaccination rates", newsSource: "Guardian", newsDate: "June 9, 2021", newsLink: "https://www.theguardian.com/us-news/2021/jun/09/washington-state-joints-for-jabs-boost-vaccination-rates"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Mixing COVID-19 vaccines appears to boost immune responses", newsSource: "Science Magazine", newsDate: "June 9, 2021", newsLink: "https://www.sciencemag.org/news/2021/06/mixing-covid-19-vaccines-appears-boost-immune-responses"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Covid vaccine incentives: Australian doctors now allowed to offer cash, prizes and alternative medicines", newsSource: "Guardian", newsDate: "June 9, 2021"}, {newsLink: "https://www.theguardian.com/australia-news/2021/jun/09/covid-vaccine-incentives-australian-doctors-now-allowed-to-offer-cash-prizes-and-alternative-medicines"}),
         e(NewsList, {newsType: "Media News", newsTitle: "No ‘Freedom Day’? UK could delay lifting of all Covid restrictions due to Delta variant", newsSource: "CNBC", newsDate: "June 9, 2021", newsLink: "https://www.cnbc.com/2021/06/09/uk-could-delay-june-21-lifting-of-covid-measures-due-to-delta-variant.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Despite Ample Shots and Incentives, Vaccine Rates Lag Far Behind in the South", newsSource: "NY Times", newsDate: "June 9, 2021", newsLink: "https://www.nytimes.com/2021/06/09/us/virus-vaccine-south.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Covid could become seasonal epidemic by winter, says German expert", newsSource: "Guardian", newsDate: "June 9, 2021", newsLink: "https://www.theguardian.com/world/2021/jun/09/covid-could-become-seasonal-epidemic-by-winter-says-german-expert"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "Passengers on Mediterranean cruise test positive for covid-19", newsSource: "Washington Post", newsDate: "June 9, 2021", newsLink: "https://www.washingtonpost.com/travel/2021/06/09/msc-cruise-covid-passenger-italy/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Regulators back down from new California workplace mask rules", newsSource: "Mercury News", newsDate: "June 9, 2021", newsLink: "https://www.mercurynews.com/2021/06/09/regulators-back-down-from-new-california-workplace-mask-rules/"}),   
         e(NewsList, {newsType: "Media News", newsTitle: "CDC finds deaths from heart disease and diabetes climbed amid Covid in U.S.", newsSource: "NBC News", newsDate: "June 9, 2021", newsLink: "https://www.nbcnews.com/health/health-news/cdc-finds-deaths-heart-disease-diabetes-climbed-amid-covid-u-n1270260"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Ohio nurse hilariously fails to prove COVID vaccine makes people magnetic, key falls from her neck", newsSource: "NY Daily News", newsDate: "June 9, 2021", newsLink: "https://www.nydailynews.com/news/national/ny-ohio-nurse-covid-vaccine-magnetic-20210610-mumke7o5sncg3lngicytageczu-story.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "New Evidence Suggests COVID-19 Vaccines Remain Effective Against Variants", newsSource: "NPR", newsDate: "June 9, 2021", newsLink: "https://www.npr.org/sections/health-shots/2021/06/09/1004738276/new-evidence-suggests-covid-19-vaccines-remain-effective-against-variants"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Social, economic, and environmental factors influencing the basic reproduction number of COVID-19 across countries", newsSource: "PLOS", newsDate: "June 9, 2021", newsLink: "https://doi.org/10.1371/journal.pone.0252373"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Covid distancing may have weakened children’s immune system, experts say", newsSource: "Guardian", newsDate: "June 9, 2021", newsLink: "https://www.theguardian.com/society/2021/jun/09/covid-distancing-may-have-weakened-childrens-immune-system-experts-say"}),
         e(NewsList, {newsType: "Media News", newsTitle: "The Olympics Are Really Happening. For Athletes, That Means A Huge Number Of Rules", newsSource: "NPR", newsDate: "June 9, 2021", newsLink: "https://www.npr.org/2021/06/09/1004765190/the-olympics-are-really-happening-for-athletes-that-means-a-huge-number-of-rules"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Biden administration tells federal agencies they should not require employees to be vaccinated to work on-site", newsSource: "Washington Post", newsDate: "June 9, 2021", newsLink: "https://www.washingtonpost.com/politics/biden-administraton-federal-workers-vaccines/2021/06/09/19dea94c-c947-11eb-afd0-9726f7ec0ba6_story.html"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "Biden administration to buy 500 million Pfizer coronavirus vaccine doses to donate to the world", newsSource: "Washington Post", newsDate: "June 9, 2021", newsLink: "https://www.washingtonpost.com/politics/biden-vaccine-donate/2021/06/09/c2744674-c934-11eb-93fa-9053a95eb9f2_story.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Danes ditch masks, allow more Euro 2020 fans in lockdown deal", newsSource: "Euro News", newsDate: "June 10, 2021", newsLink: "https://www.euronews.com/2021/06/10/us-health-coronavirus-denmark"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Does vaccinating adults stop kids from spreading COVID too?", newsSource: "Nature", newsDate: "June 10, 2021", newsLink: "https://doi.org/10.1038/d41586-021-01549-z"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Miami Bitcoin Gathering Was a Covid Hot Spot, Attendees Say", newsSource: "Bloomberg", newsDate: "June 10, 2021", newsLink: "https://www.bloomberg.com/news/articles/2021-06-10/miami-bitcoin-gathering-was-a-covid-hot-spot-attendees-say"}),
         e(NewsList, {newsType: "Media News", newsTitle: "G7 leaders will call for fresh WHO inquiry into Covid origins, leaked communique suggests", newsSource: "Guardian", newsDate: "June 10, 2021", newsLink: "https://www.theguardian.com/world/2021/jun/10/g7-communique-leak-covid-origins-inquiry-vaccines-forced-labour"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Celebrations (and questions) greet US vaccine donation plan", newsSource: "AP News", newsDate: "June 10, 2021", newsLink: "https://apnews.com/article/joe-biden-asia-g-7-summit-coronavirus-pandemic-business-8ce6cca4689cce38a81e2cc8a790edb6"}),
         e(NewsList, {newsType: "Media News", newsTitle: "German panel gives limited approval for COVID-19 shot for adolescents", newsSource: "Reuters", newsDate: "June 10, 2021", newsLink: "https://www.reuters.com/article/health-coronavirus-germany-biontech/german-panel-gives-limited-approval-for-covid-19-shot-for-adolescents-idUSL5N2NK1OI"}),
         e(NewsList, {newsType: "Media News", newsTitle: "CDC says heart inflammation was higher than expected in 16- to 24-year-olds after second Covid vaccine shot, but still rare", newsSource: "CNBC", newsDate: "June 10, 2021", newsLink: "https://www.cnbc.com/2021/06/10/covid-vaccine-cdc-says-heart-inflammation-cases-in-16-to-24-year-olds-higher-than-expected-after-second-shot.html"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Moderna Files for Emergency Use Authorization for its COVID-19 Vaccine in Adolescents in the United States", newsSource: "Moderna", newsDate: "June 10, 2021", newsLink: "https://investors.modernatx.com/news-releases/news-release-details/moderna-files-emergency-use-authorization-its-covid-19-vaccine"}),  
         e(NewsList, {newsType: "Non Media News", newsTitle: "BNT162b2-elicited neutralization of B.1.617 and other SARS-CoV-2 variants", newsSource: "Nature", newsDate: "June 10, 2021", newsLink: "https://doi.org/10.1038/s41586-021-03693-y"}), 
         e(NewsList, {newsType: "Media News", newsTitle: "Drop in childhood vaccinations during pandemic may raise risk of other outbreaks when schools reopen, CDC says", newsSource: "Washington Post", newsDate: "June 10, 2021", newsLink: "https://www.washingtonpost.com/health/2021/06/10/childhood-vaccination-falloff-increased-risk-disease-outbreaks/"}), 
         e(NewsList, {newsType: "Non Media News", newsTitle: "Incidence of Multisystem Inflammatory Syndrome in Children Among US Persons Infected With SARS-CoV-2", newsSource: "Jama Network", newsDate: "June 10, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamanetworkopen.2021.16420"}), 
         e(NewsList, {newsType: "Media News", newsTitle: "FDA advisers debate standards on a coronavirus vaccine for young children", newsSource: "Washington Post", newsDate: "June 10, 2021", newsLink: "https://www.washingtonpost.com/health/2021/06/10/covid-vaccines-for-children/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "As more kids go down the ‘deep, dark tunnel’ of long Covid, doctors still can’t predict who is at risk", newsSource: "Stat News", newsDate: "June 10, 2021", newsLink: "https://www.statnews.com/2021/06/10/as-more-kids-get-long-covid-doctors-still-cant-predict-who-is-at-risk/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Tinnitus, hearing loss not uncommon in COVID-19 patients", newsSource: "UPI", newsDate: "June 10, 2021", newsLink: "https://www.upi.com/Health_News/2021/06/10/coronavirus-hearing-loss-research/7501623345172/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "FDA accuses company of distributing unapproved Covid test and using falsified data", newsSource: "Stat News", newsDate: "June 10, 2021", newsLink: "https://www.statnews.com/2021/06/10/fda-accuses-company-of-distributing-unapproved-covid-test-using-falsified-data/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "The COVID-19 virus can cause diabetes, new studies find", newsSource: "ABC News", newsDate: "June 10, 2021", newsLink: "https://abcnews.go.com/Health/covid-19-virus-diabetes-studies-find/story?id=78168634"}),
         e(NewsList, {newsType: "Media News", newsTitle: "US extends expiration dates for J&J COVID vaccine by 6 weeks", newsSource: "AP News", newsDate: "June 10, 2021", newsLink: "https://apnews.com/article/joe-biden-coronavirus-vaccine-science-coronavirus-pandemic-business-6d04574617b35c56e7ca2c711cc5585f"}),
         e(NewsList, {newsType: "Media News", newsTitle: "EU foregoes 100 million J&J vaccines, considers donating other doses", newsSource: "Reuters", newsDate: "June 10, 2021", newsLink: "https://www.reuters.com/world/europe/eu-foregoes-100-million-jj-vaccines-considers-donating-other-doses-sources-2021-06-10/"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "US Department of Labor's OSHA issues emergency temporary standard to protect health care workers from the coronavirus", newsSource: "U.S. Department of Labor", newsDate: "June 10, 2021", newsLink: "https://www.osha.gov/news/newsreleases/national/06102021"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Bitcoin conference attendees report testing positive for Covid after returning from Miami", newsSource: "CNBC", newsDate: "June 10, 2021", newsLink: "https://www.cnbc.com/2021/06/10/bitcoin-2021-attendees-report-covid-cases-after-returning-from-miami.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Anatomy of Japan’s joyless Olympics: A hyper-cautious bureaucracy and slow vaccine rollout", newsSource: "Washington Post", newsDate: "June 10, 2021", newsLink: "https://www.washingtonpost.com/world/asia_pacific/japan-olympics-pandemic-vaccines/2021/06/10/97bdbbda-c84f-11eb-8708-64991f2acf28_story.html"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Community-level evidence for SARS-CoV-2 vaccine protection of unvaccinated individuals", newsSource: "Nature", newsDate: "June 10, 2021", newsLink: "https://doi.org/10.1038/s41591-021-01407-5"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "A new group at increased risk of a SARS-CoV-2 infection emerges: The recently vaccinated", newsSource: "Science Direct", newsDate: "June 8, 2021", newsLink: "https://www.sciencedirect.com/science/article/pii/S0264410X21007362"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Electronic Cigarette Use Is Not Associated with COVID-19 Diagnosis ", newsSource: "Sage Journal", newsDate: "June 10, 2021", newsLink: "https://doi.org/10.1177%2F21501327211024391"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Viral infiltration of pancreatic islets in patients with COVID-19", newsSource: "Nature", newsDate: "June 10, 2020", newsLink: "https://doi.org/10.1038/s41467-021-23886-3"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "Seattle becomes most vaccinated city in US, mayor says", newsSource: "Guardian", newsDate: "June 10, 2021", newsLink: "https://www.theguardian.com/us-news/2021/jun/10/seattle-most-vaccinated-city-in-us-mayor"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Clinical characteristics and risk factors for death among hospitalised children and adolescents with COVID-19 in Brazil: an analysis of a nationwide database", newsSource: "Lancet", newsDate: "June 10, 2021", newsLink: "https://doi.org/10.1016/S2352-4642(21)00134-6"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Taco Bell® Plans To Shell Out Free Tacos To Vaccinated Californians On June 15", newsSource: "Taco Bell", newsDate: "June 11, 2021", newsLink: "https://www.tacobell.com/news/free-tacos-to-vaccinated-californians-on-june-15"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Open letter from Deputy Chief Medical Officer to UK residents who have volunteered to take part in COVID-19 vaccine studies ", newsSource: "Government UK", newsDate: "June 11, 2021", newsLink: "https://www.gov.uk/government/publications/letter-from-the-deputy-chief-medical-officer-to-uk-vaccine-study-volunteers/open-letter-from-deputy-chief-medical-officer-to-uk-residents-who-have-volunteered-to-take-part-in-covid-19-vaccine-studies"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Virtually all hospitalized Covid patients have one thing in common: They're unvaccinated", newsSource: "NBC News", newsDate: "June 11, 2021", newsLink: "https://www.nbcnews.com/health/health-news/virtually-all-hospitalized-covid-patients-have-one-thing-common-they-n1270482"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Southern states have a ‘real vulnerability’ to Delta Covid variant this summer, warns Dr. Peter Hotez", newsSource: "CNBC", newsDate: "June 11, 2021", newsLink: "https://www.cnbc.com/2021/06/11/covid-doctor-warns-southern-states-vulnerable-to-delta-variant-this-summer.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "As the pandemic retreats, we’re left wondering what we’ve been through", newsSource: "Washington Post", newsDate: "June 11, 2021", newsLink: "https://www.washingtonpost.com/outlook/pandemic-retreat-time-changed/2021/06/10/cd8ecb90-c7a6-11eb-a11b-6c6191ccd599_story.html"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "International Analysis of Electronic Health Records of Children and Youth Hospitalized With COVID-19 Infection in 6 Countries", newsSource: "Jama Network", newsDate: "June 11, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamanetworkopen.2021.12596"}),
         e(NewsList, {newsType: "Media News", newsTitle: "What Did COVID Do to Friendship?", newsSource: "New Yorker", newsDate: "June 11, 2021", newsLink: "https://www.newyorker.com/culture/dept-of-returns/what-did-covid-do-to-friendship"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "COVID-19 Vaccine Janssen: authorities in EU take steps to safeguard vaccine quality", newsSource: "European Medicine Agency (EMA)", newsDate: "June 11, 2021", newsLink: "https://www.ema.europa.eu/en/news/covid-19-vaccine-janssen-authorities-eu-take-steps-safeguard-vaccine-quality"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "CDC plans emergency meeting on rare heart inflammation following COVID-19 vaccines", newsSource: "CBS News", newsDate: "June 11, 2021", newsLink: "https://www.cbsnews.com/news/covid-19-vaccine-cdc-meeting-myocarditis-heart-inflammation/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Rural Communities Fall Farther Behind In COVID-19 Vaccination Rates", newsSource: "NPR", newsDate: "June 11, 2021", newsLink: "https://www.npr.org/sections/health-shots/2021/06/11/1005367753/rural-communities-fall-farther-behind-in-covid-19-vaccination-rates"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "J&J doses to be released, but many will be tossed", newsSource: "AP News", newsDate: "June 11, 2021", newsLink: "https://apnews.com/article/government-and-politics-coronavirus-pandemic-business-health-d67646ba072e5eb4e574005174d1c184"}),    
         e(NewsList, {newsType: "Non Media News", newsTitle: "Comparison of Symptoms and RNA Levels in Children and Adults With SARS-CoV-2 Infection in the Community Setting", newsSource: "Jama Network", newsDate: "June 11, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamapediatrics.2021.2025"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Factors Associated With Self-reported Symptoms of Depression Among Adults With and Without a Previous COVID-19 Diagnosis", newsSource: "Jama Network", newsDate: "June 11, 2021", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamanetworkopen.2021.16612"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Novavax Announces Positive Data from Three Complementary Studies of COVID-19 Beta (B.1.351) Variant Strain Vaccine", newsSource: "Novavax", newsDate: "June 11, 2020", newsLink: "https://ir.novavax.com/news-releases/news-release-details/novavax-announces-positive-data-three-complementary-studies"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "Americans are heaven for us: the surge in US visitors throwing Greece a lifeline", newsSource: "Guardian", newsDate: "June 12, 2021", newsLink: "https://www.theguardian.com/world/2021/jun/12/americans-are-heaven-for-us-a-surge-in-us-visitors-throws-greece-a-lifeline"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Covid passports will be discriminatory and must be scrapped, say MPs", newsSource: "Guardian", newsDate: "June 12, 2021", newsLink: "https://www.theguardian.com/politics/2021/jun/12/covid-passports-will-be-discriminatory-and-must-be-scrapped-say-mps"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Virus-ravaged Brazil doesn’t want Copa America. But Bolsonaro says it’s hosting it anyway.", newsSource: "Washington Post", newsDate: "June 12, 2021", newsLink: "https://www.washingtonpost.com/world/2021/06/12/brazil-virus-copa-soccer-bolsonaro/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Too early to tell if yearly COVID-19 booster vaccines needed", newsSource: "UPI", newsDate: "June 12, 2021", newsLink: "https://www.upi.com/Health_News/2021/06/12/coronavirus-researchers-unsure-vaccine-boosters/1021623446300/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Most people in UK initially opposed to Covid vaccine have had jab, study finds", newsSource: "Guardian", newsDate: "June 12, 2021", newsLink: "https://www.theguardian.com/society/2021/jun/12/most-people-in-uk-initially-opposed-to-covid-vaccine-have-had-jab-study-finds"}),
         e(NewsList, {newsType: "Media News", newsTitle: "COVID Precautions Can Help Kids During Cold Season", newsSource: "NPR", newsDate: "June 12, 2021", newsLink: "https://www.npr.org/2021/06/12/1005833538/covid-precautions-can-help-kids-during-cold-season"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Bolsonaro fined for flouting mask order at motorcycle rally", newsSource: "AP News", newsDate: "June 12, 2021", newsLink: "https://apnews.com/article/caribbean-coronavirus-pandemic-health-2a5fe1181e7b2cf683273ef37be0e5d6"}),
         e(NewsList, {newsType: "Media News", newsTitle: "U.S. Air Travelers Top 2 Million for First Time in Pandemic", newsSource: "Bloomberg", newsDate: "June 12, 2021", newsLink: "https://www.bloomberg.com/news/articles/2021-06-12/u-s-air-travelers-top-2-million-for-first-time-since-pandemic"}),
         e(NewsList, {newsType: "Media News", newsTitle: "F.D.A. details failures at a Baltimore plant that led to unusable vaccine doses.", newsSource: "New York Times", newsDate: "June 12, 2021", newsLink: "https://www.nytimes.com/2021/06/12/world/fda-baltimore-unusable-vaccine-doses-johnson.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Delay ending lockdown: majority of public back Boris Johnson to wait", newsSource: "Guardian", newsDate: "June 12, 2021", newsLink: "https://www.theguardian.com/uk-news/2021/jun/12/delay-ending-lockdown-majority-of-public-back-boris-johnson"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Man gets 10-year sentence for attacking and coughing on person who asked him to pull up mask", newsSource: "Washington Post", newsDate: "June 12, 2021", newsLink: "https://www.washingtonpost.com/nation/2021/06/12/shane-michael-mask-assault-iowa/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Judge dismisses lawsuit filed by Houston hospital employees who refused covid-19 vaccine", newsSource: "Washington Post", newsDate: "June 13, 2021", newsLink: "https://www.washingtonpost.com/nation/2021/06/13/methodist-vaccine-lawsuit-dismissed/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Why are women more prone to long Covid?", newsSource: "Guardian", newsDate: "June 13, 2021", newsLink: "https://www.theguardian.com/society/2021/jun/13/why-are-women-more-prone-to-long-covid"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Factory workers making goods for the west bear brunt of virus surge in south-east Asia", newsSource: "Guardian", newsDate: "June 13, 2021", newsLink: "https://www.theguardian.com/world/2021/jun/13/factory-workers-making-goods-for-the-west-bear-brunt-of-virus-surge-in-south-east-asia"}),
         e(NewsList, {newsType: "Media News", newsTitle: "At least 130,000 households in England made homeless in pandemic", newsSource: "Guardian", newsDate: "June 13, 2021", newsLink: "https://www.theguardian.com/society/2021/jun/13/at-least-130000-households-in-england-made-homeless-in-pandemic"}),
         e(NewsList, {newsType: "Media News", newsTitle: "People are so burned out: US essential workers struggle as restrictions lifted", newsSource: "Guardian", newsDate: "June 13, 2021", newsLink: "https://www.theguardian.com/us-news/2021/jun/13/us-essential-workers-burned-out-pandemic"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "A long-term perspective on immunity to COVID", newsSource: "Nature", newsDate: "June 14, 2020", newsLink: "https://doi.org/10.1038/d41586-021-01557-z"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Anti-Vaccine Activists Use A Federal Database To Spread Fear About COVID Vaccines", newsSource: "NPR", newsDate: "June 14, 2020", newsLink: "https://www.npr.org/sections/health-shots/2021/06/14/1004757554/anti-vaccine-activists-use-a-federal-database-to-spread-fear-about-covid-vaccine/"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Novavax COVID-19 Vaccine Demonstrates 90% Overall Efficacy and 100% Protection Against Moderate and Severe Disease in PREVENT-19 Phase 3 Trial", newsSource: "Novavax", newsDate: "June 14, 2020", newsLink: "https://ir.novavax.com/news-releases/news-release-details/novavax-covid-19-vaccine-demonstrates-90-overall-efficacy-and"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Vaccines Offer Significant Protection Against Covid-19 Delta Variant, U.K. Analysis Shows", newsSource: "Wall Street Journal", newsDate: "June 14, 2020", newsLink: "https://www.wsj.com/articles/vaccines-offer-significant-protection-against-covid-19-delta-variant-u-k-analysis-shows-11623690999"}),
         e(NewsList, {newsType: "Media News", newsTitle: "U.S. sending 1.35 million doses of J&J vaccine to Mexico overnight", newsSource: "NBC News", newsDate: "June 14, 2020", newsLink: "https://www.nbcnews.com/politics/white-house/u-s-sending-1-35-million-doses-j-j-vaccine-n1270820"}),
         e(NewsList, {newsType: "Media News", newsTitle: "A Top Virologist in China, at Center of a Pandemic Storm, Speaks Out", newsSource: "NY Times", newsDate: "June 14, 2020", newsLink: "https://www.nytimes.com/2021/06/14/world/asia/china-covid-wuhan-lab-leak.html"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Ashvattha Therapeutics Announces Positive Interim Data from Ongoing Phase 2 PRANA Clinical Study of OP-101 in Severe COVID-19 Patients ", newsSource: "Ashvattha Therapeutics", newsDate: "June 14, 2020", newsLink: "https://avttx.com/ashvattha-therapeutics-announces-positive-interim-data-from-ongoing-phase-2-prana-clinical-study-of-op-101-in-severe-covid-19-patients/"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "A third dose of Covid vaccine may help protect immunocompromised patients, small study suggests", newsSource: "NBC News", newsDate: "June 14, 2020", newsLink: "https://www.nbcnews.com/health/health-news/third-dose-covid-vaccine-may-help-protect-immunocompromised-patients-small-n1270809"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "A Delta pilot left a note behind last March. 435 days later, another pilot found the ‘pandemic time capsule.’", newsSource: "Washington Post", newsDate: "June 14, 2020", newsLink: "https://www.washingtonpost.com/travel/2021/06/14/delta-pilot-pandemic-note-plane/"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "San Francisco Is Over 70% Vaccinated — But It's Not Quite Time To Pop The Champagne", newsSource: "NPR", newsDate: "June 14, 2020", newsLink: "https://www.npr.org/2021/06/14/1006349431/san-francisco-is-over-70-vaccinated-but-it-s-not-quite-time-to-pop-the-champagne"}),     
         e(NewsList, {newsType: "Media News", newsTitle: "Coronavirus infections dropping where people are vaccinated, rising where they are not, Post analysis finds", newsSource: "Washington Post", newsDate: "June 14, 2020", newsLink: "https://www.washingtonpost.com/health/2021/06/14/covid-cases-vaccination-rates/"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "SARS-CoV-2 Delta VOC in Scotland: demographics, risk of hospital admission, and vaccine effectiveness", newsSource: "Lancet", newsDate: "June 14, 2020", newsLink: "https://doi.org/10.1016/S0140-6736(21)01358-1"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Naturally enhanced neutralizing breadth against SARS-CoV-2 one year after infection", newsSource: "Nature", newsDate: "June 14, 2020", newsLink: "https://doi.org/10.1038/s41586-021-03696-9"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Role of meteorological factors in the transmission of SARS-CoV-2 in the United States", newsSource: "Nature", newsDate: "June 14, 2020", newsLink: "https://doi.org/10.1038/s41467-021-23866-7"}),        
         e(NewsList, {newsType: "Media News", newsTitle: "Alarm rises in India over COVID-19 risks as crowds return to malls and rail stations", newsSource: "Reuters", newsDate: "June 15, 2020", newsLink: "https://www.reuters.com/business/healthcare-pharmaceuticals/india-reports-60471-new-covid-19-cases-2726-deaths-2021-06-15/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Covid-19 Ranged From Illinois to Massachusetts Before States Reported First Cases", newsSource: "Wall Street Journal", newsDate: "June 15, 2020", newsLink: "https://www.wsj.com/articles/covid-19-virus-ranged-from-illinois-to-massachusetts-before-states-reported-first-cases-11623762001"}),     
         e(NewsList, {newsType: "Media News", newsTitle: "Health experts say India missed early alarm, let deadly coronavirus variant spread", newsSource: "Reuters", newsDate: "June 15, 2020", newsLink: "https://www.reuters.com/business/healthcare-pharmaceuticals/health-experts-say-india-missed-early-alarm-let-deadly-coronavirus-variant-2021-06-15/"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "China set to administer 1bn Covid vaccine doses by end of this week", newsSource: "Guardian", newsDate: "June 15, 2020", newsLink: "https://www.theguardian.com/society/2021/jun/15/china-set-to-deliver-1bn-covid-vaccine-doses-by-end-of-this-week"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "Astra antibody cocktail fails to prevent COVID-19 symptoms in large trial", newsSource: "Reuters", newsDate: "June 15, 2020", newsLink: "https://www.reuters.com/business/healthcare-pharmaceuticals/astrazeneca-says-its-antibody-treatment-failed-in-preventing-covid-19-exposed-2021-06-15/"}), 
         e(NewsList, {newsType: "Media News", newsTitle: "Vermont drops all Covid restrictions as first state to reach 80% vaccination", newsSource: "Guardian", newsDate: "June 15, 2020", newsLink: "https://www.theguardian.com/us-news/2021/jun/15/vermont-covid-coronavirus-restrictions-vaccination-goal"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Covid jabs to become mandatory for care home staff in England", newsSource: "Guardian", newsDate: "June 15, 2020", newsLink: "https://www.theguardian.com/world/2021/jun/15/covid-jabs-to-become-mandatory-for-care-home-staff-in-england"}),
         e(NewsList, {newsType: "Media News", newsTitle: "The Lab Leak Theory Doesn’t Hold Up", newsSource: "Foreign Policy", newsDate: "June 15, 2020", newsLink: "https://foreignpolicy.com/2021/06/15/lab-leak-theory-doesnt-hold-up-covid-china/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "New York lifts most Covid restrictions ‘effective immediately’ now that 70% of adults have at least one vaccine shot", newsSource: "CNBC", newsDate: "June 15, 2020", newsLink: "https://www.cnbc.com/2021/06/15/new-york-will-lift-most-covid-restrictions-after-70percent-of-adults-vaccinated.html"}), 
         e(NewsList, {newsType: "Non Media News", newsTitle: "NIH study offers new evidence of early SARS-CoV-2 infections in U.S.", newsSource: "National Institute of Health", newsDate: "June 15, 2020", newsLink: "https://www.nih.gov/news-events/news-releases/nih-study-offers-new-evidence-early-sars-cov-2-infections-us"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "COVID-19 Vaccine AstraZeneca effective against Delta (‘Indian’) variant", newsSource: "AstraZeneca", newsDate: "June 15, 2020", newsLink: "https://www.astrazeneca.com/media-centre/press-releases/2021/covid-19-vaccine-astrazeneca-effective-against-delta-indian-variant.html"}), 
         e(NewsList, {newsType: "Non Media News", newsTitle: "Safety and Immunogenicity of a Third Dose of SARS-CoV-2 Vaccine in Solid Organ Transplant Recipients: A Case Series", newsSource: "ACP Journals", newsDate: "June 15, 2020", newsLink: "https://doi.org/10.7326/L21-0282"}),     
         e(NewsList, {newsType: "Non Media News", newsTitle: "The mechanisms of action of Ivermectin against SARS-CoV-2: An evidence-based clinical review article", newsSource: "Nature", newsDate: "June 15, 2020", newsLink: "https://doi.org/10.1038/s41429-021-00430-5"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Dynamic innate immune response determines susceptibility to SARS-CoV-2 infection and early replication kinetics", newsSource: "Journal of Experimental Medicine", newsDate: "June 15, 2020", newsLink: "https://doi.org/10.1084/jem.20210583"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Distorted, Bizarre Food Smells Haunt Covid Survivors", newsSource: "NY Times", newsDate: "June 15, 2020", newsLink: "https://www.nytimes.com/2021/06/15/health/covid-smells-food.html"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Public acceptance of COVID-19 vaccines: cross-national evidence on levels and individual-level predictors using observational data", newsSource: "National Library of Medicine", newsDate: "June 15, 2020", newsLink: "https://pubmed.ncbi.nlm.nih.gov/34130963/"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "A cohort autopsy study defines COVID-19 systemic pathogenesis", newsSource: "Nature", newsDate: "June 16, 2020", newsLink: "https://doi.org/10.1038/s41422-021-00523-8"}),    
         e(NewsList, {newsType: "Non Media News", newsTitle: "CureVac Provides Update on Phase 2b/3 Trial of First-Generation COVID-19 Vaccine Candidate, CVnCoV", newsSource: "CureVac", newsDate: "June 16, 2020", newsLink: "https://www.curevac.com/en/2021/06/16/curevac-provides-update-on-phase-2b-3-trial-of-first-generation-covid-19-vaccine-candidate-cvncov/"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "RECOVERY trial finds Regeneron’s monoclonal antibody combination reduces deaths for hospitalised COVID-19 patients who have not mounted their own immune response", newsSource: "Recovery", newsDate: "June 16, 2020", newsLink: "https://www.recoverytrial.net/news/recovery-trial-finds-regeneron2019s-monoclonal-antibody-combination-reduces-deaths-for-hospitalised-covid-19-patients-who-have-not-mounted-their-own-immune-response-1"}), 
         e(NewsList, {newsType: "Media News", newsTitle: "EU says J&J to miss vaccine supply target in second quarter", newsSource: "Reuters", newsDate: "June 16, 2020", newsLink: "https://www.reuters.com/business/healthcare-pharmaceuticals/eu-says-jj-miss-vaccine-supply-target-second-quarter-2021-06-16/"}), 
         e(NewsList, {newsType: "Media News", newsTitle: "I work on cruise ships. We can’t get back to normal if we can’t require vaccines.", newsSource: "Washington Post", newsDate: "June 16, 2020", newsLink: "https://www.washingtonpost.com/outlook/2021/06/16/cruise-vaccines-desantis-florida/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Vaccine advisers not planning to back Covid jabs for children, says UK minister", newsSource: "Guardian", newsDate: "June 16, 2020", newsLink: "https://www.theguardian.com/society/2021/jun/16/uk-minister-vaccine-advisers-not-planning-back-covid-jabs-children"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Inside Pfizer’s race to produce the world’s biggest supply of covid vaccine", newsSource: "Washington Post", newsDate: "June 16, 2020", newsLink: "https://www.washingtonpost.com/business/2021/06/16/pfizer-vaccine-engineers-supply/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Royal Caribbean delays cruise ship after 8 crew members test positive for Covid", newsSource: "NBC News", newsDate: "June 16, 2020", newsLink: "https://www.nbcnews.com/news/us-news/royal-caribbean-delays-cruise-ship-after-8-crew-members-test-n1270979"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Pockets of unvaccinated Americans threaten to prolong pandemic", newsSource: "Seattle Times", newsDate: "June 16, 2020", newsLink: "https://www.seattletimes.com/nation-world/pockets-of-unvaccinated-americans-threaten-to-prolong-pandemic/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "After Months Of Special Education Turmoil, Families Say Schools Owe Them", newsSource: "NPR", newsDate: "June 16, 2020", newsLink: "https://www.npr.org/2021/06/16/994587239/after-months-of-special-education-turmoil-families-say-schools-owe-them"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "Moral judgments about an activity’s COVID-19 risk can lead people astray", newsSource: "Science News", newsDate: "June 16, 2020", newsLink: "https://www.sciencenews.org/article/coronavirus-covid-moral-judgment-activity-risk-behavior-bias"}), 
         e(NewsList, {newsType: "Media News", newsTitle: "The U.S. agrees to buy 200 million more doses of Moderna’s vaccine, in case boosters are needed.", newsSource: "NY Times", newsDate: "June 16, 2020", newsLink: "https://www.nytimes.com/2021/06/16/us/politics/moderna-covid-vaccine-booster-shots.html"}), 
         e(NewsList, {newsType: "Media News", newsTitle: "Needle phobia could be the cause of 10% of COVID vaccine hesitancy in the UK", newsSource: "Conversation", newsDate: "June 16, 2020", newsLink: "https://theconversation.com/needle-phobia-could-be-the-cause-of-10-of-covid-vaccine-hesitancy-in-the-uk-new-research-162678"}), 
         e(NewsList, {newsType: "Non Media News", newsTitle: "Incidence of SARS-CoV-2 Infection in Health Care Workers After a Single Dose of mRNA-1273 Vaccine", newsSource: "Jama Network", newsDate: "June 16, 2020", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamanetworkopen.2021.16416"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Tofacitinib in Patients Hospitalized with Covid-19 Pneumonia", newsSource: "New England Journal of Medicine", newsDate: "June 16, 2020", newsLink: "https://www.nejm.org/doi/full/10.1056/NEJMoa2101643"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "SARS-CoV-2 Infects Hamster Testes", newsSource: "MDPI", newsDate: "June 16, 2020", newsLink: "https://www.mdpi.com/2076-2607/9/6/1318/htm"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Reduced neutralization of SARS-CoV-2 B.1.617 by vaccine and convalescent serum", newsSource: "Cell", newsDate: "June 17, 2020", newsLink: "https://doi.org/10.1016/j.cell.2021.06.020"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Causation or confounding: why controls are critical for characterizing long COVID", newsSource: "Nature", newsDate: "June 17, 2020", newsLink: "https://doi.org/10.1038/s41591-021-01402-w"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Sperm Parameters Before and After COVID-19 mRNA Vaccination", newsSource: "Jama Network", newsDate: "June 17, 2020", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jama.2021.9976"}),    
         e(NewsList, {newsType: "Non Media News", newsTitle: "New national surveillance of possible COVID-19 reinfection, published by PHE ", newsSource: "Government UK", newsDate: "June 17, 2020", newsLink: "https://www.gov.uk/government/news/new-national-surveillance-of-possible-covid-19-reinfection-published-by-phe"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "US to spend $3.2B for antiviral pills for COVID-19", newsSource: "AP News", newsDate: "June 17, 2020", newsLink: "https://apnews.com/article/anthony-fauci-united-states-infectious-diseases-coronavirus-pandemic-health-d9cfa18e561f3e58b2ae39e77353ab01"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Dr. Fauci Says The Risks From The Delta Variant Underscore The Importance Of Vaccines", newsSource: "NPR", newsDate: "June 17, 2020", newsLink: "https://www.npr.org/sections/coronavirus-live-updates/2021/06/17/1007493934/the-delta-variant-is-the-most-contagious-of-covid-19-strains"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "From $1-Million Lotteries to Free Beer: Do COVID Vaccination Incentives Work?", newsSource: "Scientific American", newsDate: "June 17, 2020", newsLink: "https://www.scientificamerican.com/article/from-1-million-lotteries-to-free-beer-do-covid-vaccination-incentives-work/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Why are Olympics going on despite public, medical warnings?", newsSource: "AP News", newsDate: "June 17, 2020", newsLink: "https://apnews.com/article/business-health-coronavirus-pandemic-olympic-games-2020-tokyo-olympics-dd49a7aaaa6c59defea9670c5b19475c"}),
         e(NewsList, {newsType: "Media News", newsTitle: "New Covid study hints at long-term loss of brain tissue, Dr. Scott Gottlieb warns", newsSource: "CNBC", newsDate: "June 17, 2020", newsLink: "https://www.cnbc.com/2021/06/17/new-covid-study-hints-at-long-term-loss-of-brain-tissue-dr-scott-gottlieb-warns.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Giant Buddhist goddess in Japan gets face mask to pray for end of COVID-19", newsSource: "Reuters", newsDate: "June 17, 2020", newsLink: "https://www.reuters.com/world/asia-pacific/giant-buddhist-goddess-japan-gets-face-mask-pray-end-covid-19-2021-06-16/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "The U.S. Has a Higher Rate of Vaccine Opposition Than Any Country Tracked Besides Russia", newsSource: "Morning Consult", newsDate: "June 17, 2020", newsLink: "https://morningconsult.com/global-vaccine-tracking/"}),   
         e(NewsList, {newsType: "Non Media News", newsTitle: "Antiviral effect of high-dose ivermectin in adults with COVID-19: A proof-of-concept randomized trial", newsSource: "Lancet", newsDate: "June 17, 2020", newsLink: "https://doi.org/10.1016/j.eclinm.2021.100959"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Ivermectin for Prevention and Treatment of COVID-19 Infection", newsSource: "American Journal of Therapeutics", newsDate: "June 17, 2020", newsLink: "https://doi.org/10.1097/mjt.0000000000001402"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "In vitro and in vivo functions of SARS-CoV-2 infection-enhancing and neutralizing antibodies", newsSource: "Cell", newsDate: "June 18, 2020", newsLink: "https://doi.org/10.1016/j.cell.2021.06.021"}),    
         e(NewsList, {newsType: "Non Media News", newsTitle: "Telmisartan for treatment of Covid-19 patients: An open multicenter randomized clinical trial", newsSource: "Lancet", newsDate: "June 18, 2020", newsLink: "https://doi.org/10.1016/j.eclinm.2021.100962"}),
         e(NewsList, {newsType: "Media News", newsTitle: "It’s going to be weird’: Download festival opens with no social distancing", newsSource: "Guardian", newsDate: "June 18, 2020", newsLink: "https://www.theguardian.com/music/2021/jun/18/its-going-to-be-weird-download-festival-opens-with-no-social-distancing-covid-pilot-event"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "High Hopes for Johnson & Johnson’s Covid Vaccine Have Fizzled in the U.S.", newsSource: "NY Times", newsDate: "June 18, 2020", newsLink: "https://www.nytimes.com/2021/06/18/us/politics/johnson-johnson-covid-vaccine.html?action=click&module=Spotlight&pgtype=Homepage"}), 
         e(NewsList, {newsType: "Non Media News", newsTitle: "AstraZeneca welcomes Court ruling on supply of its COVID-19 vaccine to Europe", newsSource: "AstraZeneca", newsDate: "June 18, 2020", newsLink: "https://www.astrazeneca.com/content/astraz/media-centre/press-releases/2021/astrazeneca-welcomes-court-ruling-on-supply-of-its-covid-19-vaccine-to-europe.html"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Belgian Court orders AstraZeneca to deliver vaccine doses to the EU", newsSource: "European Comission", newsDate: "June 18, 2020", newsLink: "https://ec.europa.eu/commission/presscorner/detail/en/ip_21_3090"}),
         e(NewsList, {newsType: "Media News", newsTitle: "BioNTech shots have stronger antibody response than Sinovac, Hong Kong study shows", newsSource: "Reuters", newsDate: "June 18, 2020", newsLink: "https://www.reuters.com/business/healthcare-pharmaceuticals/biontech-shots-have-stronger-antibody-response-than-sinovac-hong-kong-study-2021-06-19/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "AP-NORC poll: Many Americans resuming pre-virus activities", newsSource: "AP News", newsDate: "June 18, 2020", newsLink: "https://apnews.com/article/only-on-ap-lifestyle-coronavirus-pandemic-health-ddfd165dd67e9ec79d4850a1d80734e8"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Vaccine induced thrombotic thrombocytopenia: The shady chapter of a success story", newsSource: "Science Direct", newsDate: "June 18, 2020", newsLink: "https://doi.org/10.1016/j.metop.2021.100101"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "CureVac COVID vaccine let-down spotlights mRNA design challenges", newsSource: "Nature", newsDate: "June 18, 2020", newsLink: "https://doi.org/10.1038/d41586-021-01661-0"}),
         e(NewsList, {newsType: "Media News", newsTitle: "COVID-19 may cause loss of brain tissue; Delta variant fuels steep infection rise in England", newsSource: "Reuters", newsDate: "June 18, 2020", newsLink: "https://www.reuters.com/business/healthcare-pharmaceuticals/covid-19-may-cause-loss-brain-tissue-delta-variant-fuels-steep-infection-rise-2021-06-18/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "California rolls out digital vaccine verification — but don't call it a passport", newsSource: "NBC News", newsDate: "June 18, 2020", newsLink: "https://www.nbcnews.com/tech/tech-news/california-rolls-digital-vaccine-verification-dont-call-passport-rcna1224"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Safety and immunogenicity of the ChAdOx1 nCoV-19 (AZD1222) vaccine against SARS-CoV-2 in HIV infection: a single-arm substudy of a phase 2/3 clinical trial", newsSource: "Lancet", newsDate: "June 18, 2020", newsLink: "https://doi.org/10.1016/S2352-3018(21)00103-X"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Protected them to death’: Elder-care COVID rules under fire", newsSource: "AP News", newsDate: "June 19, 2020", newsLink: "https://apnews.com/article/coronavirus-pandemic-lifestyle-health-2c6b98804219c731a5e8a9b843594381"}),
         e(NewsList, {newsType: "Media News", newsTitle: "It’s such a relief’: how Europe’s Covid vaccine rollout is catching up with UK", newsSource: "Guardian", newsDate: "June 19, 2020", newsLink: "https://www.theguardian.com/world/2021/jun/19/its-such-a-relief-how-europes-covid-vaccine-rollout-is-catching-up-with-uk?"}),
         e(NewsList, {newsType: "Media News", newsTitle: "U.S. triples vaccines for Taiwan with 2.5 million-dose shipment", newsSource: "National Post", newsDate: "June 19, 2020", newsLink: "https://nationalpost.com/pmn/health-pmn/u-s-triples-vaccines-for-taiwan-with-2-5-million-dose-shipment"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Covid jabs for billions of humans will earn their makers billions of dollars", newsSource: "Guardian", newsDate: "June 19, 2020", newsLink: "https://www.theguardian.com/business/2021/jun/19/covid-jabs-for-billions-of-humans-will-earn-their-makers-billions-of-dollars"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Kids Return To Summer Camp After COVID Kept Them Away Last Year", newsSource: "NPR", newsDate: "June 19, 2020", newsLink: "https://www.npr.org/2021/06/19/1008304531/kids-return-to-summer-camp-after-covid-kept-them-away-last-year"}),
         e(NewsList, {newsType: "Media News", newsTitle: "UK pushes for fully vaccinated to be exempt from Covid self-isolation", newsSource: "Guardian", newsDate: "June 19, 2020", newsLink: "https://www.theguardian.com/world/2021/jun/19/uk-pushes-for-fully-vaccinated-to-be-exempt-from-covid-self-isolation"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Australia Covid update: masks compulsory indoors in parts of Sydney as cluster grows to nine", newsSource: "Guardian", newsDate: "June 20, 2020", newsLink: "https://www.theguardian.com/australia-news/2021/jun/20/australia-covid-update-qld-records-one-new-local-case-as-new-sydney-exposure-sites-named"}),
         e(NewsList, {newsType: "Media News", newsTitle: "BBC tightens security after anti-vaxxer ‘death threats’ to staff", newsSource: "Guardian", newsDate: "June 20, 2020", newsLink: "https://www.theguardian.com/media/2021/jun/20/bbc-tightens-security-after-anti-vaxxer-death-threats-to-staff"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Under-18s could be ‘reservoirs’ for virus when all adults are jabbed, expert warns", newsSource: "Guardian", newsDate: "June 20, 2020", newsLink: "https://www.theguardian.com/society/2021/jun/20/under-18s-could-be-reservoirs-for-virus-when-all-adults-are-jabbed-expert-warns"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Florida county closes government building after COVID deaths", newsSource: "AP News", newsDate: "June 20, 2020", newsLink: "https://apnews.com/article/fl-state-wire-florida-health-coronavirus-pandemic-e4e12243f5b94bfd999b7a278484e9ba"}),
         e(NewsList, {newsType: "Media News", newsTitle: "‘Two Americas’ may emerge as Delta variant spreads and vaccination rates drop", newsSource: "Guardian", newsDate: "June 20, 2020", newsLink: "https://www.theguardian.com/us-news/2021/jun/20/us-covid-delta-variant-spreads-vaccination-rates-drop"}),    
         e(NewsList, {newsType: "Media News", newsTitle: "Models predict U.S. coronavirus infections could surge this fall if vaccination rates lag, former FDA chief says", newsSource: "Washington Post", newsDate: "June 20, 2020", newsLink: "https://www.washingtonpost.com/nation/2021/06/20/us-coronavirus-infection-rate-fall-2021/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Australia’s vaccine rollout ‘constrained’ by Pfizer supply shortages until August", newsSource: "Guardian", newsDate: "June 21, 2020", newsLink: "https://www.theguardian.com/australia-news/2021/jun/21/australias-vaccine-rollout-constrained-by-pfizer-supply-shortages-until-august"}),
         e(NewsList, {newsType: "Media News", newsTitle: "What is 'gain-of-function' and why does it matter in the search for SARS-CoV-2's origins?", newsSource: "PHYS ORG", newsDate: "June 21, 2020", newsLink: "https://phys.org/news/2021-06-gain-of-function-sars-cov-.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "India’s vaccinations hit record with free COVID shots", newsSource: "Reuters", newsDate: "June 21, 2020", newsLink: "https://www.reuters.com/world/india/india-reports-53256-new-covid-19-cases-2021-06-21/"}),
         e(NewsList, {newsType: "Media News", newsTitle: "U.S. to split 55 million Covid vaccine doses between Latin America, Asia and Africa", newsSource: "CNBC", newsDate: "June 21, 2020", newsLink: "https://www.cnbc.com/2021/06/21/covid-vaccine-us-to-split-55-million-doses-between-latin-america-asia-and-africa-.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Covid Rebounds in U.S. South, With Many Shunning Vaccines", newsSource: "Bloomberg", newsDate: "June 21, 2020", newsLink: "https://www.bloomberg.com/news/articles/2021-06-21/covid-rebounds-in-u-s-south-where-many-have-shunned-vaccines"}),
         e(NewsList, {newsType: "Media News", newsTitle: "WHO says delta is the fastest and fittest Covid variant and will ‘pick off’ most vulnerable", newsSource: "CNBC", newsDate: "June 21, 2020", newsLink: "https://www.cnbc.com/2021/06/21/covid-delta-who-says-variant-is-the-fastest-and-fittest-and-will-pick-off-most-vulnerable-.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "A mix-and-match approach to COVID-19 vaccines could provide logistical and immunological benefits", newsSource: "PBS", newsDate: "June 21, 2020", newsLink: "https://www.pbs.org/newshour/health/a-mix-and-match-approach-to-covid-19-vaccines-could-provide-logistical-and-immunological-benefits"}),
         e(NewsList, {newsType: "Media News", newsTitle: "California weighs extending eviction protections past June", newsSource: "AP News", newsDate: "June 21, 2020", newsLink: "https://apnews.com/article/california-health-coronavirus-pandemic-business-government-and-politics-4a9a08ffb93e80e90bae9e649378bfbc"}),    
         e(NewsList, {newsType: "Non Media News", newsTitle: "Assessing the Association Between Social Gatherings and COVID-19 Risk Using Birthdays", newsSource: "Jama Network", newsDate: "June 21, 2020", newsLink: "http://jamanetwork.com/article.aspx?doi=10.1001/jamainternmed.2021.2915"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "COVID-19 Vaccination Coverage Among Adults — United States, December 14, 2020–May 22, 2021", newsSource: "CDC", newsDate: "June 21, 2020", newsLink: "http://dx.doi.org/10.15585/mmwr.mm7025e1"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "COVID-19 Vaccination Coverage and Intent Among Adults Aged 18–39 Years — United States, March–May 2021", newsSource: "CDC", newsDate: "June 21, 2020", newsLink: "http://dx.doi.org/10.15585/mmwr.mm7025e2"}),    
         e(NewsList, {newsType: "Non Media News", newsTitle: "The impact of super-spreader cities, highways, and intensive care availability in the early stages of the COVID-19 epidemic in Brazil", newsSource: "Nature", newsDate: "June 21, 2020", newsLink: "https://doi.org/10.1038/s41598-021-92263-3"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Anti-vax group mounts legal blitz to sow disinformation against vaccinations", newsSource: "Guardian", newsDate: "June 22, 2020", newsLink: "https://www.theguardian.com/us-news/2021/jun/22/anti-vax-group-legal-blitz-deter-vaccinations"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Covid boosters in the fall? As calls grow for third shots, here’s what you need to know", newsSource: "CNBC", newsDate: "June 22, 2020", newsLink: "https://www.cnbc.com/2021/06/22/covid-booster-shots-coronavirus-variants-see-calls-for-third-shots.html"}),
         e(NewsList, {newsType: "Media News", newsTitle: "Cuba says Abdala vaccine 92.28% effective against coronavirus", newsSource: "Reuters", newsDate: "June 22, 2020", newsLink: "https://www.reuters.com/business/healthcare-pharmaceuticals/cuba-says-abdala-vaccine-9228-effective-against-coronavirus-2021-06-21/"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Correcting pandemic data analysis through environmental fluid dynamics", newsSource: "Physics of Fluids", newsDate: "June 22, 2020", newsLink: "https://doi.org/10.1063/5.0055299"}),
         e(NewsList, {newsType: "Non Media News", newsTitle: "Two additional manufacturing sites for BioNTech/Pfizer’s COVID-19 vaccine", newsSource: "European Commission", newsDate: "June 22, 2020", newsLink: "https://www.ema.europa.eu/en/news/two-additional-manufacturing-sites-biontechpfizers-covid-19-vaccine"})
   ); 
 }
}

document.addEventListener("DOMContentLoaded", function(event) {
  ReactDOM.render(
  e(NewsApp), 
  //e(Welcome, {name: "Person"}),
  document.querySelector('#article-main-june2021')
  );
});

const pfizerUpdate = document.querySelector('.pfizer-update')
    pfizerUpdate.innerHTML = "Last Updated: 6/20/2021";
const modernaUpdate = document.querySelector('.moderna-update')
    modernaUpdate.innerHTML = "Last Updated: 6/20/2021";
const jessenUpdate = document.querySelector('.jessen-update')
    jessenUpdate.innerHTML = "Last Updated: 6/20/2021";
